const crypto = window.crypto || window.msCrypto;

const base64UrlSafeChars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-'.split('');

export function generateUniqueShortId(desiredLength = 16) {
  let result = '';

  for (let i = 0; i < desiredLength; i++) {
    result += base64UrlSafeChars[randomByte() % base64UrlSafeChars.length];
  }

  return result;
}

function randomByte() {
  if (!crypto || !crypto.getRandomValues) {
    return Math.floor(Math.random() * 256);
  }
  const dest = new Uint8Array(1);
  crypto.getRandomValues(dest);
  return dest[0];
}

// Objects are ordered in JavaScript and in JSON. As a result of that, JSON.stringify
// output depends on property insertion order in objects. This is sometimes useful and
// irrelevant most of the time.
//
// We never make any assumptions on the order of properties and on the server side we
// also ignore this. Within the UI, we have some places which want to use the "hash"
// (JSON.stringify) of an object to determine changes between two objects. One such
// place are the IDs of our subscriptions.
//
// The hash generated by this function is a small wrapper around JSON.stringify which
// ensures that the generated string is order independent.
export function generateStableHash(obj) {
  if (obj === undefined) {
    return 'undefined';
  } else if (obj == null) {
    return 'null';
  } else if (obj instanceof Array) {
    return '[' + obj.map(v => (v === undefined ? 'null' : generateStableHash(v))).join(',') + ']';
  } else if (typeof obj === 'object') {
    const values = Object.keys(obj)
      .sort()
      .filter(k => obj[k] !== undefined)
      .map(k => `"${k}":${generateStableHash(obj[k])}`)
      .join(',');

    return `{${values}}`;
  }
  return JSON.stringify(obj);
}
