/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

export const mockEmptyPermissionsSet = {
  applicationIds: [],
  kubernetesClusterUUIDs: [],
  kubernetesNamespaceUIDs: [],
  mobileAppIds: [],
  permissions: [],
  websiteIds: [],
  syntheticTestIds: []
};

const mockPermissionsWithLimitedAccess = [
  'LIMITED_WEBSITES_SCOPE',
  'ACCESS_APPLICATIONS',
  'ACCESS_WEBSITES',
  'ACCESS_VSPHERE',
  'CAN_VIEW_TRACE_DETAILS',
  'ACCESS_MOBILE_APPS',
  'CAN_CONFIGURE_AGENTS',
  'CAN_CONFIGURE_EUM_APPLICATIONS',
  'LIMITED_OPENSTACK_SCOPE',
  'CAN_CONFIGURE_AUTOMATION_ACTIONS',
  'ACCESS_SYNTHETICS',
  'CAN_CONFIGURE_INTEGRATIONS',
  'LIMITED_PCF_SCOPE',
  'LIMITED_SYNTHETICS_SCOPE',
  'CAN_CONFIGURE_GLOBAL_ALERT_CONFIGS',
  'CAN_CONFIGURE_GLOBAL_ALERT_PAYLOAD',
  'LIMITED_INFRASTRUCTURE_SCOPE',
  'CAN_CONFIGURE_MOBILE_APP_MONITORING',
  'CAN_CONFIGURE_SERVICE_LEVEL_INDICATORS',
  'ACCESS_INFRASTRUCTURE',
  'LIMITED_APPLICATIONS_SCOPE',
  'CAN_CONFIGURE_RELEASES',
  'LIMITED_VSPHERE_SCOPE',
  'ACCESS_KUBERNETES',
  'LIMITED_MOBILE_APPS_SCOPE',
  'CAN_CONFIGURE_CUSTOM_ALERTS',
  'CAN_CONFIGURE_AGENT_RUN_MODE',
  'LIMITED_ZHMC_SCOPE',
  'CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS',
  'LIMITED_KUBERNETES_SCOPE',
  'CAN_INSTALL_NEW_AGENTS',
  'CAN_RUN_AUTOMATION_ACTIONS',
  'CAN_VIEW_AUTOMATION_ACTION_INSTANCES',
  'CAN_CONFIGURE_TEAMS',
  'CAN_CREATE_PUBLIC_CUSTOM_DASHBOARDS',
  'CAN_CONFIGURE_LOG_MANAGEMENT',
  'LIMITED_PHMC_SCOPE',
  'LIMITED_POWERVC_SCOPE',
  'LIMITED_SAP_SCOPE',
  'CAN_CONFIGURE_APPLICATIONS'
];

const mockPermissionsLimitedNoAccess = [
  'CAN_VIEW_LOGS',
  'CAN_VIEW_TRACE_DETAILS',
  'LIMITED_WEBSITES_SCOPE',
  'LIMITED_APPLICATIONS_SCOPE',
  'LIMITED_VSPHERE_SCOPE',
  'LIMITED_MOBILE_APPS_SCOPE',
  'LIMITED_OPENSTACK_SCOPE',
  'LIMITED_ZHMC_SCOPE',
  'LIMITED_KUBERNETES_SCOPE',
  'LIMITED_SAP_SCOPE',
  'LIMITED_PCF_SCOPE',
  'LIMITED_SYNTHETICS_SCOPE',
  'LIMITED_PHMC_SCOPE',
  'LIMITED_POWERVC_SCOPE',
  'LIMITED_INFRASTRUCTURE_SCOPE'
];

const mockPermissionsWithFullAccess = [
  'ACCESS_APPLICATIONS',
  'ACCESS_WEBSITES',
  'ACCESS_VSPHERE',
  'CAN_VIEW_TRACE_DETAILS',
  'ACCESS_MOBILE_APPS',
  'CAN_CONFIGURE_AGENTS',
  'CAN_CONFIGURE_EUM_APPLICATIONS',
  'CAN_CONFIGURE_AUTOMATION_ACTIONS',
  'ACCESS_SYNTHETICS',
  'CAN_CONFIGURE_INTEGRATIONS',
  'CAN_CONFIGURE_GLOBAL_ALERT_CONFIGS',
  'CAN_CONFIGURE_GLOBAL_ALERT_PAYLOAD',
  'CAN_CONFIGURE_MOBILE_APP_MONITORING',
  'CAN_CONFIGURE_SERVICE_LEVEL_INDICATORS',
  'ACCESS_INFRASTRUCTURE',
  'CAN_CONFIGURE_RELEASES',
  'ACCESS_KUBERNETES',
  'CAN_CONFIGURE_CUSTOM_ALERTS',
  'CAN_CONFIGURE_AGENT_RUN_MODE',
  'CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS',
  'CAN_INSTALL_NEW_AGENTS',
  'CAN_RUN_AUTOMATION_ACTIONS',
  'CAN_VIEW_AUTOMATION_ACTION_INSTANCES',
  'CAN_CONFIGURE_TEAMS',
  'CAN_CREATE_PUBLIC_CUSTOM_DASHBOARDS',
  'CAN_CONFIGURE_LOG_MANAGEMENT',
  'CAN_CONFIGURE_APPLICATIONS'
];

export const mockPermissionsSetWithData = {
  applicationIds: [
    { scopeId: '1', scopeRoleId: '11' },
    { scopeId: '2', scopeRoleId: '22' }
  ],
  kubernetesClusterUUIDs: [
    { scopeId: '3', scopeRoleId: '33' },
    { scopeId: '4', scopeRoleId: '44' }
  ],
  kubernetesNamespaceUIDs: [
    { scopeId: '5', scopeRoleId: '55' },
    { scopeId: '6', scopeRoleId: '66' }
  ],
  mobileAppIds: [
    { scopeId: '7', scopeRoleId: '77' },
    { scopeId: '8', scopeRoleId: '88' }
  ],
  websiteIds: [
    { scopeId: '11', scopeRoleId: '1111' },
    { scopeId: '12', scopeRoleId: '1212' }
  ],
  syntheticTestIds: [],
  permissions: mockPermissionsWithLimitedAccess
};

export const mockPermissionsSetWithFullAccessData = {
  ...mockPermissionsSetWithData,
  permissions: mockPermissionsWithFullAccess
};

export const mockPermissionsSetWithLimitedAccessEmptyData = {
  ...mockEmptyPermissionsSet,
  permissions: mockPermissionsLimitedNoAccess
};
