/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */

import { assign } from 'lodash';

/* eslint-disable max-len */
export const ID_OF_UNMONITORED_ZONE = '5nXT64z0gY0pShCaT5VQ7wGu-0E';
export const ID_OF_PROCESSING_STATISTICS = '_9Ct9EsdanGCFtGIG_j7wNKr5hE';
export const ID_OF_REGION = '7c238Z6UhpGTsuCTCehWnBoiaxs';

export const nonServicePlugins = {
  aceIntegrationNode: 'aceIntegrationNode',
  aceIntegrationServer: 'aceIntegrationServer',
  aceMessageFlow: 'aceMessageFlow',
  aceFlowNode: 'aceFlowNode',
  activeMQ: 'activeMQ',
  activeMQArtemis: 'activeMQArtemis',
  aerospike: 'aerospike',
  apmProxy: 'apmProxy',
  availabilityZone: 'availabilityZone',
  awsBeanstalk: 'awsBeanstalk',
  awsDynamoDb: 'awsDynamoDb',
  awsEc: 'awsEc',
  awsEcs: 'awsEcs',
  awsEcsCluster: 'awsEcsCluster',
  awsEcsContainer: 'awsEcsContainer',
  awsEcsService: 'awsEcsService',
  awsEcsTask: 'awsEcsTask',
  awsEs: 'awsEs',
  awsElb: 'awsElb',
  awsEmr: 'awsEmr',
  awsKinesis: 'awsKinesis',
  awsLambdaFunction: 'awsLambdaFunction',
  awsLambdaVersion: 'awsLambdaVersion',
  // legacy AWS Lambda plug-in
  awsLambda: 'awsLambda',
  awsMq: 'awsMq',
  awsMskCluster: 'awsMskCluster',
  awsMskBroker: 'awsMskBroker',
  awsRds: 'awsRds',
  awsSqs: 'awsSqs',
  awsS3: 'awsS3',
  awsEbs: 'awsEbs',
  azure: 'azure',
  azureApiManagement: 'azureApiManagement',
  azureAppService: 'azureAppService',
  azureCosmosDb: 'azureCosmosDb',
  azureRedisCache: 'azureRedisCache',
  azureSqlDb: 'azureSqlDb',
  azureSqlElasticPool: 'azureSqlElasticPool',
  azureSqlServer: 'azureSqlServer',
  azureStorage: 'azureStorage',
  beeInstanaNode: 'beeInstanaNode',
  bizTalk: 'bizTalk',
  cassandraNode: 'cassandraNode',
  cassandraCluster: 'cassandraCluster',
  ceph: 'ceph',
  clrRuntimePlatform: 'clrRuntimePlatform',
  clickHouseDatabase: 'clickHouseDatabase',
  clickHouseCluster: 'clickHouseCluster',
  cloudFoundry: 'cloudFoundry',
  cockroachDBCluster: 'cockroachDBCluster',
  cockroachDBNode: 'cockroachDBNode',
  containerd: 'containerd',
  crio: 'crio',
  consul: 'consul',
  consulCluster: 'consulCluster',
  couchbaseNode: 'couchbaseNode',
  couchbaseCluster: 'couchbaseCluster',
  crystalRuntimePlatform: 'crystalRuntimePlatform',
  db2Database: 'db2Database',
  docker: 'docker',
  dropwizardApplicationContainer: 'dropwizardApplicationContainer',
  ec2: 'ec2',
  elasticsearchNode: 'elasticsearchNode',
  elasticsearchCluster: 'elasticsearchCluster',
  etcd: 'etcd',
  finagleApplicationContainer: 'finagleApplicationContainer',
  f5: 'f5',
  garden: 'garden',
  gce: 'gce',
  genericHardware: 'genericHardware',
  genericZone: 'genericZone',
  glassfishApplicationContainer: 'glassfishApplicationContainer',
  golangRuntimePlatform: 'golangRuntimePlatform',
  googleCloudDatastore: 'googleCloudDatastore',
  googleCloudPubSub: 'googleCloudPubSub',
  googleCloudPubSubSubscription: 'googleCloudPubSubSubscription',
  googleCloudPubSubTopic: 'googleCloudPubSubTopic',
  googleCloudRunServiceRevision: 'googleCloudRunServiceRevision',
  googleCloudRunServiceRevisionInstance: 'googleCloudRunServiceRevisionInstance',
  googleCloudSQL: 'googleCloudSQL',
  googleCloudStorage: 'googleCloudStorage',
  hadoopYARN: 'hadoopYARN',
  hadoopYARNNode: 'hadoopYARNNode',
  hAProxy: 'hAProxy',
  haskellRuntimePlatform: 'haskellRuntimePlatform',
  hazelcastCluster: 'hazelcastCluster',
  hazelcastNode: 'hazelcastNode',
  hBase: 'hBase',
  host: 'host',
  httpd: 'httpd',
  ibmcloudCloudant: 'ibmcloudCloudant',
  ibmcloudEtcd: 'ibmcloudEtcd',
  ibmcloudFunctions: 'ibmcloudFunctions',
  ibmcloudLoadBalancer: 'ibmcloudLoadBalancer',
  ibmcloudObjectStorage: 'ibmcloudObjectStorage',
  ibmcloudVSI: 'ibmcloudVSI',
  ibmDataPowerCluster: 'ibmDataPowerCluster',
  ibmDataPowerAppliance: 'ibmDataPowerAppliance',
  ibmDataPowerDomain: 'ibmDataPowerDomain',
  ibmDataPowerService: 'ibmDataPowerService',
  ibmDataPowerSqlDatasource: 'ibmDataPowerSqlDatasource',
  ibmDataPowerQueueManager: 'ibmDataPowerQueueManager',
  ibmDataPowerEthernetInterface: 'ibmDataPowerEthernetInterface',
  ibmMqCluster: 'ibmMqCluster',
  ibmMqQueueManager: 'ibmMqQueueManager',
  ibmMqChannel: 'ibmMqChannel',
  ibmMqListener: 'ibmMqListener',
  ibmMqQueue: 'ibmMqQueue',
  ibmMqQueueUsage: 'ibmMqQueueUsage',
  ibmMqTopic: 'ibmMqTopic',
  instanaAgent: 'instanaAgent',
  jBossAsApplicationContainer: 'jBossAsApplicationContainer',
  jbossDataGrid: 'jbossDataGrid',
  jenkins: 'jenkins',
  jettyApplicationContainer: 'jettyApplicationContainer',
  jiraApplication: 'jiraApplication',
  jvmRuntimePlatform: 'jvmRuntimePlatform',
  kafka: 'kafka',
  kafkaCluster: 'kafkaCluster',
  kafkaConnectCluster: 'kafkaConnectCluster',
  kafkaConnectConnector: 'kafkaConnectConnector',
  kafkaConnectWorker: 'kafkaConnectWorker',
  kubernetesCluster: 'kubernetesCluster',
  kubernetesCronJob: 'kubernetesCronJob',
  kubernetesJob: 'kubernetesJob',
  kubernetesDaemonSet: 'kubernetesDaemonSet',
  kubernetesDeployment: 'kubernetesDeployment',
  kubernetesNamespace: 'kubernetesNamespace',
  kubernetesNode: 'kubernetesNode',
  kubernetesPod: 'kubernetesPod',
  kubernetesReplicaSet: 'kubernetesReplicaSet',
  kubernetesService: 'kubernetesService',
  kubernetesStatefulSet: 'kubernetesStatefulSet',
  kubernetesPersistentVolume: 'kubernetesPersistentVolume',
  kubernetesPersistentVolumeClaim: 'kubernetesPersistentVolumeClaim',
  liferayApplicationContainer: 'liferayApplicationContainer',
  lxc: 'lxc',
  mariaDbDatabase: 'mariaDbDatabase',
  memcached: 'memcached',
  mongoDb: 'mongoDb',
  mongoDbCluster: 'mongoDbCluster',
  mongoDbReplicaSet: 'mongoDbReplicaSet',
  msiis: 'msiis',
  msSqlDatabase: 'msSqlDatabase',
  mule: 'mule',
  mySqlDatabase: 'mySqlDatabase',
  nats: 'nats',
  natsStreaming: 'natsStreaming',
  netCoreRuntimePlatform: 'netCoreRuntimePlatform',
  neo4j: 'neo4j',
  nginx: 'nginx',
  nodeJsRuntimePlatform: 'nodeJsRuntimePlatform',
  nomadScheduler: 'nomadScheduler',
  nova: 'nova',
  opc: 'opc',
  oracleDB: 'oracleDB',
  openLDAP: 'openLDAP',
  openshiftDeploymentConfig: 'openshiftDeploymentConfig',
  packet: 'packet',
  pCFApplication: 'pCFApplication',
  pCFOrganization: 'pCFOrganization',
  pCFSpace: 'pCFSpace',
  phpFpmRuntimePlatform: 'phpFpmRuntimePlatform',
  phpRuntimePlatform: 'phpRuntimePlatform',
  ping: 'ping',
  pingDirectory: 'pingDirectory',
  postgreSqlDatabase: 'postgreSqlDatabase',
  process: 'process',
  prometheus: 'prometheus',
  pythonRuntimePlatform: 'pythonRuntimePlatform',
  rabbitMq: 'rabbitMq',
  redis: 'redis',
  redisCluster: 'redisCluster',
  redisEnterpriseNode: 'redisEnterpriseNode',
  redisEnterpriseCluster: 'redisEnterpriseCluster',
  rubyRuntimePlatform: 'rubyRuntimePlatform',
  sapHana: 'sapHana',
  solr: 'solr',
  solrCloudCluster: 'solrCloudCluster',
  sparkApplication: 'sparkApplication',
  sparkStandalone: 'sparkStandalone',
  springbootApplicationContainer: 'springbootApplicationContainer',
  statsd: 'statsd',
  sybase: 'sybase',
  tanzuFoundation: 'tanzuFoundation',
  tanzuFoundationMember: 'tanzuFoundationMember',
  tibcoEMS: 'tibcoEMS',
  tomcatApplicationContainer: 'tomcatApplicationContainer',
  unmonitoredHost: 'unmonitoredHost',
  varnish: 'varnish',
  vault: 'vault',
  vsphereDatacenter: 'vsphereDatacenter',
  vsphereHost: 'vsphereHost',
  vsphereVM: 'vsphereVM',
  webLogicApplicationContainer: 'webLogicApplicationContainer',
  webSphereApplicationContainer: 'webSphereApplicationContainer',
  webSphereLibertyApplicationContainer: 'webSphereLibertyApplicationContainer',
  zooKeeper: 'zooKeeper'
};

export const applicationPlugins = {
  application: 'application',
  defaultEntity20: 'defaultEntity20',
  endpoint: 'endpoint',
  service: 'service'
};

export const plugins = assign({}, applicationPlugins, nonServicePlugins);

export const defaultAndUnknownPluginNames = [
  'unknownService',
  'defaultEntity20',
  'defaultLogicalConnection',
  'defaultLogicalService',
  'defaultServiceInstance'
];

export const customIssuesDisabledForPlugins = [...defaultAndUnknownPluginNames];

export const fullyQualifiedPlugins = {
  aceIntegrationNode: 'com.instana.forge.infrastructure.messaging.ace.AceIntegrationNode',
  aceIntegrationServer:
    'com.instana.forge.infrastructure.messaging.ace.derivedentity.aceIntegrationServer.AceIntegrationServer',
  aceMessageFlow: 'com.instana.forge.infrastructure.messaging.ace.derivedentity.aceMessageFlow.AceMessageFlow',
  aceFlowNode: 'com.instana.forge.infrastructure.messaging.ace.derivedentity.aceFlowNode.AceFlowNode',
  activeMQ: 'com.instana.forge.infrastructure.messaging.activemq.ActiveMQ',
  activeMQArtemis: 'com.instana.forge.infrastructure.messaging.activemqartemis.ActiveMQArtemis',
  aerospike: 'aerospike',
  apmProxy: 'apmProxy',
  application: 'com.instana.forge.application.Application',
  availabilityZone: 'com.instana.forge.hardware.AvailabilityZone',
  awsBeanstalk: 'com.instana.forge.hardware.virtual.aws.beanstalk.AwsBeanstalk',
  awsDynamoDb: 'com.instana.forge.hardware.virtual.aws.dynamodb.AwsDynamoDb',
  awsEc: 'com.instana.forge.hardware.virtual.aws.ec.AwsEc',
  awsEcs: 'com.instana.forge.hardware.virtual.aws.ecs.cluster.awsEcs',
  awsEcsCluster: 'com.instana.forge.hardware.virtual.aws.ecs.cluster.awsEcsCluster',
  awsEcsContainer: 'com.instana.forge.hardware.virtual.aws.ecs.container.AwsEcsContainer',
  awsEcsService: 'com.instana.forge.hardware.virtual.aws.ecs.service.awsEcsService',
  awsEcsTask: 'com.instana.forge.hardware.virtual.aws.ecs.task.AwsEcsTask',
  awsEs: 'com.instana.forge.hardware.virtual.aws.es.AwsEs',
  awsElb: 'com.instana.forge.hardware.virtual.aws.elb.AwsElb',
  awsEmr: 'com.instana.forge.hardware.virtual.aws.emr.AwsEmr',
  awsKinesis: 'com.instana.forge.hardware.virtual.aws.kinesis.AwsKinesis',
  awsLambdaVersion: 'com.instana.forge.hardware.virtual.aws.lambda.version.AwsLambdaVersion',
  awsLambdaFunction: 'com.instana.forge.hardware.virtual.aws.lambda.function.AwsLambdaFunction',
  awsLambda: 'com.instana.forge.hardware.virtual.aws.lambda.AwsLambda',
  awsMq: 'com.instana.forge.hardware.virtual.aws.mq.AwsMq',
  awsMskCluster: 'com.instana.forge.hardware.virtual.aws.msk.derivedentity.cluster.AwsMskCluster',
  awsMskBroker: 'com.instana.forge.hardware.virtual.aws.msk.derivedentity.broker.AwsMskBroker',
  awsRds: 'com.instana.forge.hardware.virtual.aws.rds.AwsRds',
  awsSqs: 'com.instana.forge.hardware.virtual.aws.sqs.AwsSqs',
  awsS3: 'com.instana.forge.hardware.virtual.aws.sqs.AwsS3',
  awsEbs: 'com.instana.forge.hardware.virtual.aws.ebs.AwsEbs',
  azure: 'com.instana.forge.hardware.virtual.azure.Azure',
  azureApiManagement: 'com.instana.forge.hardware.virtual.azure.apimanagement.AzureApiManagement',
  azureAppService: 'com.instana.forge.hardware.virtual.azure.appservice.AzureAppService',
  azureCosmosDb: 'com.instana.forge.hardware.virtual.azure.cosmosdb.AzureCosmosDb',
  azureRedisCache: 'com.instana.forge.hardware.virtual.azure.rediscache.AzureRedisCache',
  azureStorage: 'com.instana.forge.hardware.virtual.azure.storage.AzureStorage',
  azureSqlDb: 'com.instana.forge.hardware.virtual.azure.sqldb.AzureSqlDb',
  azureSqlElasticPool: 'com.instana.forge.hardware.virtual.azure.sqlelasticpool.AzureSqlElasticPool',
  azureSqlServer: 'com.instana.forge.hardware.virtual.azure.sqlserver.AzureSqlServer',
  beeInstanaNode: 'com.instana.forge.infrastructure.database.beeinstana.BeeInstanaNode',
  bizTalk: 'com.instana.forge.infrastructure.messaging.biztalk.BizTalk',
  cassandraCluster: 'com.instana.forge.infrastructure.database.cassandra.CassandraCluster',
  cassandraNode: 'com.instana.forge.infrastructure.database.cassandra.CassandraNode',
  ceph: 'com.instana.forge.infrastructure.database.ceph.Ceph',
  clrRuntimePlatform: 'com.instana.forge.infrastructure.runtime.clr.ClrRuntimePlatform',
  clickHouseDatabase: 'com.instana.forge.infrastructure.database.clickhouse.ClickHouseDatabase',
  clickHouseCluster: 'com.instana.forge.infrastructure.database.clickhouse.ClickHouseCluster',
  cloudFoundry: 'com.instana.forge.infrastructure.paas.cloudfoundry.CloudFoundry',
  cockroachDBCluster: 'com.instana.forge.infrastructure.database.cockroachdb.CockroachDBCluster',
  cockroachDBNode: 'com.instana.forge.infrastructure.database.cockroachdb.CockroachDBNode',
  containerd: 'com.instana.forge.infrastructure.virtualization.containerd.Containerd',
  crio: 'com.instana.forge.infrastructure.virtualization.crio.Crio',
  consul: 'com.instana.forge.infrastructure.discovery.consul.Consul',
  consulCluster: 'com.instana.forge.infrastructure.discovery.consul.ConsulCluster',
  couchbaseCluster: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseCluster',
  couchbaseNode: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseNode',
  crystalRuntimePlatform: 'com.instana.forge.infrastructure.runtime.crystal.CrystalRuntimePlatform',
  db2Database: 'com.instana.forge.infrastructure.database.db2.Db2Database',
  defaultEntity20: 'defaultEntity20',
  docker: 'com.instana.forge.infrastructure.virtualization.docker.Docker',
  dropwizardApplicationContainer:
    'com.instana.forge.infrastructure.application.dropwizard.DropwizardApplicationContainer',
  ec2: 'com.instana.forge.hardware.virtual.ec2.Ec2',
  elasticsearchCluster: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchCluster',
  elasticsearchNode: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchNode',
  endpoint: 'com.instana.forge.application.Endpoint',
  etcd: 'com.instana.forge.infrastructure.cache.etcd.Etcd',
  finagleApplicationContainer: 'com.instana.forge.infrastructure.application.finagle.FinagleApplicationContainer',
  f5: 'com.instana.forge.infrastructure.loadbalancer.F5',
  garden: 'com.instana.forge.infrastructure.virtualization.garden.Garden',
  gce: 'com.instana.forge.hardware.virtual.gce.Gce',
  googleCloudDatastore: 'com.instana.forge.hardware.virtual.gcp.datastore.GoogleCloudDatastore',
  googleCloudPubSub: 'com.instana.forge.hardware.virtual.gcp.pubsub.GoogleCloudPubSub',
  googleCloudPubSubSubscription:
    'com.instana.forge.hardware.virtual.gcp.pubsub.derivedentity.subscription.GoogleCloudPubSubSubscription',
  googleCloudPubSubTopic: 'com.instana.forge.hardware.virtual.gcp.pubsub.derivedentity.topic.GoogleCloudPubSubTopic',
  googleCloudRunServiceRevision: 'com.instana.forge.hardware.virtual.gcp.run.revision.GoogleCloudRunServiceRevision',
  googleCloudRunServiceRevisionInstance:
    'com.instana.forge.hardware.virtual.gcp.run.instance.GoogleCloudRunServiceRevisionInstance',
  googleCloudSQL: 'com.instana.forge.hardware.virtual.gcp.sql.GoogleCloudSQL',
  googleCloudStorage: 'com.instana.forge.hardware.virtual.gcp.storage.GoogleCloudStorage',
  genericHardware: 'com.instana.forge.hardware.GenericHardware',
  genericZone: 'com.instana.forge.hardware.GenericZone',
  glassfishApplicationContainer: 'com.instana.forge.infrastructure.application.glassfish.GlassfishApplicationContainer',
  golangRuntimePlatform: 'com.instana.forge.infrastructure.runtime.golang.GolangRuntimePlatform',
  hadoopYARN: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarn.HadoopYARN',
  hadoopYARNNode: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarnnode.HadoopYARNNode',
  hAProxy: 'com.instana.forge.infrastructure.loadbalancer.haproxy.HAProxy',
  haskellRuntimePlatform: 'com.instana.forge.infrastructure.runtime.haskell.HaskellRuntimePlatform',
  hazelcastCluster: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastCluster',
  hazelcastNode: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastNode',
  hBase: 'com.instana.forge.infrastructure.database.hbase.HBase',
  host: 'com.instana.forge.infrastructure.os.host.Host',
  httpd: 'com.instana.forge.infrastructure.webserver.httpd.Httpd',
  ibmcloudCloudant: 'com.instana.forge.infrastructure.database.ibmcloud.cloudant.IBMCloudCloudant',
  ibmcloudEtcd: 'com.instana.forge.infrastructure.database.ibmcloud.etcd.IBMCloudEtcd',
  ibmcloudFunctions: 'com.instana.forge.infrastructure.faas.ibmcloud.functions.IBMCloudFunctions',
  ibmcloudLoadBalancer: 'com.instana.forge.infrastructure.loadbalancer.ibmcloud.loadbalancer.IBMCloudLoadBalancer',
  ibmcloudObjectStorage: 'com.instana.forge.hardware.virtual.ibm.cos.IBMCOS',
  ibmcloudVSI: 'com.instana.forge.hardware.virtual.ibm.vsi.IBMVSI',
  ibmDataPowerCluster: 'com.instana.forge.infrastructure.messaging.ibmdatapower.IbmDataPowerCluster',
  ibmDataPowerAppliance:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.appliance.IbmDataPowerAppliance',
  ibmDataPowerDomain: 'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.domain.IbmDataPowerDomain',
  ibmDataPowerService:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.service.IbmDataPowerService',
  ibmDataPowerSqlDatasource:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.sqldatasource.IbmDataPowerSqlDatasource',
  ibmDataPowerQueueManager:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.queueManager.IbmDataPowerQueueManager',
  ibmDataPowerEthernetInterface:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.ethernetinterface.IbmDataPowerEthernetInterface',
  ibmMqCluster: 'com.instana.forge.infrastructure.messaging.ibmmq.IbmMqCluster',
  ibmMqQueueManager: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.queuemanager.IbmMqQueueManager',
  ibmMqChannel: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.channel.IbmMqChannel',
  ibmMqListener: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.listener.IbmMqListener',
  ibmMqQueue: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.queue.IbmMqQueue',
  ibmMqQueueUsage: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.queueusage.IbmMqQueueUsage',
  ibmMqTopic: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.topic.IbmMqTopic',
  instanaAgent: 'com.instana.forge.infrastructure.application.instana.agent.InstanaAgent',
  jBossAsApplicationContainer: 'com.instana.forge.infrastructure.application.jbossas.JBossAsApplicationContainer',
  jbossDataGrid: 'com.instana.forge.infrastructure.cache.jbossdatagrid.JbossDataGrid',
  jenkins: 'com.instana.forge.infrastructure.ci_cd.jenkins.Jenkins',
  jettyApplicationContainer: 'com.instana.forge.infrastructure.application.jetty.JettyApplicationContainer',
  jiraApplication: 'com.instana.forge.infrastructure.application.jira.JiraApplication',
  jvmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.jvm.JvmRuntimePlatform',
  kafka: 'com.instana.forge.infrastructure.messaging.kafka.Kafka',
  kafkaCluster: 'com.instana.forge.infrastructure.messaging.kafka.KafkaCluster',
  kafkaConnectCluster:
    'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.cluster.KafkaConnectCluster',
  kafkaConnectConnector:
    'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.connector.KafkaConnectConnector',
  kafkaConnectWorker: 'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.worker.KafkaConnectWorker',
  kubernetesCluster: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesCluster',
  kubernetesCronJob: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.job.KubernetesCronJob',
  kubernetesDaemonSet: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.daemonset.KubernetesDaemonSet',
  kubernetesDeployment:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.deployment.KubernetesDeployment',
  kubernetesJob: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.job.KubernetesJob',
  kubernetesNamespace: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.namespace.KubernetesNamespace',
  kubernetesNode: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.node.KubernetesNode',
  kubernetesPersistentVolume:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.volume.kubernetesPersistentVolume',
  kubernetesPersistentVolumeClaim:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.volume.kubernetesPersistentVolumeClaim',
  kubernetesPod: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.pod.KubernetesPod',
  kubernetesReplicaSet:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.replicaset.KubernetesReplicaSet',
  kubernetesService: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.service.KubernetesService',
  kubernetesStatefulSet:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.statefulset.KubernetesStatefulSet',
  liferayApplicationContainer: 'com.instana.forge.infrastructure.application.liferay.LiferayApplicationContainer',
  lxc: 'com.instana.forge.infrastructure.virtualization.lxc.Lxc',
  mariaDbDatabase: 'com.instana.forge.infrastructure.database.mariadb.MariaDbDatabase',
  memcached: 'com.instana.forge.infrastructure.cache.memcached.Memcached',
  mongoDb: 'com.instana.forge.infrastructure.database.mongodb.MongoDb',
  mongoDbCluster: 'com.instana.forge.connection.database.mongodb.MongoDbCluster',
  mongoDbReplicaSet: 'com.instana.forge.connection.database.mongodb.MongoDbReplicaSet',
  msiis: 'com.instana.forge.infrastructure.webserver.msiis.Msiis',
  msSqlDatabase: 'com.instana.forge.infrastructure.database.mssql.MsSqlDatabase',
  mule: 'com.instana.forge.infrastructure.messaging.mule.Mule',
  mySqlDatabase: 'com.instana.forge.infrastructure.database.mysql.MySqlDatabase',
  nats: 'nats',
  natsStreaming: 'natsStreaming',
  neo4j: 'com.instana.forge.infrastructure.database.neo4j.Neo4j',
  netCoreRuntimePlatform: 'com.instana.forge.infrastructure.runtime.netcore.NetCoreRuntimePlatform',
  nomadScheduler: 'com.instana.forge.infrastructure.scheduler.nomad.NomadScheduler',
  nginx: 'com.instana.forge.infrastructure.webserver.nginx.Nginx',
  nodeJsRuntimePlatform: 'com.instana.forge.infrastructure.runtime.nodejs.NodeJsRuntimePlatform',
  nova: 'com.instana.forge.hardware.virtual.openstack.Nova',
  opc: 'com.instana.forge.hardware.virtual.opc.Opc',
  oracleDB: 'com.instana.forge.infrastructure.database.oracledb.OracleDB',
  openLDAP: 'com.instana.forge.infrastructure.directory.openldap.OpenLDAP',
  openshiftDeploymentConfig:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.openshift.deploymentconfig.OpenshiftDeploymentConfig',
  packet: 'com.instana.forge.hardware.virtual.Packet',
  pCFApplication: 'com.instana.forge.infrastructure.paas.cloudfoundry.PCFApplication',
  pCFOrganization: 'com.instana.forge.infrastructure.paas.cloudfoundry.PCFOrganization',
  pCFSpace: 'com.instana.forge.infrastructure.paas.cloudfoundry.PCFSpace',
  phpFpmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.phpfpm.PhpFpmRuntimePlatform',
  phpRuntimePlatform: 'com.instana.forge.infrastructure.runtime.php.PhpRuntimePlatform',
  ping: 'com.instana.forge.infrastructure.synthetic.ping.Ping',
  pingDirectory: 'com.instana.forge.infrastructure.directory.pingdirectory.PingDirectory',
  postgreSqlDatabase: 'com.instana.forge.infrastructure.database.postgresql.PostgreSqlDatabase',
  process: 'com.instana.forge.infrastructure.os.process.Process',
  prometheus: 'com.instana.forge.infrastructure.custom.prometheus.Prometheus',
  pythonRuntimePlatform: 'com.instana.forge.infrastructure.runtime.python.PythonRuntimePlatform',
  rabbitMq: 'com.instana.forge.infrastructure.messaging.rabbitmq.RabbitMq',
  redis: 'com.instana.forge.infrastructure.cache.redis.Redis',
  redisEnterpriseNode: 'com.instana.forge.infrastructure.cache.redisenterprise.derivedentity.node.RedisEnterpriseNode',
  redisCluster: 'com.instana.forge.infrastructure.cache.redis.RedisCluster',
  redisEnterpriseCluster: 'com.instana.forge.infrastructure.cache.redisenterprise.RedisEnterpriseCluster',
  rubyRuntimePlatform: 'com.instana.forge.infrastructure.runtime.ruby.RubyRuntimePlatform',
  sapHana: 'com.instana.forge.infrastructure.database.saphana.SapHana',
  service: 'com.instana.forge.application.Service',
  solr: 'com.instana.forge.infrastructure.database.solr.Solr',
  solrCloudCluster: 'com.instana.forge.infrastructure.database.solr.SolrCloudCluster',
  springbootApplicationContainer:
    'com.instana.forge.infrastructure.application.springboot.SpringbootApplicationContainer',
  sparkApplication: 'com.instana.forge.infrastructure.dataanalytics.sparkapplication.SparkApplication',
  sparkStandalone: 'com.instana.forge.infrastructure.dataanalytics.sparkstandalone.SparkStandalone',
  statsd: 'com.instana.forge.common.Statsd',
  sybase: 'com.instana.forge.infrastructure.database.sybase.Sybase',
  tanzuFoundation: 'com.instana.forge.infrastructure.paas.cloudfoundry.tanzu_foundation.TanzuFoundation',
  tanzuFoundationMember: 'com.instana.forge.infrastructure.paas.cloudfoundry.tanzu_foundation.TanzuFoundationMember',
  tibcoEMS: 'com.instana.forge.infrastructure.messaging.tibcoems.TibcoEMS',
  tomcatApplicationContainer: 'com.instana.forge.infrastructure.application.tomcat.TomcatApplicationContainer',
  unmonitoredHost: 'com.instana.forge.infrastructure.UnmonitoredHost',
  varnish: 'com.instana.forge.infrastructure.cache.varnish.Varnish',
  vault: 'com.instana.forge.infrastructure.database.vault.Vault',
  vsphereDatacenter: 'com.instana.forge.infrastructure.paas.vsphere.derivedentity.datacenter.VsphereDatacenter',
  vsphereHost: 'com.instana.forge.infrastructure.paas.vsphere.derivedentity.host.VsphereHost',
  vsphereVM: 'com.instana.forge.infrastructure.paas.vsphere.derivedentity.vm.VsphereVM',
  webLogicApplicationContainer: 'com.instana.forge.infrastructure.application.weblogic.WebLogicApplicationContainer',
  webSphereApplicationContainer: 'com.instana.forge.infrastructure.application.websphere.WebSphereApplicationContainer',
  webSphereLibertyApplicationContainer:
    'com.instana.forge.infrastructure.application.websphere.WebSphereLibertyApplicationContainer',
  zooKeeper: 'com.instana.forge.infrastructure.database.zookeeper.ZooKeeper'
};

export function translateFullyQualifiedPluginToShortPluginName(fullyQualifiedPlugin) {
  const keys = Object.keys(fullyQualifiedPlugins);
  for (let i = 0; i < keys.length; i++) {
    const key = keys[i];
    if (fullyQualifiedPlugins[key] === fullyQualifiedPlugin) {
      return key;
    }
  }
  return null;
}
