import { assign, omit } from 'lodash';

/* eslint-disable max-len */
export const ID_OF_UNMONITORED_ZONE = '5nXT64z0gY0pShCaT5VQ7wGu-0E';
export const ID_OF_PROCESSING_STATISTICS = '_9Ct9EsdanGCFtGIG_j7wNKr5hE';

export const nonServicePlugins = {
  activemq: 'activeMQ',
  availabilityZone: 'availabilityZone',
  awsDynamoDb: 'awsDynamoDb',
  awsEc: 'awsEc',
  awsElb: 'awsElb',
  awsKinesis: 'awsKinesis',
  awsLambda: 'awsLambda',
  awsRds: 'awsRds',
  awsSqs: 'awsSqs',
  awsS3: 'awsS3',
  azure: 'azure',
  azureAppService: 'azureAppService',
  azureCosmosDb: 'azureCosmosDb',
  azureRedisCache: 'azureRedisCache',
  cassandra: 'cassandraNode',
  cassandraCluster: 'cassandraCluster',
  ceph: 'ceph',
  clrRuntimePlatform: 'clrRuntimePlatform',
  clickHouseDatabase: 'clickHouseDatabase',
  cloudFoundry: 'cloudFoundry',
  consul: 'consul',
  consulCluster: 'consulCluster',
  couchbase: 'couchbaseNode',
  couchbaseCluster: 'couchbaseCluster',
  crystal: 'crystalRuntimePlatform',
  docker: 'docker',
  dropwizard: 'dropwizardApplicationContainer',
  ec2: 'ec2',
  elasticsearch: 'elasticsearchNode',
  elasticsearchCluster: 'elasticsearchCluster',
  etcd: 'etcd',
  finagle: 'finagleApplicationContainer',
  f5: 'f5',
  garden: 'garden',
  gce: 'gce',
  genericHardware: 'genericHardware',
  genericZone: 'genericZone',
  glassfish: 'glassfishApplicationContainer',
  golang: 'golangRuntimePlatform',
  hadoopYARN: 'hadoopYARN',
  hadoopYARNNode: 'hadoopYARNNode',
  haproxy: 'hAProxy',
  hazelcastCluster: 'hazelcastCluster',
  hazelcastNode: 'hazelcastNode',
  hbase: 'hBase',
  host: 'host',
  httpd: 'httpd',
  instanaAgent: 'instanaAgent',
  jbossas: 'jBossAsApplicationContainer',
  jbossdatagrid: 'jbossDataGrid',
  jetty: 'jettyApplicationContainer',
  jira: 'jiraApplication',
  jvm: 'jvmRuntimePlatform',
  kafka: 'kafka',
  kafkaCluster: 'kafkaCluster',
  kubernetesCluster: 'kubernetesCluster',
  kubernetesPod: 'kubernetesPod',
  kubernetesNode: 'kubernetesNode',
  kubernetesReplicaSet: 'kubernetesReplicaSet',
  kubernetesDeployment: 'kubernetesDeployment',
  kubernetesNamespace: 'kubernetesNamespace',
  liferay: 'liferayApplicationContainer',
  mariaDbDatabase: 'mariaDbDatabase',
  memcached: 'memcached',
  mongodb: 'mongoDb',
  mongodbReplicaSet: 'mongoDbReplicaSet',
  msiis: 'msiis',
  mssql: 'msSqlDatabase',
  mule: 'mule',
  mysql: 'mySqlDatabase',
  netCoreRuntimePlatform: 'netCoreRuntimePlatform',
  neo4j: 'neo4j',
  nginx: 'nginx',
  nodejs: 'nodeJsRuntimePlatform',
  nomadScheduler: 'nomadScheduler',
  nova: 'nova',
  oracledb: 'oracleDB',
  openLDAP: 'openLDAP',
  openshiftDeploymentConfig: 'openshiftDeploymentConfig',
  phpfpm: 'phpFpmRuntimePlatform',
  php: 'phpRuntimePlatform',
  ping: 'ping',
  postgresql: 'postgreSqlDatabase',
  process: 'process',
  python: 'pythonRuntimePlatform',
  rabbitmq: 'rabbitMq',
  redis: 'redis',
  ruby: 'rubyRuntimePlatform',
  sapHana: 'sapHana',
  solr: 'solr',
  sparkApplication: 'sparkApplication',
  sparkStandalone: 'sparkStandalone',
  springboot: 'springbootApplicationContainer',
  statsd: 'statsd',
  tomcat: 'tomcatApplicationContainer',
  unmonitoredHost: 'unmonitoredHost',
  varnish: 'varnish',
  webLogic: 'webLogicApplicationContainer',
  webSphere: 'webSphereApplicationContainer',
  webSphereLiberty: 'webSphereLibertyApplicationContainer',
  zookeeper: 'zooKeeper'
};

export const oneZeroLogicalPlugins = {
  batchServiceInstance: 'batchServiceInstance',
  cassandraKeyspaceServiceInstance: 'cassandraKeyspaceServiceInstance',
  databaseServiceInstance: 'databaseServiceInstance',
  defaultLogicalConnection: 'defaultLogicalConnection',
  defaultLogicalService: 'defaultLogicalService',
  defaultServiceInstance: 'defaultServiceInstance',
  ejbLogicalConnection: 'ejbLogicalConnection',
  ejbLogicalService: 'ejbLogicalService',
  ejbServiceInstance: 'ejbServiceInstance',
  elasticSearchIndexServiceInstance: 'elasticSearchIndexServiceInstance',
  ftpServiceInstance: 'ftpServiceInstance',
  javaMailLogicalConnection: 'javaMailLogicalConnection',
  javaMailLogicalService: 'javaMailLogicalService',
  javaMailServiceInstance: 'javaMailServiceInstance',
  ldapLogicalConnection: 'ldapLogicalConnection',
  ldapLogicalService: 'ldapLogicalService',
  ldapServiceInstance: 'ldapServiceInstance',
  logicalBatch: 'logicalBatch',
  logicalBatchConnection: 'logicalBatchConnection',
  logicalCassandraConnection: 'logicalCassandraConnection',
  logicalCassandraKeyspace: 'logicalCassandraKeyspace',
  logicalDatabase: 'logicalDatabase',
  logicalDatabaseConnection: 'logicalDatabaseConnection',
  logicalEjbConnection: 'logicalEjbConnection',
  logicalElasticSearchConnection: 'logicalElasticSearchConnection',
  logicalElasticSearchIndex: 'logicalElasticSearchIndex',
  logicalFtpConnection: 'logicalFtpConnection',
  logicalFtpService: 'logicalFtpService',
  logicalHttpConnection: 'logicalHttpConnection',
  logicalJdbcConnection: 'logicalJdbcConnection',
  logicalKafkaConsumerConnection: 'logicalKafkaConsumerConnection',
  logicalKafkaPublisherConnection: 'logicalKafkaPublisherConnection',
  logicalMessageBroker: 'logicalMessageBroker',
  logicalMessageConsumer: 'logicalMessageConsumer',
  logicalMessageConsumerConnection: 'logicalMessageConsumerConnection',
  logicalMessagePublisherConnection: 'logicalMessagePublisherConnection',
  logicalMongoDbConnection: 'logicalMongoDbConnection',
  logicalMongoDbDatabase: 'logicalMongoDbDatabase',
  logicalMsmqConsumerConnection: 'logicalMsmqConsumerConnection',
  logicalMsmqPublisherConnection: 'logicalMsmqPublisherConnection',
  logicalNeo4jConnection: 'logicalNeo4jConnection',
  logicalNeo4jDatabase: 'logicalNeo4jDatabase',
  logicalPdoConnection: 'logicalPdoConnection',
  logicalRabbitMqConsumerConnection: 'logicalRabbitMqConsumerConnection',
  logicalRabbitMqPublisherConnection: 'logicalRabbitMqPublisherConnection',
  logicalRedisConnection: 'logicalRedisConnection',
  logicalRedisDatabase: 'logicalRedisDatabase',
  logicalRpcConnection: 'logicalRpcConnection',
  logicalRpcEndpoint: 'logicalRpcEndpoint',
  logicalWebApp: 'logicalWebApp',
  messageBrokerServiceInstance: 'messageBrokerServiceInstance',
  messageConsumerServiceInstance: 'messageConsumerServiceInstance',
  mongoDbDatabaseServiceInstance: 'mongoDbDatabaseServiceInstance',
  neo4jServiceInstance: 'neo4jServiceInstance',
  redisServiceInstance: 'redisServiceInstance',
  rpcEndpointServiceInstance: 'rpcEndpointServiceInstance',
  sdkLogicalConnection: 'sdkLogicalConnection',
  sdkLogicalService: 'sdkLogicalService',
  sdkServiceInstance: 'sdkServiceInstance',
  shellLogicalConnection: 'shellLogicalConnection',
  shellLogicalService: 'shellLogicalService',
  unknownService: 'unknownService',
  webAppServiceInstance: 'webAppServiceInstance'
};

export const oneZeroServicePlugins = {
  defaultLogicalService: 'defaultLogicalService',
  ejbLogicalService: 'ejbLogicalService',
  javaMailLogicalService: 'javaMailLogicalService',
  ldapLogicalService: 'ldapLogicalService',
  logicalBatch: 'logicalBatch',
  logicalCassandraKeyspace: 'logicalCassandraKeyspace',
  logicalDatabase: 'logicalDatabase',
  logicalElasticSearchIndex: 'logicalElasticSearchIndex',
  logicalFtpService: 'logicalFtpService',
  logicalMessageBroker: 'logicalMessageBroker',
  logicalMessageConsumer: 'logicalMessageConsumer',
  logicalMongoDbDatabase: 'logicalMongoDbDatabase',
  logicalNeo4jDatabase: 'logicalNeo4jDatabase',
  logicalRedisDatabase: 'logicalRedisDatabase',
  logicalWebApp: 'logicalWebApp',
  sdkLogicalService: 'sdkLogicalService',
  shellLogicalService: 'shellLogicalService',
  unknownService: 'unknownService'
};

export const applicationPlugins = {
  application: 'application',
  defaultEntity20: 'defaultEntity20',
  endpoint: 'endpoint',
  service: 'service'
};

const websiteMonitoring = {
  browserLogicalConnection: 'browserLogicalConnection',
  browserLogicalService: 'browserLogicalService',
  pageResourceLogicalConnection: 'pageResourceLogicalConnection',
  pageResourceLogicalService: 'pageResourceLogicalService',
  pageResourceServiceInstance: 'pageResourceServiceInstance'
};

export const plugins10 = assign({}, oneZeroLogicalPlugins, nonServicePlugins, websiteMonitoring);
export const plugins20 = assign({}, applicationPlugins, nonServicePlugins, websiteMonitoring);
export const pluginsDeprecatedIn20 = omit(plugins10, Object.keys(plugins20), Object.keys(oneZeroServicePlugins));
export const plugins = assign({}, plugins10, plugins20);

export const defaultAndUnknownPluginNames = [
  'unknownService',
  'defaultEntity20',
  'defaultLogicalConnection',
  'defaultLogicalService',
  'defaultServiceInstance'
];

export const fullyQualifiedPlugins = {
  activeMQ: 'com.instana.forge.infrastructure.messaging.activemq.ActiveMQ',
  application: 'com.instana.forge.application.Application',
  availabilityZone: 'com.instana.forge.hardware.AvailabilityZone',
  awsDynamoDb: 'com.instana.forge.hardware.virtual.aws.dynamodb.AwsDynamoDb',
  awsEc: 'com.instana.forge.hardware.virtual.aws.ec.AwsEc',
  awsElb: 'com.instana.forge.hardware.virtual.aws.elb.AwsElb',
  awsKinesis: 'com.instana.forge.hardware.virtual.aws.kinesis.AwsKinesis',
  awsLambda: 'com.instana.forge.hardware.virtual.aws.lambda.AwsLambda',
  awsRds: 'com.instana.forge.hardware.virtual.aws.rds.AwsRds',
  awsSqs: 'com.instana.forge.hardware.virtual.aws.sqs.AwsSqs',
  awsS3: 'com.instana.forge.hardware.virtual.aws.sqs.AwsS3',
  azure: 'com.instana.forge.hardware.virtual.azure.Azure',
  azureAppService: 'com.instana.forge.hardware.virtual.azure.appservice.AzureAppService',
  azureCosmosDb: 'com.instana.forge.hardware.virtual.azure.cosmosdb.AzureCosmosDb',
  azureRedisCache: 'com.instana.forge.hardware.virtual.azure.rediscache.AzureRedisCache',
  batchServiceInstance: 'com.instana.forge.connection.batch.BatchServiceInstance',
  browserLogicalConnection: 'com.instana.forge.connection.eum.BrowserLogicalConnection',
  browserLogicalService: 'com.instana.forge.connection.eum.BrowserLogicalService',
  cassandraCluster: 'com.instana.forge.infrastructure.database.cassandra.CassandraCluster',
  cassandraKeyspaceServiceInstance: 'com.instana.forge.connection.database.cassandra.CassandraKeyspaceServiceInstance',
  cassandraNode: 'com.instana.forge.infrastructure.database.cassandra.CassandraNode',
  ceph: 'com.instana.forge.infrastructure.database.ceph.Ceph',
  clrRuntimePlatform: 'com.instana.forge.infrastructure.runtime.clr.ClrRuntimePlatform',
  clickHouseDatabase: 'com.instana.forge.infrastructure.database.clickhouse.ClickHouseDatabase',
  cloudFoundry: 'com.instana.forge.infrastructure.paas.cloudfoundry.CloudFoundry',
  consul: 'com.instana.forge.infrastructure.discovery.consul.Consul',
  consulCluster: 'com.instana.forge.infrastructure.discovery.consul.ConsulCluster',
  couchbaseCluster: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseCluster',
  couchbaseNode: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseNode',
  crystalRuntimePlatform: 'com.instana.forge.infrastructure.runtime.crystal.CrystalRuntimePlatform',
  databaseServiceInstance: 'com.instana.forge.connection.database.DatabaseServiceInstance',
  defaultEntity20: 'defaultEntity20',
  defaultLogicalConnection: 'com.instana.forge.connection.fallback.DefaultLogicalConnection',
  defaultLogicalService: 'com.instana.forge.connection.fallback.DefaultLogicalService',
  defaultServiceInstance: 'com.instana.forge.connection.fallback.DefaultServiceInstance',
  docker: 'com.instana.forge.infrastructure.virtualization.docker.Docker',
  dropwizardApplicationContainer:
    'com.instana.forge.infrastructure.application.dropwizard.DropwizardApplicationContainer',
  ec2: 'com.instana.forge.hardware.virtual.ec2.Ec2',
  ejbLogicalConnection: 'com.instana.forge.connection.ejb.EjbLogicalConnection',
  ejbLogicalService: 'com.instana.forge.connection.ejb.EjbLogicalService',
  ejbServiceInstance: 'com.instana.forge.connection.ejb.EjbServiceInstance',
  elasticsearchCluster: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchCluster',
  elasticSearchIndexServiceInstance:
    'com.instana.forge.connection.database.elasticsearch.ElasticSearchIndexServiceInstance',
  elasticsearchNode: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchNode',
  endpoint: 'com.instana.forge.application.Endpoint',
  etcd: 'com.instana.forge.infrastructure.cache.etcd.Etcd',
  finagleApplicationContainer: 'com.instana.forge.infrastructure.application.finagle.FinagleApplicationContainer',
  f5: 'com.instana.forge.infrastructure.loadbalancer.F5',
  ftpServiceInstance: 'com.instana.forge.connection.ftp.FtpServiceInstance',
  garden: 'com.instana.forge.infrastructure.virtualization.garden.Garden',
  gce: 'com.instana.forge.hardware.virtual.gce.Gce',
  genericHardware: 'com.instana.forge.hardware.GenericHardware',
  genericZone: 'com.instana.forge.hardware.GenericZone',
  glassfishApplicationContainer: 'com.instana.forge.infrastructure.application.glassfish.GlassfishApplicationContainer',
  golangRuntimePlatform: 'com.instana.forge.infrastructure.runtime.golang.GolangRuntimePlatform',
  hadoopYARN: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarn.HadoopYARN',
  hadoopYARNNode: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarnnode.HadoopYARNNode',
  hAProxy: 'com.instana.forge.infrastructure.loadbalancer.haproxy.HAProxy',
  hazelcastCluster: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastCluster',
  hazelcastNode: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastNode',
  hBase: 'com.instana.forge.infrastructure.database.hbase.HBase',
  host: 'com.instana.forge.infrastructure.os.host.Host',
  httpd: 'com.instana.forge.infrastructure.webserver.httpd.Httpd',
  instanaAgent: 'com.instana.forge.infrastructure.application.instana.agent.InstanaAgent',
  javaMailLogicalConnection: 'com.instana.forge.connection.mail.javaMailLogicalConnection',
  javaMailLogicalService: 'com.instana.forge.connection.mail.JavaMailLogicalService',
  javaMailServiceInstance: 'com.instana.forge.connection.mail.javaMailServiceInstance',
  jBossAsApplicationContainer: 'com.instana.forge.infrastructure.application.jbossas.JBossAsApplicationContainer',
  jbossDataGrid: 'com.instana.forge.infrastructure.cache.jbossdatagrid.JbossDataGrid',
  jettyApplicationContainer: 'com.instana.forge.infrastructure.application.jetty.JettyApplicationContainer',
  jiraApplication: 'com.instana.forge.infrastructure.application.jira.JiraApplication',
  jvmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.jvm.JvmRuntimePlatform',
  kafka: 'com.instana.forge.infrastructure.messaging.kafka.Kafka',
  kafkaCluster: 'com.instana.forge.infrastructure.messaging.kafka.KafkaCluster',
  kubernetesCluster: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesCluster',
  kubernetesPod: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesPod',
  kubernetesDeployment: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesDeployment',
  kubernetesNamespace: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesNamespace',
  kubernetesNode: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesNode',
  kubernetesReplicaSet:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.replicaset.KubernetesReplicaSet',
  ldapLogicalConnection: 'com.instana.forge.connection.ldap.LdapLogicalConnection',
  ldapLogicalService: 'com.instana.forge.connection.ldap.LdapLogicalService',
  ldapServiceInstance: 'com.instana.forge.connection.ldap.LdapServiceInstance',
  liferayApplicationContainer: 'com.instana.forge.infrastructure.application.liferay.LiferayApplicationContainer',
  logicalBatch: 'com.instana.forge.connection.batch.LogicalBatch',
  logicalBatchConnection: 'com.instana.forge.connection.batch.LogicalBatchConnection',
  logicalCassandraConnection: 'com.instana.forge.connection.database.cassandra.LogicalCassandraConnection',
  logicalCassandraKeyspace: 'com.instana.forge.connection.database.cassandra.LogicalCassandraKeyspace',
  logicalDatabase: 'com.instana.forge.connection.database.LogicalDatabase',
  logicalDatabaseConnection: 'com.instana.forge.connection.database.LogicalDatabaseConnection',
  logicalEjbConnection: 'com.instana.forge.connection.logicalEjbConnection',
  logicalElasticSearchConnection: 'com.instana.forge.connection.database.elasticsearch.LogicalElasticSearchConnection',
  logicalElasticSearchIndex: 'com.instana.forge.connection.database.elasticsearch.LogicalElasticSearchIndex',
  logicalFtpConnection: 'com.instana.forge.connection.ftp.LogicalFtpConnection',
  logicalFtpService: 'com.instana.forge.connection.ftp.LogicalFtpService',
  logicalHttpConnection: 'com.instana.forge.connection.http.logical.LogicalHttpConnection',
  logicalJdbcConnection: 'com.instana.forge.connection.database.jdbc.LogicalJdbcConnection',
  logicalKafkaConsumerConnection: 'com.instana.forge.connection.messaging.kafka.LogicalKafkaConsumerConnection',
  logicalKafkaPublisherConnection: 'com.instana.forge.connection.messaging.kafka.LogicalKafkaPublisherConnection',
  logicalMessageBroker: 'com.instana.forge.connection.messaging.LogicalMessageBroker',
  logicalMessageConsumer: 'com.instana.forge.connection.messaging.LogicalMessageConsumer',
  logicalMessageConsumerConnection: 'com.instana.forge.connection.messaging.LogicalMessageConsumerConnection',
  logicalMessagePublisherConnection: 'com.instana.forge.connection.messaging.LogicalMessagePublisherConnection',
  logicalMongoDbConnection: 'com.instana.forge.connection.database.mongodb.LogicalMongoDbConnection',
  logicalMongoDbDatabase: 'com.instana.forge.connection.database.mongodb.LogicalMongoDbDatabase',
  logicalMsmqConsumerConnection: 'com.instana.forge.connection.messaging.msmq.LogicalMsmqConsumerConnection',
  logicalMsmqPublisherConnection: 'com.instana.forge.connection.messaging.msmq.LogicalMsmqPublisherConnection',
  logicalNeo4jConnection: 'com.instana.forge.connection.database.neo4j.LogicalNeo4jConnection',
  logicalNeo4jDatabase: 'com.instana.forge.connection.database.neo4j.LogicalNeo4jDatabase',
  logicalPdoConnection: 'com.instana.forge.connection.database.pdo.LogicalPdoConnection',
  logicalRabbitMqConsumerConnection:
    'com.instana.forge.connection.messaging.rabbitmq.LogicalRabbitMqConsumerConnection',
  logicalRabbitMqPublisherConnection:
    'com.instana.forge.connection.messaging.rabbitmq.LogicalRabbitMqPublisherConnection',
  logicalRedisConnection: 'com.instana.forge.connection.database.redis.LogicalRedisConnection',
  logicalRedisDatabase: 'com.instana.forge.connection.database.redis.LogicalRedisDatabase',
  logicalRpcConnection: 'com.instana.forge.connection.rpc.logical.LogicalRpcConnection',
  logicalRpcEndpoint: 'com.instana.forge.connection.rpc.logical.LogicalRpcEndpoint',
  logicalWebApp: 'com.instana.forge.connection.http.logical.LogicalWebApp',
  mariaDbDatabase: 'com.instana.forge.infrastructure.database.mariadb.MariaDbDatabase',
  memcached: 'com.instana.forge.infrastructure.cache.memcached.Memcached',
  messageBrokerServiceInstance: 'com.instana.forge.connection.messaging.MessageBrokerServiceInstance',
  messageConsumerServiceInstance: 'com.instana.forge.connection.messaging.MessageConsumerServiceInstance',
  mongoDb: 'com.instana.forge.infrastructure.database.mongodb.MongoDb',
  mongoDbDatabaseServiceInstance: 'com.instana.forge.connection.database.mongodb.MongoDbDatabaseServiceInstance',
  mongoDbReplicaSet: 'com.instana.forge.connection.database.mongodb.MongoDbReplicaSet',
  msiis: 'com.instana.forge.infrastructure.webserver.msiis.Msiis',
  msSqlDatabase: 'com.instana.forge.infrastructure.database.mssql.MsSqlDatabase',
  mule: 'com.instana.forge.infrastructure.messaging.mule.Mule',
  mySqlDatabase: 'com.instana.forge.infrastructure.database.mysql.MySqlDatabase',
  neo4j: 'com.instana.forge.infrastructure.database.neo4j.Neo4j',
  neo4jServiceInstance: 'com.instana.forge.connection.database.neo4j.Neo4jServiceInstance',
  netCoreRuntimePlatform: 'com.instana.forge.infrastructure.runtime.netcore.NetCoreRuntimePlatform',
  nomadScheduler: 'com.instana.forge.infrastructure.scheduler.nomad.NomadScheduler',
  nginx: 'com.instana.forge.infrastructure.webserver.nginx.Nginx',
  nodeJsRuntimePlatform: 'com.instana.forge.infrastructure.runtime.nodejs.NodeJsRuntimePlatform',
  nova: 'com.instana.forge.hardware.virtual.openstack.Nova',
  oracleDB: 'com.instana.forge.infrastructure.database.oracledb.OracleDB',
  openLDAP: 'com.instana.forge.infrastructure.directory.openldap.OpenLDAP',
  openshiftDeploymentConfig: 'com.instana.forge.infrastructure.paas.kubernetes.OpenshiftDeploymentConfig',
  pageResourceLogicalConnection: 'com.instana.forge.connection.eum.PageResourceLogicalConnection',
  pageResourceLogicalService: 'com.instana.forge.connection.eum.PageResourceLogicalService',
  pageResourceServiceInstance: 'com.instana.forge.connection.eum.PageResourceServiceInstance',
  phpFpmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.phpfpm.PhpFpmRuntimePlatform',
  phpRuntimePlatform: 'com.instana.forge.infrastructure.runtime.php.PhpRuntimePlatform',
  ping: 'com.instana.forge.infrastructure.synthetic.ping.Ping',
  postgreSqlDatabase: 'com.instana.forge.infrastructure.database.postgresql.PostgreSqlDatabase',
  process: 'com.instana.forge.infrastructure.os.process.Process',
  pythonRuntimePlatform: 'com.instana.forge.infrastructure.runtime.python.PythonRuntimePlatform',
  rabbitMq: 'com.instana.forge.infrastructure.messaging.rabbitmq.RabbitMq',
  redis: 'com.instana.forge.infrastructure.cache.redis.Redis',
  redisServiceInstance: 'com.instana.forge.connection.database.redis.RedisServiceInstance',
  rpcEndpointServiceInstance: 'com.instana.forge.connection.rpc.logical.RpcEndpointServiceInstance',
  rubyRuntimePlatform: 'com.instana.forge.infrastructure.runtime.ruby.RubyRuntimePlatform',
  sapHana: 'com.instana.forge.infrastructure.database.saphana.SapHana',
  sdkLogicalConnection: 'com.instana.forge.connection.sdk.SdkLogicalConnection',
  sdkLogicalService: 'com.instana.forge.connection.sdk.SdkLogicalService',
  sdkServiceInstance: 'com.instana.forge.connection.sdk.SdkServiceInstance',
  service: 'com.instana.forge.application.Service',
  shellLogicalService: 'com.instana.forge.connection.shell.ShellLogicalService',
  shellLogicalConnection: 'com.instana.forge.connection.shell.ShellLogicalConnection',
  solr: 'com.instana.forge.infrastructure.database.solr.Solr',
  springbootApplicationContainer:
    'com.instana.forge.infrastructure.application.springboot.SpringbootApplicationContainer',
  sparkApplication: 'com.instana.forge.infrastructure.dataanalytics.sparkapplication.SparkApplication',
  sparkStandalone: 'com.instana.forge.infrastructure.dataanalytics.sparkstandalone.SparkStandalone',
  statsd: 'com.instana.forge.common.Statsd',
  tomcatApplicationContainer: 'com.instana.forge.infrastructure.application.tomcat.TomcatApplicationContainer',
  unknownService: 'com.instana.forge.connection.UnknownService',
  unmonitoredHost: 'com.instana.forge.infrastructure.UnmonitoredHost',
  varnish: 'com.instana.forge.infrastructure.cache.varnish.Varnish',
  webAppServiceInstance: 'com.instana.forge.connection.http.logical.WebAppServiceInstance',
  webLogicApplicationContainer: 'com.instana.forge.infrastructure.application.weblogic.WebLogicApplicationContainer',
  webSphereApplicationContainer: 'com.instana.forge.infrastructure.application.websphere.WebSphereApplicationContainer',
  webSphereLibertyApplicationContainer:
    'com.instana.forge.infrastructure.application.websphere.WebSphereLibertyApplicationContainer',
  zooKeeper: 'com.instana.forge.infrastructure.database.zookeeper.ZooKeeper'
};
