/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */

export const ID_OF_UNMONITORED_ZONE = '5nXT64z0gY0pShCaT5VQ7wGu-0E';
export const ID_OF_PROCESSING_STATISTICS = '_9Ct9EsdanGCFtGIG_j7wNKr5hE';
// host: "region" - pluginId: "com.instana.forge.selfmonitoring.RegionEntity" - steadyId: "region"
export const ID_OF_REGION = '7c238Z6UhpGTsuCTCehWnBoiaxs';
export const DEFAULT_DISTANCE_BETWEEN_DATA_POINTS_OTEL = 120_000;

export const oTelPlugins = {
  openTelemetry: 'openTelemetry',
  oTelDatabase: 'oTelDatabase',
  oTelLLM: 'oTelLLM',
  oTelVLLM: 'oTelVLLM',
  oTelDcgm: 'oTelDcgm',
  otelHost: 'otelHost',
  oTelJvm: 'oTelJvm',
  otelProcess: 'otelProcess',
  oTelK8sPod: 'oTelK8sPod',
  oTelK8sCluster: 'oTelK8sCluster',
  oTelK8sNode: 'oTelK8sNode'
};

export const nonServicePlugins = {
  aceIntegrationNode: 'aceIntegrationNode',
  aceIntegrationServer: 'aceIntegrationServer',
  aceMessageFlow: 'aceMessageFlow',
  activeDirectory: 'activeDirectory',
  activeMQ: 'activeMQ',
  activeMQArtemis: 'activeMQArtemis',
  aerospike: 'aerospike',
  aliCloudOss: 'aliCloudOss',
  aliCloudOssBucket: 'aliCloudOssBucket',
  aliCloudMysql: 'aliCloudMysql',
  aliCloudRocketMq: 'aliCloudRocketMq',
  aliCloudRocketMqGroup: 'aliCloudRocketMqGroup',
  aliCloudRocketMqGroupPerTopic: 'aliCloudRocketMqGroupPerTopic',
  aliCloudRocketMqTopic: 'aliCloudRocketMqTopic',
  apmProxy: 'apmProxy',
  availabilityZone: 'availabilityZone',
  awsAppSync: 'awsAppSync',
  awsAutoScaling: 'awsAutoScaling',
  awsBeanstalk: 'awsBeanstalk',
  awsCloudFront: 'awsCloudFront',
  awsDynamoDb: 'awsDynamoDb',
  awsEc: 'awsEc',
  awsEcs: 'awsEcs',
  awsEcsCluster: 'awsEcsCluster',
  awsEcsContainer: 'awsEcsContainer',
  awsEcsService: 'awsEcsService',
  awsEcsTask: 'awsEcsTask',
  awsEs: 'awsEs',
  awsElb: 'awsElb',
  awsEmr: 'awsEmr',
  awsIotCore: 'awsIotCore',
  awsKinesis: 'awsKinesis',
  awsLambdaFunction: 'awsLambdaFunction',
  awsLambdaVersion: 'awsLambdaVersion',
  // legacy AWS Lambda plug-in
  awsLambda: 'awsLambda',
  awsMq: 'awsMq',
  awsMskCluster: 'awsMskCluster',
  awsMskBroker: 'awsMskBroker',
  awsRedshiftCluster: 'awsRedshiftCluster',
  awsRedshiftNode: 'awsRedshiftNode',
  awsDocumentDbCluster: 'awsDocumentDbCluster',
  awsDocumentDbInstance: 'awsDocumentDbInstance',
  awsDocumentDbElasticCluster: 'awsDocumentDbElasticCluster',
  awsRds: 'awsRds',
  awsSqs: 'awsSqs',
  awsSns: 'awsSns',
  awsS3: 'awsS3',
  awsTimestream: 'awsTimestream',
  awsEbs: 'awsEbs',
  awsApiGateway: 'awsApiGateway',
  azure: 'azure',
  azureApiManagement: 'azureApiManagement',
  azureAppService: 'azureAppService',
  azureCosmosDb: 'azureCosmosDb',
  azureDataFactory: 'azureDataFactory',
  azureMySql: 'azureMySql',
  azureRedisCache: 'azureRedisCache',
  azureSqlDb: 'azureSqlDb',
  azureSqlElasticPool: 'azureSqlElasticPool',
  azureSqlServer: 'azureSqlServer',
  azureStorage: 'azureStorage',
  azureQueue: 'azureQueue',
  azureBlob: 'azureBlob',
  azureFunctionApp: 'azureFunctionApp',
  azureFunction: 'azureFunction',
  azureDatabricks: 'azureDatabricks',
  azureServiceBus: 'azureServiceBus',
  azureServiceBusQueues: 'azureServiceBusQueues',
  azureServiceBusTopics: 'azureServiceBusTopics',
  azureMachineLearning: 'azureMachineLearning',
  azureKeyVault: 'azureKeyVault',
  microsoftPurview: 'microsoftPurview',
  azureManagedHSM: 'azureManagedHSM',
  azurePostgreSQL: 'azurePostgreSQL',
  azureLoadBalancer: 'azureLoadBalancer',
  azureSignalR: 'azureSignalR',
  azureApplicationGateway: 'azureApplicationGateway',
  beeInstanaNode: 'beeInstanaNode',
  bizTalk: 'bizTalk',
  camunda: 'camunda',
  baw: 'baw',
  jbpm: 'jbpm',
  cassandraNode: 'cassandraNode',
  cassandraCluster: 'cassandraCluster',
  ceph: 'ceph',
  clrRuntimePlatform: 'clrRuntimePlatform',
  clickHouseDatabase: 'clickHouseDatabase',
  clickHouseCluster: 'clickHouseCluster',
  cloudFoundry: 'cloudFoundry',
  cockroachDBCluster: 'cockroachDBCluster',
  cockroachDBNode: 'cockroachDBNode',
  containerd: 'containerd',
  crio: 'crio',
  consul: 'consul',
  consulCluster: 'consulCluster',
  couchbaseNode: 'couchbaseNode',
  couchbaseCluster: 'couchbaseCluster',
  crowdStrikeFalcon: 'crowdStrikeFalcon',
  crystalRuntimePlatform: 'crystalRuntimePlatform',
  db2Database: 'db2Database',
  db2ZDatabase: 'db2ZDatabase',
  docker: 'docker',
  domino: 'domino',
  drbdReactor: 'drbdReactor',
  drbdResource: 'drbdResource',
  drbdDevice: 'drbdDevice',
  drbdConnection: 'drbdConnection',
  drbdPeerDevice: 'drbdPeerDevice',
  dropwizardApplicationContainer: 'dropwizardApplicationContainer',
  ec2: 'ec2',
  ec2Tags: 'ec2Tags',
  ec2TagsCollector: 'ec2TagsCollector',
  elasticsearchNode: 'elasticsearchNode',
  elasticsearchCluster: 'elasticsearchCluster',
  entityStatistics: 'entityStatistics',
  entityStatisticsMember: 'entityStatisticsMember',
  envoy: 'envoy',
  etcd: 'etcd',
  fileMonitoring: 'fileMonitoring',
  fileMonitoringCondition: 'fileMonitoringCondition',
  finagleApplicationContainer: 'finagleApplicationContainer',
  f5: 'f5',
  garden: 'garden',
  gce: 'gce',
  genericHardware: 'genericHardware',
  genericZone: 'genericZone',
  glassfishApplicationContainer: 'glassfishApplicationContainer',
  golangRuntimePlatform: 'golangRuntimePlatform',
  googleCloudDatastore: 'googleCloudDatastore',
  googleCloudPubSub: 'googleCloudPubSub',
  googleCloudPubSubSubscription: 'googleCloudPubSubSubscription',
  googleCloudPubSubTopic: 'googleCloudPubSubTopic',
  googleCloudRunServiceRevision: 'googleCloudRunServiceRevision',
  googleCloudRunServiceRevisionInstance: 'googleCloudRunServiceRevisionInstance',
  googleCloudSQL: 'googleCloudSQL',
  googleCloudStorage: 'googleCloudStorage',
  hadoopYARN: 'hadoopYARN',
  hadoopYARNNode: 'hadoopYARNNode',
  hAProxy: 'hAProxy',
  haskellRuntimePlatform: 'haskellRuntimePlatform',
  hazelcastCluster: 'hazelcastCluster',
  hazelcastNode: 'hazelcastNode',
  hBase: 'hBase',
  host: 'host',
  hostWinService: 'hostWinService',
  httpd: 'httpd',
  ibmApiConnect: 'ibmApiConnect',
  ibmApiConnectCatalog: 'ibmApiConnectCatalog',
  ibmApiConnectSpace: 'ibmApiConnectSpace',
  ibmCics: 'ibmCics',
  ibmCtg: 'ibmCtg',
  ibmCloudClinicalData: 'ibmCloudClinicalData',
  ibmCloudCloudant: 'ibmCloudCloudant',
  ibmCloudContainerRegistry: 'ibmCloudContainerRegistry',
  ibmCloudElasticsearch: 'ibmCloudElasticsearch',
  ibmCloudEtcd: 'ibmCloudEtcd',
  ibmCloudEventStream: 'ibmCloudEventStream',
  ibmCloudFoundry: 'ibmCloudFoundry',
  ibmCloudFunctions: 'ibmCloudFunctions',
  ibmCloudHPMongoDb: 'ibmCloudHPMongoDb',
  ibmCloudHPPostgreSql: 'ibmCloudHPPostgreSql',
  ibmCloudIsLoadBalancer: 'ibmCloudIsLoadBalancer',
  ibmCloudLoadBalancer: 'ibmCloudLoadBalancer',
  ibmCloudMongoDb: 'ibmCloudMongoDb',
  ibmCloudPostgreSql: 'ibmCloudPostgreSql',
  ibmCloudRabbitMq: 'ibmCloudRabbitMq',
  ibmCloudRedis: 'ibmCloudRedis',
  ibmCloudSchematics: 'ibmCloudSchematics',
  ibmCloudSqlQuery: 'ibmCloudSqlQuery',
  ibmCloudVpn4Vpc: 'ibmCloudVpn4Vpc',
  ibmCos: 'ibmCos',
  ibmDataPowerCluster: 'ibmDataPowerCluster',
  ibmDataPowerAppliance: 'ibmDataPowerAppliance',
  ibmDataPowerDomain: 'ibmDataPowerDomain',
  ibmDataPowerService: 'ibmDataPowerService',
  ibmDataPowerSqlDatasource: 'ibmDataPowerSqlDatasource',
  ibmDataPowerQueueManager: 'ibmDataPowerQueueManager',
  ibmDataPowerQueueManagerV9: 'ibmDataPowerQueueManagerV9',
  ibmDataPowerEthernetInterface: 'ibmDataPowerEthernetInterface',
  ibmIDb2: 'ibmIDb2',
  ibmiDiskInfo: 'ibmiDiskInfo',
  ibmIMessageQueueInfo: 'ibmIMessageQueueInfo',
  ibmiActiveJobsInfo: 'ibmiActiveJobsInfo',
  ibmIOs: 'ibmIOs',
  ibmIms: 'ibmIms',
  ibmiNetworkInfo: 'ibmiNetworkInfo',
  ibmInfosphereCdc: 'ibmInfosphereCdc',
  ibmInfosphereCdcSubscription: 'ibmInfosphereCdcSubscription',
  ibmMqCluster: 'ibmMqCluster',
  ibmMqQueueManager: 'ibmMqQueueManager',
  ibmMqChannel: 'ibmMqChannel',
  ibmMqttChannel: 'ibmMqttChannel',
  ibmMqListener: 'ibmMqListener',
  ibmMqQueue: 'ibmMqQueue',
  ibmMqQueueUsage: 'ibmMqQueueUsage',
  ibmMqTopic: 'ibmMqTopic',
  ibmMqSubscription: 'ibmMqSubscription',
  ibmMqMftCoordiQmgr: 'ibmMqMftCoordiQmgr',
  ibmMqMftZone: 'ibmMqMftZone',
  ibmMqMftAgent: 'ibmMqMftAgent',
  ibmMqMftTransfer: 'ibmMqMftTransfer',
  ibmMqMftMonitor: 'ibmMqMftMonitor',
  ibmOpenstack: 'ibmOpenstack',
  ibmOpenstackComputeInstance: 'ibmOpenstackComputeInstance',
  ibmOpenstackHypervisor: 'ibmOpenstackHypervisor',
  ibmOpenstackRegion: 'ibmOpenstackRegion',
  ibmVsi: 'ibmVsi',
  ibmZOsConnect: 'ibmZOsConnect',
  instanaAgent: 'instanaAgent',
  jBossAsApplicationContainer: 'jBossAsApplicationContainer',
  jbossDataGrid: 'jbossDataGrid',
  jenkins: 'jenkins',
  jettyApplicationContainer: 'jettyApplicationContainer',
  jiraApplication: 'jiraApplication',
  jvmRuntimePlatform: 'jvmRuntimePlatform',
  kafka: 'kafka',
  kafkaCluster: 'kafkaCluster',
  kafkaConnectCluster: 'kafkaConnectCluster',
  kafkaConnectTask: 'kafkaConnectTask',
  kafkaConnectConnector: 'kafkaConnectConnector',
  kafkaConnectWorker: 'kafkaConnectWorker',
  kongApigateway: 'kongApigateway',
  kubernetesCluster: 'kubernetesCluster',
  kubernetesCronJob: 'kubernetesCronJob',
  kubernetesJob: 'kubernetesJob',
  kubernetesDaemonSet: 'kubernetesDaemonSet',
  kubernetesDeployment: 'kubernetesDeployment',
  kubernetesEndpoints: 'kubernetesEndpoints',
  kubernetesNamespace: 'kubernetesNamespace',
  kubernetesNode: 'kubernetesNode',
  kubernetesPod: 'kubernetesPod',
  kubernetesReplicaSet: 'kubernetesReplicaSet',
  kubernetesReplicationController: 'kubernetesReplicationController',
  kubernetesService: 'kubernetesService',
  kubernetesStatefulSet: 'kubernetesStatefulSet',
  kubernetesPersistentVolume: 'kubernetesPersistentVolume',
  kubernetesPersistentVolumeClaim: 'kubernetesPersistentVolumeClaim',
  kubernetesHorizontalPodAutoscaler: 'kubernetesHorizontalPodAutoscaler',
  liferayApplicationContainer: 'liferayApplicationContainer',
  lxc: 'lxc',
  mariaDbDatabase: 'mariaDbDatabase',
  memcached: 'memcached',
  mongoDb: 'mongoDb',
  mongoDbCluster: 'mongoDbCluster',
  mongoDbReplicaSet: 'mongoDbReplicaSet',
  msiis: 'msiis',
  msSqlDatabase: 'msSqlDatabase',
  mule: 'mule',
  mySqlDatabase: 'mySqlDatabase',
  nats: 'nats',
  natsStreaming: 'natsStreaming',
  netCoreRuntimePlatform: 'netCoreRuntimePlatform',
  neo4j: 'neo4j',
  nginx: 'nginx',
  nodeJsRuntimePlatform: 'nodeJsRuntimePlatform',
  nomadScheduler: 'nomadScheduler',
  nova: 'nova',
  nutanixDatacenter: 'nutanixDatacenter',
  nutanixHost: 'nutanixHost',
  opc: 'opc',
  oracleDB: 'oracleDB',
  openLDAP: 'openLDAP',
  openshiftDeploymentConfig: 'openshiftDeploymentConfig',
  ...oTelPlugins,
  packet: 'packet',
  pCFApplication: 'pCFApplication',
  pCFOrganization: 'pCFOrganization',
  pCFSpace: 'pCFSpace',
  perfCounters: 'perfCounters',
  phmcConsole: 'phmcConsole',
  phmcSystem: 'phmcSystem',
  phmcLPAR: 'phmcLPAR',
  phmcSharedProcessorPool: 'phmcSharedProcessorPool',
  phmcVIOS: 'phmcVIOS',
  phpFpmRuntimePlatform: 'phpFpmRuntimePlatform',
  phpRuntimePlatform: 'phpRuntimePlatform',
  ping: 'ping',
  pingDirectory: 'pingDirectory',
  postgreSqlDatabase: 'postgreSqlDatabase',
  podman: 'podman',
  powerVCRegion: 'powerVCRegion',
  powerVCHypervisor: 'powerVCHypervisor',
  powerVCComputeInstance: 'powerVCComputeInstance',
  process: 'process',
  processingStatistics: 'processingStatistics',
  processingStatisticsMember: 'processingStatisticsMember',
  prometheus: 'prometheus',
  pythonRuntimePlatform: 'pythonRuntimePlatform',
  rabbitMq: 'rabbitMq',
  rabbitMqCluster: 'rabbitMqCluster',
  redis: 'redis',
  redisCluster: 'redisCluster',
  redisEnterpriseNode: 'redisEnterpriseNode',
  redisEnterpriseCluster: 'redisEnterpriseCluster',
  redisEnterpriseDatabase: 'redisEnterpriseDatabase',
  redisEnterpriseShard: 'redisEnterpriseShard',
  rocketMqCluster: 'rocketMqCluster',
  rocketMqBroker: 'rocketMqBroker',
  rocketMqTopic: 'rocketMqTopic',
  rubyRuntimePlatform: 'rubyRuntimePlatform',
  sapHana: 'sapHana',
  snowflake: 'snowflake',
  solr: 'solr',
  solrCloudCluster: 'solrCloudCluster',
  snowflakeOrganization: 'snowflakeOrganization',
  sparkApplication: 'sparkApplication',
  sparkStandalone: 'sparkStandalone',
  springbootApplicationContainer: 'springbootApplicationContainer',
  statsd: 'statsd',
  sybase: 'sybase',
  syntheticPoP: 'syntheticPoP',
  tanzuFoundation: 'tanzuFoundation',
  tanzuFoundationMember: 'tanzuFoundationMember',
  tibcoASNode: 'tibcoASNode',
  tibcoASProxy: 'tibcoASProxy',
  tibcoASDataGrid: 'tibcoASDataGrid',
  tibcoBWAppNode: 'tibcoBWAppNode',
  tibcoBWAppInst: 'tibcoBWAppInst',
  tibcoBWProcess: 'tibcoBWProcess',
  tibcoEMS: 'tibcoEMS',
  tibcoEMSTopic: 'tibcoEMSTopic',
  tibcoEMSQueue: 'tibcoEMSQueue',
  tomcatApplicationContainer: 'tomcatApplicationContainer',
  traefik: 'traefik',
  tuxedoDomain: 'tuxedoDomain',
  tuxedoMachine: 'tuxedoMachine',
  tuxedoServer: 'tuxedoServer',
  tuxedoIpcQueue: 'tuxedoIpcQueue',
  tuxedoAppApplication: 'tuxedoAppApplication',
  tuxedoAppServiceBrokerProject: 'tuxedoAppServiceBrokerProject',
  tuxedoAppTuxedoService: 'tuxedoAppTuxedoService',
  unmonitoredHost: 'unmonitoredHost',
  varnish: 'varnish',
  vault: 'vault',
  vsphereDatacenter: 'vsphereDatacenter',
  vsphereHost: 'vsphereHost',
  vsphereVM: 'vsphereVM',
  webLogicApplicationContainer: 'webLogicApplicationContainer',
  websiteHttpd: 'websiteHttpd',
  webSphereApplicationContainer: 'webSphereApplicationContainer',
  webSphereInfrastructureManager: 'webSphereInfrastructureManager',
  webSphereDeploymentManager: 'webSphereDeploymentManager',
  webSphereCluster: 'webSphereCluster',
  webSphereMember: 'webSphereMember',
  webSphereLibertyApplicationContainer: 'webSphereLibertyApplicationContainer',
  zhmcConsole: 'zhmcConsole',
  zhmcCpc: 'zhmcCpc',
  zooKeeper: 'zooKeeper',
  zOS: 'zOS',
  zDb2: 'zDb2',
  zCics: 'zCics',
  zIms: 'zIms',
  zCtg: 'zCtg',
  abapInstance: 'abapInstance',
  abapSystem: 'abapSystem',
  sapDbms: 'sapDbms',
  sapHost: 'sapHost',
  sapDbInstance: 'sapDbInstance',
  sapDbTenant: 'sapDbTenant',
  sapHanaPlatform: 'sapHanaPlatform',
  sapJavaInstance: 'sapJavaInstance',
  sapJavaSystem: 'sapJavaSystem',
  sapHanaSystem: 'sapHanaSystem',
  sapWebDispatcher: 'sapWebDispatcher',
  sapAbapInstanceSensor: 'sapAbapInstanceSensor',
  sapAbapSystemSensor: 'sapAbapSystemSensor',
  remoteHost: 'remoteHost',
  processGroup: 'processGroup'
};

export const applicationPlugins = {
  application: 'application',
  defaultEntity20: 'defaultEntity20',
  endpoint: 'endpoint',
  service: 'service'
};

export const plugins = { ...applicationPlugins, ...nonServicePlugins };

export const defaultAndUnknownPluginNames = [
  'unknownService',
  'defaultEntity20',
  'defaultLogicalConnection',
  'defaultLogicalService',
  'defaultServiceInstance',
  'entityStatistics',
  'entityStatisticsMember',
  'processingStatistics',
  'processingStatisticsMember'
];

export const hiddenPlugins = [
  'agentStatistics',
  'componentMetricsInstance',
  'entityStatisticsMember',
  'processingStatisticsMember',
  'steadyMetricExposureEntity'
];

export const customIssuesDisabledForPlugins = [...defaultAndUnknownPluginNames];

export const fullyQualifiedPlugins = {
  aceIntegrationNode: 'com.instana.forge.infrastructure.messaging.ace.AceIntegrationNode',
  aceIntegrationServer:
    'com.instana.forge.infrastructure.messaging.ace.derivedentity.aceIntegrationServer.AceIntegrationServer',
  aceMessageFlow: 'com.instana.forge.infrastructure.messaging.ace.derivedentity.aceMessageFlow.AceMessageFlow',
  activeDirectory: 'com.instana.forge.infrastructure.directory.activedirectory.ActiveDirectory',
  activeMQ: 'com.instana.forge.infrastructure.messaging.activemq.ActiveMQ',
  activeMQArtemis: 'com.instana.forge.infrastructure.messaging.activemqartemis.ActiveMQArtemis',
  aerospike: 'aerospike',
  aliCloudOss: 'com.instana.forge.hardware.virtual.alicloud.oss.AliCloudOss',
  aliCloudOssBucket: 'com.instana.forge.hardware.virtual.alicloud.oss.AliCloudOssBucket',
  aliCloudMysql: 'com.instana.forge.hardware.virtual.alicloud.rds.mysql.AliCloudMysql',
  aliCloudRocketMq: 'com.instana.forge.hardware.virtual.alicloud.rocketmq.AliCloudRocketMq',
  aliCloudRocketMqGroup:
    'com.instana.forge.hardware.virtual.alicloud.rocketmq.derivedentity.group.AliCloudRocketMqGroup',
  aliCloudRocketMqGroupPerTopic:
    'com.instana.forge.hardware.virtual.alicloud.rocketmq.derivedentity.groupPerTopic.AliCloudRocketMqGroupPerTopic',
  aliCloudRocketMqTopic:
    'com.instana.forge.hardware.virtual.alicloud.rocketmq.derivedentity.topic.AliCloudRocketMqTopic',
  rocketMqCluster: 'com.instana.forge.infrastructure.messaging.rocketmq.RocketMqCluster',
  rocketMqBroker: 'com.instana.forge.infrastructure.messaging.rocketmq.derivedentity.broker.RocketMqBroker',
  rocketMqTopic: 'com.instana.forge.infrastructure.messaging.rocketmq.derivedentity.topic.RocketMqTopic',
  apmProxy: 'apmProxy',
  application: 'com.instana.forge.application.Application',
  availabilityZone: 'com.instana.forge.hardware.AvailabilityZone',
  awsAppSync: 'com.instana.forge.hardware.virtual.aws.appsync.AwsAppSync',
  awsAutoScaling: 'com.instana.forge.hardware.virtual.aws.autoscaling.AwsAutoScaling',
  awsBeanstalk: 'com.instana.forge.hardware.virtual.aws.beanstalk.AwsBeanstalk',
  awsCloudFront: 'com.instana.forge.hardware.virtual.aws.cloudfront.AwsCloudFront',
  awsDynamoDb: 'com.instana.forge.hardware.virtual.aws.dynamodb.AwsDynamoDb',
  awsEc: 'com.instana.forge.hardware.virtual.aws.ec.AwsEc',
  awsEcs: 'com.instana.forge.hardware.virtual.aws.ecs.cluster.awsEcs',
  awsEcsCluster: 'com.instana.forge.hardware.virtual.aws.ecs.cluster.awsEcsCluster',
  awsEcsContainer: 'com.instana.forge.hardware.virtual.aws.ecs.container.AwsEcsContainer',
  awsEcsService: 'com.instana.forge.hardware.virtual.aws.ecs.service.awsEcsService',
  awsEcsTask: 'com.instana.forge.hardware.virtual.aws.ecs.task.AwsEcsTask',
  awsEs: 'com.instana.forge.hardware.virtual.aws.es.AwsEs',
  awsElb: 'com.instana.forge.hardware.virtual.aws.elb.AwsElb',
  awsEmr: 'com.instana.forge.hardware.virtual.aws.emr.AwsEmr',
  awsIotCore: 'com.instana.forge.hardware.virtual.aws.iotcore.AwsIotCore',
  awsKinesis: 'com.instana.forge.hardware.virtual.aws.kinesis.AwsKinesis',
  awsLambdaVersion: 'com.instana.forge.hardware.virtual.aws.lambda.version.AwsLambdaVersion',
  awsLambdaFunction: 'com.instana.forge.hardware.virtual.aws.lambda.function.AwsLambdaFunction',
  awsLambda: 'com.instana.forge.hardware.virtual.aws.lambda.AwsLambda',
  awsMq: 'com.instana.forge.hardware.virtual.aws.mq.AwsMq',
  awsMskCluster: 'com.instana.forge.hardware.virtual.aws.msk.derivedentity.cluster.AwsMskCluster',
  awsMskBroker: 'com.instana.forge.hardware.virtual.aws.msk.derivedentity.broker.AwsMskBroker',
  awsRedshiftCluster: 'com.instana.forge.hardware.virtual.aws.redshift.derivedentity.cluster.AwsRedshiftCluster',
  awsRedshiftNode: 'com.instana.forge.hardware.virtual.aws.redshift.derivedentity.node.AwsRedshiftNode',
  awsDocumentDbCluster: 'com.instana.forge.hardware.virtual.aws.documentdb.derivedentity.cluster.AwsDocumentDbCluster',
  awsDocumentDbElasticCluster:
    'com.instana.forge.hardware.virtual.aws.documentdb.derivedentity.elasticcluster.AwsDocumentDbElasticCluster',
  awsDocumentDbInstance:
    'com.instana.forge.hardware.virtual.aws.documentdb.derivedentity.instance.AwsDocumentDbInstance',
  awsRds: 'com.instana.forge.hardware.virtual.aws.rds.AwsRds',
  awsSqs: 'com.instana.forge.hardware.virtual.aws.sqs.AwsSqs',
  awsSns: 'com.instana.forge.hardware.virtual.aws.sns.AwsSns',
  awsS3: 'com.instana.forge.hardware.virtual.aws.s3.AwsS3',
  awsTimestream: 'com.instana.forge.hardware.virtual.aws.timestream.AwsTimestream',
  awsEbs: 'com.instana.forge.hardware.virtual.aws.ebs.AwsEbs',
  awsApiGateway: 'com.instana.forge.hardware.virtual.aws.apigateway.AwsApiGateway',
  azure: 'com.instana.forge.hardware.virtual.azure.Azure',
  azureApiManagement: 'com.instana.forge.hardware.virtual.azure.apimanagement.AzureApiManagement',
  azureAppService: 'com.instana.forge.hardware.virtual.azure.appservice.AzureAppService',
  azureCosmosDb: 'com.instana.forge.hardware.virtual.azure.cosmosdb.AzureCosmosDb',
  azureDataFactory: 'com.instana.forge.hardware.virtual.azure.datafactory.AzureDataFactory',
  azureMySql: 'com.instana.forge.hardware.virtual.azure.mysql.AzureMySql',
  azureRedisCache: 'com.instana.forge.hardware.virtual.azure.rediscache.AzureRedisCache',
  azureStorage: 'com.instana.forge.hardware.virtual.azure.storage.AzureStorage',
  azureQueue: 'com.instana.forge.hardware.virtual.azure.storage.queue.AzureQueue',
  azureBlob: 'com.instana.forge.hardware.virtual.azure.storage.blob.AzureBlob',
  azureFunctionApp: 'com.instana.forge.hardware.virtual.azure.functions.app.AzureFunctionApp',
  azureFunction: 'com.instana.forge.hardware.virtual.azure.functions.AzureFunction',
  azureSqlDb: 'com.instana.forge.hardware.virtual.azure.sqldb.AzureSqlDb',
  azureSqlElasticPool: 'com.instana.forge.hardware.virtual.azure.sqlelasticpool.AzureSqlElasticPool',
  azureSqlServer: 'com.instana.forge.hardware.virtual.azure.sqlserver.AzureSqlServer',
  azureDatabricks: 'com.instana.forge.hardware.virtual.azure.databricks.AzureDatabricks',
  azureServiceBus: 'com.instana.forge.hardware.virtual.azure.servicebus.AzureServiceBus',
  azureServiceBusQueues:
    'com.instana.forge.hardware.virtual.azure.servicebus.derivedentity.queues.AzureServiceBusQueues',
  azureServiceBusTopics:
    'com.instana.forge.hardware.virtual.azure.servicebus.derivedentity.topics.AzureServiceBusTopics',
  azureMachineLearning: 'com.instana.forge.hardware.virtual.azure.machinelearning.AzureMachineLearning',
  azureKeyVault: 'com.instana.forge.hardware.virtual.azure.keyvault.AzureKeyVault',
  azureManagedHSM: 'com.instana.forge.hardware.virtual.azure.managedhsm.AzureManagedHSM',
  microsoftPurview: 'com.instana.forge.hardware.virtual.azure.purview.MicrosoftPurview',
  azurePostgreSQL: 'com.instana.forge.hardware.virtual.azure.postgresql.AzurePostgreSQL',
  azureLoadBalancer: 'com.instana.forge.hardware.virtual.azure.loadbalancer.AzureLoadBalancer',
  azureSignalR: 'com.instana.forge.hardware.virtual.azure.signalr.AzureSignalR',
  azureApplicationGateway: 'com.instana.forge.hardware.virtual.azure.applicationgateway.AzureApplicationGateway',
  beeInstanaNode: 'com.instana.forge.infrastructure.database.beeinstana.BeeInstanaNode',
  bizTalk: 'com.instana.forge.infrastructure.messaging.biztalk.BizTalk',
  camunda: 'camunda',
  baw: 'baw',
  jbpm: 'jbpm',
  cassandraCluster: 'com.instana.forge.infrastructure.database.cassandra.CassandraCluster',
  cassandraNode: 'com.instana.forge.infrastructure.database.cassandra.CassandraNode',
  ceph: 'com.instana.forge.infrastructure.database.ceph.Ceph',
  clrRuntimePlatform: 'com.instana.forge.infrastructure.runtime.clr.ClrRuntimePlatform',
  clickHouseDatabase: 'com.instana.forge.infrastructure.database.clickhouse.ClickHouseDatabase',
  clickHouseCluster: 'com.instana.forge.infrastructure.database.clickhouse.ClickHouseCluster',
  cloudFoundry: 'com.instana.forge.infrastructure.paas.cloudfoundry.CloudFoundry',
  cockroachDBCluster: 'com.instana.forge.infrastructure.database.cockroachdb.CockroachDBCluster',
  cockroachDBNode: 'com.instana.forge.infrastructure.database.cockroachdb.CockroachDBNode',
  containerd: 'com.instana.forge.infrastructure.virtualization.containerd.Containerd',
  crio: 'com.instana.forge.infrastructure.virtualization.crio.Crio',
  consul: 'com.instana.forge.infrastructure.discovery.consul.Consul',
  consulCluster: 'com.instana.forge.infrastructure.discovery.consul.ConsulCluster',
  couchbaseCluster: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseCluster',
  couchbaseNode: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseNode',
  crowdStrikeFalcon: 'com.instana.forge.infrastructure.security.crowdstrikefalcon.CrowdStrikeFalcon',
  crystalRuntimePlatform: 'com.instana.forge.infrastructure.runtime.crystal.CrystalRuntimePlatform',
  db2Database: 'com.instana.forge.infrastructure.database.db2.Db2Database',
  db2ZDatabase: 'com.instana.forge.infrastructure.database.db2z.Db2ZDatabase',
  defaultEntity20: 'defaultEntity20',
  docker: 'com.instana.forge.infrastructure.virtualization.docker.Docker',
  domino: 'com.instana.forge.infrastructure.custom.domino.Domino',
  drbdReactor: 'com.instana.forge.infrastructure.storage.drbd.derivedentity.drbd.DrbdReactor',
  drbdResource: 'com.instana.forge.infrastructure.storage.drbd.derivedentity.resource.DrbdResource',
  drbdDevice: 'com.instana.forge.infrastructure.storage.drbd.derivedentity.device.DrbdDevice',
  drbdConnection: 'com.instana.forge.infrastructure.storage.drbd.derivedentity.connection.DrbdConnection',
  drbdPeerDevice: 'com.instana.forge.infrastructure.storage.drbd.derivedentity.peerdevice.DrbdPeerDevice',
  dropwizardApplicationContainer:
    'com.instana.forge.infrastructure.application.dropwizard.DropwizardApplicationContainer',
  ec2: 'com.instana.forge.hardware.virtual.ec2.Ec2',
  ec2Tags: 'com.instana.forge.hardware.virtual.ec2.Ec2Tags',
  ec2TagsCollector: 'com.instana.forge.hardware.virtual.ec2.Ec2TagsCollector',
  elasticsearchCluster: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchCluster',
  elasticsearchNode: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchNode',
  endpoint: 'com.instana.forge.application.Endpoint',
  envoy: 'com.instana.forge.infrastructure.webserver.envoy.Envoy',
  entityStatistics: 'com.instana.forge.selfmonitoring.filler.EntityStatistics',
  entityStatisticsMember: 'com.instana.forge.selfmonitoring.filler.EntityStatisticsMember',
  etcd: 'com.instana.forge.infrastructure.cache.etcd.Etcd',
  fileMonitoring: 'com.instana.forge.infrastructure.os.filemonitoring.FileMonitoring',
  fileMonitoringCondition: 'com.instana.forge.infrastructure.os.filemonitoring.FileMonitoringCondition',
  finagleApplicationContainer: 'com.instana.forge.infrastructure.application.finagle.FinagleApplicationContainer',
  f5: 'com.instana.forge.infrastructure.loadbalancer.F5',
  garden: 'com.instana.forge.infrastructure.virtualization.garden.Garden',
  gce: 'com.instana.forge.hardware.virtual.gce.Gce',
  googleCloudDatastore: 'com.instana.forge.hardware.virtual.gcp.datastore.GoogleCloudDatastore',
  googleCloudPubSub: 'com.instana.forge.hardware.virtual.gcp.pubsub.GoogleCloudPubSub',
  googleCloudPubSubSubscription:
    'com.instana.forge.hardware.virtual.gcp.pubsub.derivedentity.subscription.GoogleCloudPubSubSubscription',
  googleCloudPubSubTopic: 'com.instana.forge.hardware.virtual.gcp.pubsub.derivedentity.topic.GoogleCloudPubSubTopic',
  googleCloudRunServiceRevision: 'com.instana.forge.hardware.virtual.gcp.run.revision.GoogleCloudRunServiceRevision',
  googleCloudRunServiceRevisionInstance:
    'com.instana.forge.hardware.virtual.gcp.run.instance.GoogleCloudRunServiceRevisionInstance',
  googleCloudSQL: 'com.instana.forge.hardware.virtual.gcp.sql.GoogleCloudSQL',
  googleCloudStorage: 'com.instana.forge.hardware.virtual.gcp.storage.GoogleCloudStorage',
  genericHardware: 'com.instana.forge.hardware.GenericHardware',
  genericZone: 'com.instana.forge.hardware.GenericZone',
  glassfishApplicationContainer: 'com.instana.forge.infrastructure.application.glassfish.GlassfishApplicationContainer',
  golangRuntimePlatform: 'com.instana.forge.infrastructure.runtime.golang.GolangRuntimePlatform',
  hadoopYARN: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarn.HadoopYARN',
  hadoopYARNNode: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarnnode.HadoopYARNNode',
  hAProxy: 'com.instana.forge.infrastructure.loadbalancer.haproxy.HAProxy',
  haskellRuntimePlatform: 'com.instana.forge.infrastructure.runtime.haskell.HaskellRuntimePlatform',
  hazelcastCluster: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastCluster',
  hazelcastNode: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastNode',
  hBase: 'com.instana.forge.infrastructure.database.hbase.HBase',
  host: 'com.instana.forge.infrastructure.os.host.Host',
  hostWinService: 'com.instana.forge.infrastructure.os.host.derivedentity.service.HostWinService',
  httpd: 'com.instana.forge.infrastructure.webserver.httpd.Httpd',
  ibmApiConnect: 'com.instana.forge.infrastructure.apigateway.ibmapiconnect.IbmApiConnect',
  ibmApiConnectCatalog:
    'com.instana.forge.infrastructure.apigateway.ibmapiconnect.derivedentity.catalog.IbmApiConnectCatalog',
  ibmApiConnectSpace:
    'com.instana.forge.infrastructure.apigateway.ibmapiconnect.derivedentity.space.IbmApiConnectSpace',
  ibmCics: 'com.instana.forge.infrastructure.application.ibmzos.IbmCics',
  ibmCloudClinicalData: 'com.instana.forge.infrastructure.machine_learning.ibmcloud.clinicaldata.IbmCloudClinicalData',
  ibmCloudCloudant: 'com.instana.forge.infrastructure.database.ibmcloud.cloudant.IbmCloudCloudant',
  ibmCloudContainerRegistry:
    'com.instana.forge.infrastructure.virtualization.ibmcloud.registry.IbmCloudContainerRegistry',
  ibmCloudElasticsearch: 'com.instana.forge.infrastructure.database.ibmcloud.elasticsearch.IbmCloudElasticsearch',
  ibmCloudEtcd: 'com.instana.forge.infrastructure.database.ibmcloud.etcd.IbmCloudEtcd',
  ibmCloudEventStream: 'com.instana.forge.infrastructure.messaging.ibmcloud.eventstream.IbmCloudEventStream',
  ibmCloudFoundry: 'com.instana.forge.infrastructure.paas.ibmcloud.cloudfoundry.IbmCloudFoundry',
  ibmCloudFunctions: 'com.instana.forge.infrastructure.faas.ibmcloud.functions.IbmCloudFunctions',
  ibmCloudHPMongoDb: 'com.instana.forge.infrastructure.database.ibmcloud.hpmongodb.IbmCloudHPMongoDb',
  ibmCloudHPPostgreSql: 'com.instana.forge.infrastructure.database.ibmcloud.hppostgresql.IbmCloudHPPostgreSql',
  ibmCloudIsLoadBalancer: 'com.instana.forge.infrastructure.loadbalancer.ibmcloud.loadbalancer.IbmCloudIsLoadBalancer',
  ibmCloudLoadBalancer: 'com.instana.forge.infrastructure.loadbalancer.ibmcloud.loadbalancer.IbmCloudLoadBalancer',
  ibmCloudMongoDb: 'com.instana.forge.infrastructure.database.ibmcloud.mongodb.IbmCloudMongoDb',
  ibmCloudPostgreSql: 'com.instana.forge.infrastructure.database.ibmcloud.postgres.IbmCloudPostgreSql',
  ibmCloudRabbitMq: 'com.instana.forge.infrastructure.messaging.ibmcloud.rabbitmq.IbmCloudRabbitMq',
  ibmCloudRedis: 'com.instana.forge.infrastructure.cache.ibmcloud.redis.IbmCloudRedis',
  ibmCloudSchematics: 'com.instana.forge.infrastructure.scripting.ibmcloud.schematics.IbmCloudSchematics',
  ibmCloudSqlQuery: 'com.instana.forge.infrastructure.database.ibmcloud.sqlquery.IbmCloudSqlQuery',
  ibmCloudVpn4Vpc: 'com.instana.forge.infrastructure.vpn.ibmcloud.vpn4vpc.IbmCloudVpn4Vpc',
  ibmCos: 'com.instana.forge.hardware.virtual.ibm.cos.IbmCos',
  ibmDataPowerCluster: 'com.instana.forge.infrastructure.messaging.ibmdatapower.IbmDataPowerCluster',
  ibmDataPowerAppliance:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.appliance.IbmDataPowerAppliance',
  ibmDataPowerDomain: 'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.domain.IbmDataPowerDomain',
  ibmDataPowerService:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.service.IbmDataPowerService',
  ibmDataPowerSqlDatasource:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.sqldatasource.IbmDataPowerSqlDatasource',
  ibmDataPowerQueueManager:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.queueManager.IbmDataPowerQueueManager',
  ibmDataPowerQueueManagerV9:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.queuemanagerv9.IbmDataPowerQueueManagerV9',
  ibmDataPowerEthernetInterface:
    'com.instana.forge.infrastructure.messaging.ibmdatapower.derivedentity.ethernetinterface.IbmDataPowerEthernetInterface',
  ibmIDb2: 'com.instana.forge.infrastructure.database.ibmiseries.derivedentity.db2.IbmIDb2',
  ibmIOs: 'com.instana.forge.infrastructure.database.ibmiseries.derivedentity.os.IbmIOs',
  ibmIms: 'com.instana.forge.infrastructure.application.ibmzos.IbmIms',
  ibmCtg: 'com.instana.forge.infrastructure.application.ibmzos.IbmCtg',
  ibmiActiveJobsInfo:
    'com.instana.forge.infrastructure.database.ibmiseries.derivedentity.activeJobsInfo.IbmiActiveJobsInfo',
  ibmIMessageQueueInfo:
    'com.instana.forge.infrastructure.database.ibmiseries.derivedentity.messageQueue.IbmIMessageQueueInfo',
  ibmiDiskInfo: 'com.instana.forge.infrastructure.database.ibmiseries.derivedentity.diskInfo.IbmiDiskInfo',
  ibmInfosphereCdc: 'com.instana.forge.infrastructure.datareplication.ibminfosphere.IbmInfosphereCdc',
  ibmInfosphereCdcSubscription:
    'com.instana.forge.infrastructure.datareplication.ibminfosphere.derivedentity.subscription.IbmInfosphereCdcSubscription',
  ibmiNetworkInfo: 'com.instana.forge.infrastructure.database.ibmiseries.derivedentity.networkInfo.IbmiNetworkInfo',
  ibmMqCluster: 'com.instana.forge.infrastructure.messaging.ibmmq.IbmMqCluster',
  ibmMqQueueManager: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.queuemanager.IbmMqQueueManager',
  ibmMqChannel: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.channel.IbmMqChannel',
  ibmMqttChannel: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.mqttchannel.IbmMqttChannel',
  ibmMqListener: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.listener.IbmMqListener',
  ibmMqQueue: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.queue.IbmMqQueue',
  ibmMqQueueUsage: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.queueusage.IbmMqQueueUsage',
  ibmMqTopic: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.topic.IbmMqTopic',
  ibmMqSubscription: 'com.instana.forge.infrastructure.messaging.ibmmq.derivedentity.subscription.IbmMqSubscription',
  ibmMqMftZone: 'com.instana.forge.infrastructure.messaging.ibmmqmft.IbmMqMftZone',
  ibmMqMftCoordiQmgr: 'com.instana.forge.infrastructure.messaging.ibmmqmft.derivedentity.coordiqmgr.IbmMqMftCoordiQmgr',
  ibmMqMftAgent: 'com.instana.forge.infrastructure.messaging.ibmmqmft.derivedentity.agent.IbmMqMftAgent',
  ibmMqMftTransfer: 'com.instana.forge.infrastructure.messaging.ibmmqmft.derivedentity.transfer.IbmMqMftTransfer',
  ibmMqMftMonitor: 'com.instana.forge.infrastructure.messaging.ibmmqmft.derivedentity.monitor.IbmMqMftMonitor',
  ibmOpenstack: 'com.instana.forge.infrastructure.paas.ibmopenstack.derivedentity.openstack.IbmOpenstack',
  ibmOpenstackComputeInstance:
    'com.instana.forge.infrastructure.paas.ibmopenstack.derivedentity.computeinstance.IbmOpenstackComputeInstance',
  ibmOpenstackHypervisor:
    'com.instana.forge.infrastructure.paas.ibmopenstack.derivedentity.hypervisor.IbmOpenstackHypervisor',
  ibmOpenstackRegion: 'com.instana.forge.infrastructure.paas.ibmopenstack.derivedentity.region.IbmOpenstackRegion',
  ibmVsi: 'com.instana.forge.hardware.virtual.ibm.vsi.IbmVsi',
  ibmZOsConnect: 'com.instana.forge.infrastructure.application.ibmzos.IbmZOsConnect',
  instanaAgent: 'com.instana.forge.infrastructure.application.instana.agent.InstanaAgent',
  jBossAsApplicationContainer: 'com.instana.forge.infrastructure.application.jbossas.JBossAsApplicationContainer',
  jbossDataGrid: 'com.instana.forge.infrastructure.cache.jbossdatagrid.JbossDataGrid',
  jenkins: 'com.instana.forge.infrastructure.ci_cd.jenkins.Jenkins',
  jettyApplicationContainer: 'com.instana.forge.infrastructure.application.jetty.JettyApplicationContainer',
  jiraApplication: 'com.instana.forge.infrastructure.application.jira.JiraApplication',
  jvmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.jvm.JvmRuntimePlatform',
  kafka: 'com.instana.forge.infrastructure.messaging.kafka.Kafka',
  kafkaCluster: 'com.instana.forge.infrastructure.messaging.kafka.KafkaCluster',
  kafkaConnectCluster:
    'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.cluster.KafkaConnectCluster',
  kafkaConnectConnector:
    'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.connector.KafkaConnectConnector',
  kafkaConnectWorker: 'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.worker.KafkaConnectWorker',
  kafkaConnectTask: 'com.instana.forge.infrastructure.messaging.kafkaconnect.derivedentity.worker.KafkaConnectTask',
  kongApigateway: 'com.instana.forge.infrastructure.apigateway.kong.KongApigateway',
  kubernetesCluster: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesCluster',
  kubernetesCronJob: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.batch.KubernetesCronJob',
  kubernetesDaemonSet: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.daemonset.KubernetesDaemonSet',
  kubernetesDeployment:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.deployment.KubernetesDeployment',
  kubernetesEndpoints: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.endpoints.KubernetesEndpoints',
  kubernetesHorizontalPodAutoscaler:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.horizontalpodautoscaler.KubernetesHorizontalPodAutoscaler',
  kubernetesJob: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.batch.KubernetesJob',
  kubernetesNamespace: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.namespace.KubernetesNamespace',
  kubernetesNode: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.node.KubernetesNode',
  kubernetesPersistentVolume:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.volume.KubernetesPersistentVolume',
  kubernetesPersistentVolumeClaim:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.volume.KubernetesPersistentVolumeClaim',
  kubernetesPod: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.pod.KubernetesPod',
  kubernetesReplicaSet:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.replicaset.KubernetesReplicaSet',
  kubernetesReplicationController:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.replicationcontroller.KubernetesReplicationController',
  kubernetesService: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.service.KubernetesService',
  kubernetesStatefulSet:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.statefulset.KubernetesStatefulSet',
  liferayApplicationContainer: 'com.instana.forge.infrastructure.application.liferay.LiferayApplicationContainer',
  lxc: 'com.instana.forge.infrastructure.virtualization.lxc.Lxc',
  mariaDbDatabase: 'com.instana.forge.infrastructure.database.mariadb.MariaDbDatabase',
  memcached: 'com.instana.forge.infrastructure.cache.memcached.Memcached',
  mongoDb: 'com.instana.forge.infrastructure.database.mongodb.MongoDb',
  mongoDbCluster: 'com.instana.forge.connection.database.mongodb.MongoDbCluster',
  mongoDbReplicaSet: 'com.instana.forge.connection.database.mongodb.MongoDbReplicaSet',
  msiis: 'com.instana.forge.infrastructure.webserver.msiis.Msiis',
  msSqlDatabase: 'com.instana.forge.infrastructure.database.mssql.MsSqlDatabase',
  mule: 'com.instana.forge.infrastructure.messaging.mule.Mule',
  mySqlDatabase: 'com.instana.forge.infrastructure.database.mysql.MySqlDatabase',
  nats: 'nats',
  natsStreaming: 'natsStreaming',
  neo4j: 'com.instana.forge.infrastructure.database.neo4j.Neo4j',
  netCoreRuntimePlatform: 'com.instana.forge.infrastructure.runtime.netcore.NetCoreRuntimePlatform',
  nomadScheduler: 'com.instana.forge.infrastructure.scheduler.nomad.NomadScheduler',
  nginx: 'com.instana.forge.infrastructure.webserver.nginx.Nginx',
  nodeJsRuntimePlatform: 'com.instana.forge.infrastructure.runtime.nodejs.NodeJsRuntimePlatform',
  nova: 'com.instana.forge.hardware.virtual.openstack.Nova',
  nutanixDatacenter: 'com.instana.forge.infrastructure.paas.nutanix.derivedentity.datacenter.NutanixDatacenter',
  nutanixHost: 'com.instana.forge.infrastructure.paas.nutanix.derivedentity.host.NutanixHost',
  opc: 'com.instana.forge.hardware.virtual.opc.Opc',
  oracleDB: 'com.instana.forge.infrastructure.database.oracledb.OracleDB',
  openLDAP: 'com.instana.forge.infrastructure.directory.openldap.OpenLDAP',
  openshiftDeploymentConfig:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.openshift.deploymentconfig.OpenshiftDeploymentConfig',
  openTelemetry: 'com.instana.forge.infrastructure.custom.opentelemetry.OpenTelemetry',
  oTelDatabase: 'com.instana.forge.infrastructure.custom.sensorsdk.database.OTelDatabase',
  oTelLLM: 'com.instana.forge.infrastructure.custom.sensorsdk.llmonitor.OTelLLM',
  oTelVLLM: 'com.instana.forge.infrastructure.custom.sensorsdk.vllm.OTelVLLM',
  oTelDcgm: 'com.instana.forge.infrastructure.custom.sensorsdk.dcgm.OTelDcgm',
  oTelJvm: 'com.instana.forge.infrastructure.custom.sensorsdk.jvm.OTelJvm',
  oTelK8sPod: 'com.instana.forge.infrastructure.custom.sensorsdk.k8s.OTelK8sPod',
  oTelK8sCluster: 'com.instana.forge.infrastructure.custom.sensorsdk.k8s.OTelK8sCluster',
  oTelK8sNode: 'com.instana.forge.infrastructure.custom.sensorsdk.k8s.OTelK8sNode',
  otelHost: 'com.instana.forge.infrastructure.os.otelhost.OtelHost',
  otelProcess: 'com.instana.forge.infrastructure.os.otelprocess.OtelProcess',
  packet: 'com.instana.forge.hardware.virtual.Packet',
  pCFApplication: 'com.instana.forge.infrastructure.paas.cloudfoundry.PCFApplication',
  pCFOrganization: 'com.instana.forge.infrastructure.paas.cloudfoundry.PCFOrganization',
  pCFSpace: 'com.instana.forge.infrastructure.paas.cloudfoundry.PCFSpace',
  perfCounters: 'com.instana.forge.common.PerfCounters',
  phmcConsole: 'com.instana.forge.infrastructure.paas.phmc.derivedentity.console.PhmcConsole',
  phmcSystem: 'com.instana.forge.infrastructure.paas.phmc.derivedentity.system.PhmcSystem',
  phmcLPAR: 'com.instana.forge.infrastructure.paas.phmc.derivedentity.lpar.PhmcLPAR',
  phmcSharedProcessorPool: 'com.instana.forge.infrastructure.paas.phmc.derivedentity.sppool.PhmcSharedProcessorPool',
  phmcVIOS: 'com.instana.forge.infrastructure.paas.phmc.derivedentity.vios.PhmcVIOS',
  phpFpmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.phpfpm.PhpFpmRuntimePlatform',
  phpRuntimePlatform: 'com.instana.forge.infrastructure.runtime.php.PhpRuntimePlatform',
  ping: 'com.instana.forge.infrastructure.synthetic.ping.Ping',
  pingDirectory: 'com.instana.forge.infrastructure.directory.pingdirectory.PingDirectory',
  postgreSqlDatabase: 'com.instana.forge.infrastructure.database.postgresql.PostgreSqlDatabase',
  podman: 'com.instana.forge.infrastructure.virtualization.podman.Podman',
  powerVCRegion: 'com.instana.forge.infrastructure.paas.ibmpowervc.derivedentity.region.PowerVCRegion',
  powerVCHypervisor: 'com.instana.forge.infrastructure.paas.ibmpowervc.derivedentity.hypervisor.PowerVCHypervisor',
  powerVCComputeInstance:
    'com.instana.forge.infrastructure.paas.ibmpowervc.derivedentity.computeinstance.PowerVCComputeInstance',
  process: 'com.instana.forge.infrastructure.os.process.Process',
  processingStatistics: 'com.instana.forge.ProcessingStatistics',
  processingStatisticsMember: 'com.instana.forge.ProcessingStatisticsMember',
  prometheus: 'com.instana.forge.infrastructure.custom.prometheus.Prometheus',
  pythonRuntimePlatform: 'com.instana.forge.infrastructure.runtime.python.PythonRuntimePlatform',
  rabbitMq: 'com.instana.forge.infrastructure.messaging.rabbitmq.RabbitMq',
  rabbitMqCluster: 'com.instana.forge.infrastructure.messaging.rabbitmq.RabbitMqCluster',
  redis: 'com.instana.forge.infrastructure.cache.redis.Redis',
  redisEnterpriseNode: 'com.instana.forge.infrastructure.cache.redisenterprise.derivedentity.node.RedisEnterpriseNode',
  redisCluster: 'com.instana.forge.infrastructure.cache.redis.RedisCluster',
  redisEnterpriseCluster: 'com.instana.forge.infrastructure.cache.redisenterprise.RedisEnterpriseCluster',
  redisEnterpriseDatabase: 'com.instana.forge.infrastructure.cache.redisenterprise.RedisEnterpriseDatabase',
  redisEnterpriseShard: 'com.instana.forge.infrastructure.cache.redisenterprise.RedisEnterpriseShard',
  rubyRuntimePlatform: 'com.instana.forge.infrastructure.runtime.ruby.RubyRuntimePlatform',
  sapHana: 'com.instana.forge.infrastructure.database.saphana.SapHana',
  service: 'com.instana.forge.application.Service',
  snowflake: 'com.instana.forge.infrastructure.database.snowflake.Snowflake',
  solr: 'com.instana.forge.infrastructure.database.solr.Solr',
  solrCloudCluster: 'com.instana.forge.infrastructure.database.solr.SolrCloudCluster',
  snowflakeOrganization: 'com.instana.forge.infrastructure.database.snowflake.SnowflakeOrganization',
  springbootApplicationContainer:
    'com.instana.forge.infrastructure.application.springboot.SpringbootApplicationContainer',
  sparkApplication: 'com.instana.forge.infrastructure.dataanalytics.sparkapplication.SparkApplication',
  sparkStandalone: 'com.instana.forge.infrastructure.dataanalytics.sparkstandalone.SparkStandalone',
  statsd: 'com.instana.forge.common.Statsd',
  sybase: 'com.instana.forge.infrastructure.database.sybase.Sybase',
  syntheticPoP: 'com.instana.forge.infrastructure.synthetic.pop.SyntheticPoP',
  tanzuFoundation: 'com.instana.forge.infrastructure.paas.cloudfoundry.tanzu_foundation.TanzuFoundation',
  tanzuFoundationMember: 'com.instana.forge.infrastructure.paas.cloudfoundry.tanzu_foundation.TanzuFoundationMember',
  tibcoASNode: 'com.instana.forge.infrastructure.database.tibcoas.TibcoASNode',
  tibcoASDataGrid: 'com.instana.forge.infrastructure.database.tibcoas.TibcoASDataGrid',
  tibcoASProxy: 'com.instana.forge.infrastructure.database.tibcoas.TibcoASProxy',
  tibcoBWAppNode: 'com.instana.forge.infrastructure.application.tibcobw.TibcoBWAppNode',
  tibcoBWAppInst: 'com.instana.forge.infrastructure.application.tibcobw.derivedentity.TibcoBWAppInst',
  tibcoBWProcess: 'com.instana.forge.infrastructure.application.tibcobw.derivedentity.TibcoBWProcess',
  tibcoEMS: 'com.instana.forge.infrastructure.messaging.tibcoems.TibcoEMS',
  tibcoEMSTopic: 'com.instana.forge.infrastructure.messaging.tibcoems.derivedentity.topic.TibcoEMSTopic',
  tibcoEMSQueue: 'com.instana.forge.infrastructure.messaging.tibcoems.derivedentity.queue.TibcoEMSQueue',
  tomcatApplicationContainer: 'com.instana.forge.infrastructure.application.tomcat.TomcatApplicationContainer',
  traefik: 'com.instana.forge.infrastructure.loadbalancer.traefik.Traefik',
  tuxedoDomain: 'com.instana.forge.infrastructure.application.tuxedo.TuxedoDomain',
  tuxedoMachine: 'com.instana.forge.infrastructure.application.tuxedo.derivedentity.machine.TuxedoMachine',
  tuxedoServer: 'com.instana.forge.infrastructure.application.tuxedo.derivedentity.server.TuxedoServer',
  tuxedoIpcQueue: 'com.instana.forge.infrastructure.application.tuxedo.derivedentity.ipcqueue.TuxedoIpcQueue',
  tuxedoAppApplication:
    'com.instana.forge.infrastructure.application.tuxedoApp.derivedentity.application.TuxedoAppApplication',
  tuxedoAppServiceBrokerProject:
    'com.instana.forge.infrastructure.application.tuxedoApp.derivedentity.servicebrokerproject.TuxedoAppServiceBrokerProject',
  tuxedoAppTuxedoService:
    'com.instana.forge.infrastructure.application.tuxedoApp.derivedentity.tuxedoservice.TuxedoAppTuxedoService',

  unmonitoredHost: 'com.instana.forge.infrastructure.UnmonitoredHost',
  varnish: 'com.instana.forge.infrastructure.cache.varnish.Varnish',
  vault: 'com.instana.forge.infrastructure.database.vault.Vault',
  vsphereDatacenter: 'com.instana.forge.infrastructure.paas.vsphere.derivedentity.datacenter.VsphereDatacenter',
  vsphereHost: 'com.instana.forge.infrastructure.paas.vsphere.derivedentity.host.VsphereHost',
  vsphereVM: 'com.instana.forge.infrastructure.paas.vsphere.derivedentity.vm.VsphereVM',
  webLogicApplicationContainer: 'com.instana.forge.infrastructure.application.weblogic.WebLogicApplicationContainer',
  websiteHttpd: 'com.instana.forge.infrastructure.eum.derivedentity.WebsiteHttpd',
  webSphereApplicationContainer: 'com.instana.forge.infrastructure.application.websphere.WebSphereApplicationContainer',
  webSphereInfrastructureManager:
    'com.instana.forge.infrastructure.application.webspheredmgr.WebSphereInfrastructureManager',
  webSphereDeploymentManager:
    'com.instana.forge.infrastructure.application.webspheredmgr.derivedentity.dmgr.WebSphereDeploymentManager',
  webSphereCluster: 'com.instana.forge.infrastructure.application.webspheredmgr.derivedentity.cluster.WebSphereCluster',
  webSphereLibertyApplicationContainer:
    'com.instana.forge.infrastructure.application.websphere.WebSphereLibertyApplicationContainer',
  webSphereMember: 'com.instana.forge.infrastructure.application.webspheredmgr.derivedentity.member.WebSphereMember',
  zhmcConsole: 'com.instana.forge.infrastructure.paas.zhmc.derivedentity.console.ZhmcConsole',
  zhmcCpc: 'com.instana.forge.infrastructure.paas.zhmc.derivedentity.console.ZhmcCpc',
  zooKeeper: 'com.instana.forge.infrastructure.database.zookeeper.ZooKeeper',
  zOS: 'com.instana.forge.ibm.ibmz.os.ZOS',
  zDb2: 'com.instana.forge.ibm.ibmz.db2.ZDb2',
  zCics: 'com.instana.forge.ibm.ibmz.cics.ZCics',
  zIms: 'com.instana.forge.ibm.ibmz.ims.ZIms',
  zCtg: 'com.instana.forge.ibm.ibmz.ctg.ZCtg',
  abapInstance: 'com.instana.forge.infrastructure.paas.sap.derivedentity.abapinstance.AbapInstance',
  abapSystem: 'com.instana.forge.infrastructure.paas.sap.derivedentity.abapsystem.AbapSystem',
  sapDbms: 'com.instana.forge.infrastructure.paas.sap.derivedentity.sapdbms.SapDbms',
  sapDbInstance: 'com.instana.forge.infrastructure.paas.sap.derivedentity.sapdbinstance.SapDbInstance',
  sapDbTenant: 'com.instana.forge.infrastructure.paas.sap.derivedentity.sapdbtenant.SapDbTenant',
  sapHost: 'com.instana.forge.infrastructure.paas.sap.SapHost',
  sapHanaPlatform: 'com.instana.forge.infrastructure.paas.sap.derivedentity.saphana.SapHanaPlatform',
  sapJavaSystem: 'com.instana.forge.infrastructure.paas.sap.derivedentity.javasystem.SapJavaSystem',
  sapJavaInstance: 'com.instana.forge.infrastructure.paas.sap.derivedentity.javainstance.SapJavaInstance',
  sapHanaSystem: 'com.instana.forge.infrastructure.paas.sap.derivedentity.saphanasystem.SapHanaSystem',
  sapWebDispatcher: 'com.instana.forge.infrastructure.paas.sap.derivedentity.sapwebdispatcher.SapWebDispatcher',
  sapAbapInstanceSensor: 'com.instana.forge.infrastructure.paas.sapjco.SapAbapInstanceSensor',
  sapAbapSystemSensor: 'com.instana.forge.infrastructure.paas.sapjco.derivedentity.system.SapAbapSystemSensor',
  remoteHost: 'com.instana.forge.infrastructure.remote.remotehost.RemoteHost',
  processGroup: 'com.instana.forge.infrastructure.remote.processgroup.ProcessGroup'
};

export function translateFullyQualifiedPluginToShortPluginName(fullyQualifiedPlugin: string): string | null {
  return (
    Object.entries(fullyQualifiedPlugins).find(
      ([_key, fullyQualifiedName]) => fullyQualifiedName === fullyQualifiedPlugin
    )?.[0] ?? null
  );
}
