import { assign } from 'lodash';

/* eslint-disable max-len */
export const ID_OF_UNMONITORED_ZONE = '5nXT64z0gY0pShCaT5VQ7wGu-0E';
export const ID_OF_PROCESSING_STATISTICS = '_9Ct9EsdanGCFtGIG_j7wNKr5hE';

export const nonServicePlugins = {
  activemq: 'activeMQ',
  activemqartemis: 'activeMQArtemis',
  availabilityZone: 'availabilityZone',
  awsBeanstalk: 'awsBeanstalk',
  awsDynamoDb: 'awsDynamoDb',
  awsEc: 'awsEc',
  awsEs: 'awsEs',
  awsElb: 'awsElb',
  awsKinesis: 'awsKinesis',
  awsLambda: 'awsLambda',
  awsMq: 'awsMq',
  awsRds: 'awsRds',
  awsSqs: 'awsSqs',
  awsS3: 'awsS3',
  awsEbs: 'awsEbs',
  azure: 'azure',
  azureApiManagement: 'azureApiManagement',
  azureAppService: 'azureAppService',
  azureCosmosDb: 'azureCosmosDb',
  azureRedisCache: 'azureRedisCache',
  azureSqlDatabase: 'azureSqlDatabase',
  azureSqlDb: 'azureSqlDb',
  azureSqlElasticPool: 'azureSqlElasticPool',
  azureSqlServer: 'azureSqlServer',
  azureStorage: 'azureStorage',
  bizTalk: 'bizTalk',
  cassandra: 'cassandraNode',
  cassandraCluster: 'cassandraCluster',
  ceph: 'ceph',
  clrRuntimePlatform: 'clrRuntimePlatform',
  clickHouseDatabase: 'clickHouseDatabase',
  cloudFoundry: 'cloudFoundry',
  cockroachDBCluster: 'cockroachDBCluster',
  cockroachDB: 'cockroachDBNode',
  containerd: 'containerd',
  consul: 'consul',
  consulCluster: 'consulCluster',
  couchbase: 'couchbaseNode',
  couchbaseCluster: 'couchbaseCluster',
  crystal: 'crystalRuntimePlatform',
  docker: 'docker',
  dropwizard: 'dropwizardApplicationContainer',
  ec2: 'ec2',
  elasticsearch: 'elasticsearchNode',
  elasticsearchCluster: 'elasticsearchCluster',
  etcd: 'etcd',
  finagle: 'finagleApplicationContainer',
  f5: 'f5',
  garden: 'garden',
  gce: 'gce',
  googleCloudSQL: 'googleCloudSQL',
  genericHardware: 'genericHardware',
  genericZone: 'genericZone',
  glassfish: 'glassfishApplicationContainer',
  golang: 'golangRuntimePlatform',
  hadoopYARN: 'hadoopYARN',
  hadoopYARNNode: 'hadoopYARNNode',
  haproxy: 'hAProxy',
  haskell: 'haskellRuntimePlatform',
  hazelcastCluster: 'hazelcastCluster',
  hazelcastNode: 'hazelcastNode',
  hbase: 'hBase',
  host: 'host',
  httpd: 'httpd',
  instanaAgent: 'instanaAgent',
  jbossas: 'jBossAsApplicationContainer',
  jbossdatagrid: 'jbossDataGrid',
  jenkins: 'jenkins',
  jetty: 'jettyApplicationContainer',
  jira: 'jiraApplication',
  jvm: 'jvmRuntimePlatform',
  kafka: 'kafka',
  kafkaCluster: 'kafkaCluster',
  kubernetesCluster: 'kubernetesCluster',
  kubernetesPod: 'kubernetesPod',
  kubernetesNode: 'kubernetesNode',
  kubernetesReplicaSet: 'kubernetesReplicaSet',
  kubernetesDeployment: 'kubernetesDeployment',
  kubernetesNamespace: 'kubernetesNamespace',
  liferay: 'liferayApplicationContainer',
  mariaDbDatabase: 'mariaDbDatabase',
  memcached: 'memcached',
  mongodb: 'mongoDb',
  mongodbReplicaSet: 'mongoDbReplicaSet',
  msiis: 'msiis',
  mssql: 'msSqlDatabase',
  mule: 'mule',
  mysql: 'mySqlDatabase',
  netCoreRuntimePlatform: 'netCoreRuntimePlatform',
  neo4j: 'neo4j',
  nginx: 'nginx',
  nodejs: 'nodeJsRuntimePlatform',
  nomadScheduler: 'nomadScheduler',
  nova: 'nova',
  opc: 'opc',
  oracledb: 'oracleDB',
  openLDAP: 'openLDAP',
  openshiftDeploymentConfig: 'openshiftDeploymentConfig',
  packet: 'packet',
  phpfpm: 'phpFpmRuntimePlatform',
  php: 'phpRuntimePlatform',
  ping: 'ping',
  pingDirectory: 'pingDirectory',
  postgresql: 'postgreSqlDatabase',
  process: 'process',
  prometheus: 'prometheus',
  python: 'pythonRuntimePlatform',
  rabbitmq: 'rabbitMq',
  redis: 'redis',
  ruby: 'rubyRuntimePlatform',
  sapHana: 'sapHana',
  solr: 'solr',
  sparkApplication: 'sparkApplication',
  sparkStandalone: 'sparkStandalone',
  springboot: 'springbootApplicationContainer',
  statsd: 'statsd',
  tomcat: 'tomcatApplicationContainer',
  unmonitoredHost: 'unmonitoredHost',
  varnish: 'varnish',
  webLogic: 'webLogicApplicationContainer',
  webSphere: 'webSphereApplicationContainer',
  webSphereLiberty: 'webSphereLibertyApplicationContainer',
  zookeeper: 'zooKeeper'
};

export const applicationPlugins = {
  application: 'application',
  defaultEntity20: 'defaultEntity20',
  endpoint: 'endpoint',
  service: 'service'
};

export const plugins = assign({}, applicationPlugins, nonServicePlugins);

export const defaultAndUnknownPluginNames = [
  'unknownService',
  'defaultEntity20',
  'defaultLogicalConnection',
  'defaultLogicalService',
  'defaultServiceInstance'
];

export const customIssuesDisabledForPlugins = [...defaultAndUnknownPluginNames];

export const fullyQualifiedPlugins = {
  activeMQ: 'com.instana.forge.infrastructure.messaging.activemq.ActiveMQ',
  activeMQArtemis: 'com.instana.forge.infrastructure.messaging.activemqartemis.ActiveMQArtemis',
  application: 'com.instana.forge.application.Application',
  availabilityZone: 'com.instana.forge.hardware.AvailabilityZone',
  awsBeanstalk: 'com.instana.forge.hardware.virtual.aws.beanstalk.AwsBeanstalk',
  awsDynamoDb: 'com.instana.forge.hardware.virtual.aws.dynamodb.AwsDynamoDb',
  awsEc: 'com.instana.forge.hardware.virtual.aws.ec.AwsEc',
  awsEs: 'com.instana.forge.hardware.virtual.aws.es.AwsEs',
  awsElb: 'com.instana.forge.hardware.virtual.aws.elb.AwsElb',
  awsKinesis: 'com.instana.forge.hardware.virtual.aws.kinesis.AwsKinesis',
  awsLambda: 'com.instana.forge.hardware.virtual.aws.lambda.AwsLambda',
  awsMq: 'com.instana.forge.hardware.virtual.aws.mq.AwsMq',
  awsRds: 'com.instana.forge.hardware.virtual.aws.rds.AwsRds',
  awsSqs: 'com.instana.forge.hardware.virtual.aws.sqs.AwsSqs',
  awsS3: 'com.instana.forge.hardware.virtual.aws.sqs.AwsS3',
  awsEbs: 'com.instana.forge.hardware.virtual.aws.ebs.AwsEbs',
  azure: 'com.instana.forge.hardware.virtual.azure.Azure',
  azureApiManagement: 'com.instana.forge.hardware.virtual.azure.apimanagement.AzureApiManagement',
  azureAppService: 'com.instana.forge.hardware.virtual.azure.appservice.AzureAppService',
  azureCosmosDb: 'com.instana.forge.hardware.virtual.azure.cosmosdb.AzureCosmosDb',
  azureRedisCache: 'com.instana.forge.hardware.virtual.azure.rediscache.AzureRedisCache',
  azureStorage: 'com.instana.forge.hardware.virtual.azure.storage.AzureStorage',
  azureSqlDatabase: 'com.instana.forge.hardware.virtual.azure.sqldatabase.AzureSqlDatabase',
  azureSqlDb: 'com.instana.forge.hardware.virtual.azure.sqldb.AzureSqlDb',
  azureSqlElasticPool: 'com.instana.forge.hardware.virtual.azure.sqlelasticpool.AzureSqlElasticPool',
  azureSqlServer: 'com.instana.forge.hardware.virtual.azure.sqlserver.AzureSqlServer',
  bizTalk: 'com.instana.forge.infrastructure.messaging.biztalk.BizTalk',
  cassandraCluster: 'com.instana.forge.infrastructure.database.cassandra.CassandraCluster',
  cassandraNode: 'com.instana.forge.infrastructure.database.cassandra.CassandraNode',
  ceph: 'com.instana.forge.infrastructure.database.ceph.Ceph',
  clrRuntimePlatform: 'com.instana.forge.infrastructure.runtime.clr.ClrRuntimePlatform',
  clickHouseDatabase: 'com.instana.forge.infrastructure.database.clickhouse.ClickHouseDatabase',
  cloudFoundry: 'com.instana.forge.infrastructure.paas.cloudfoundry.CloudFoundry',
  cockroachDBCluster: 'com.instana.forge.infrastructure.database.cockroachdb.CockroachDBCluster',
  cockroachDBNode: 'com.instana.forge.infrastructure.database.cockroachdb.CockroachDBNode',
  containerd: 'com.instana.forge.infrastructure.virtualization.containerd.Containerd',
  consul: 'com.instana.forge.infrastructure.discovery.consul.Consul',
  consulCluster: 'com.instana.forge.infrastructure.discovery.consul.ConsulCluster',
  couchbaseCluster: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseCluster',
  couchbaseNode: 'com.instana.forge.infrastructure.database.couchbase.CouchbaseNode',
  crystalRuntimePlatform: 'com.instana.forge.infrastructure.runtime.crystal.CrystalRuntimePlatform',
  defaultEntity20: 'defaultEntity20',
  docker: 'com.instana.forge.infrastructure.virtualization.docker.Docker',
  dropwizardApplicationContainer:
    'com.instana.forge.infrastructure.application.dropwizard.DropwizardApplicationContainer',
  ec2: 'com.instana.forge.hardware.virtual.ec2.Ec2',
  elasticsearchCluster: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchCluster',
  elasticsearchNode: 'com.instana.forge.infrastructure.database.elasticsearch.ElasticsearchNode',
  endpoint: 'com.instana.forge.application.Endpoint',
  etcd: 'com.instana.forge.infrastructure.cache.etcd.Etcd',
  finagleApplicationContainer: 'com.instana.forge.infrastructure.application.finagle.FinagleApplicationContainer',
  f5: 'com.instana.forge.infrastructure.loadbalancer.F5',
  garden: 'com.instana.forge.infrastructure.virtualization.garden.Garden',
  gce: 'com.instana.forge.hardware.virtual.gce.Gce',
  googleCloudSQL: 'com.instana.forge.hardware.virtual.gcp.sql.GoogleCloudSQL',
  genericHardware: 'com.instana.forge.hardware.GenericHardware',
  genericZone: 'com.instana.forge.hardware.GenericZone',
  glassfishApplicationContainer: 'com.instana.forge.infrastructure.application.glassfish.GlassfishApplicationContainer',
  golangRuntimePlatform: 'com.instana.forge.infrastructure.runtime.golang.GolangRuntimePlatform',
  hadoopYARN: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarn.HadoopYARN',
  hadoopYARNNode: 'com.instana.forge.infrastructure.dataanalytics.hadoopyarnnode.HadoopYARNNode',
  hAProxy: 'com.instana.forge.infrastructure.loadbalancer.haproxy.HAProxy',
  haskellRuntimePlatform: 'com.instana.forge.infrastructure.runtime.haskell.HaskellRuntimePlatform',
  hazelcastCluster: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastCluster',
  hazelcastNode: 'com.instana.forge.infrastructure.database.hazelcast.HazelcastNode',
  hBase: 'com.instana.forge.infrastructure.database.hbase.HBase',
  host: 'com.instana.forge.infrastructure.os.host.Host',
  httpd: 'com.instana.forge.infrastructure.webserver.httpd.Httpd',
  instanaAgent: 'com.instana.forge.infrastructure.application.instana.agent.InstanaAgent',
  jBossAsApplicationContainer: 'com.instana.forge.infrastructure.application.jbossas.JBossAsApplicationContainer',
  jbossDataGrid: 'com.instana.forge.infrastructure.cache.jbossdatagrid.JbossDataGrid',
  jenkins: 'com.instana.forge.infrastructure.ci_cd.jenkins.Jenkins',
  jettyApplicationContainer: 'com.instana.forge.infrastructure.application.jetty.JettyApplicationContainer',
  jiraApplication: 'com.instana.forge.infrastructure.application.jira.JiraApplication',
  jvmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.jvm.JvmRuntimePlatform',
  kafka: 'com.instana.forge.infrastructure.messaging.kafka.Kafka',
  kafkaCluster: 'com.instana.forge.infrastructure.messaging.kafka.KafkaCluster',
  kubernetesCluster: 'com.instana.forge.infrastructure.paas.kubernetes.KubernetesCluster',
  kubernetesPod: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.pod.KubernetesPod',
  kubernetesDeployment:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.deployment.KubernetesDeployment',
  kubernetesNamespace: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.namespace.KubernetesNamespace',
  kubernetesNode: 'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.node.KubernetesNode',
  kubernetesReplicaSet:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.replicaset.KubernetesReplicaSet',
  liferayApplicationContainer: 'com.instana.forge.infrastructure.application.liferay.LiferayApplicationContainer',
  mariaDbDatabase: 'com.instana.forge.infrastructure.database.mariadb.MariaDbDatabase',
  memcached: 'com.instana.forge.infrastructure.cache.memcached.Memcached',
  mongoDb: 'com.instana.forge.infrastructure.database.mongodb.MongoDb',
  mongoDbReplicaSet: 'com.instana.forge.connection.database.mongodb.MongoDbReplicaSet',
  msiis: 'com.instana.forge.infrastructure.webserver.msiis.Msiis',
  msSqlDatabase: 'com.instana.forge.infrastructure.database.mssql.MsSqlDatabase',
  mule: 'com.instana.forge.infrastructure.messaging.mule.Mule',
  mySqlDatabase: 'com.instana.forge.infrastructure.database.mysql.MySqlDatabase',
  neo4j: 'com.instana.forge.infrastructure.database.neo4j.Neo4j',
  netCoreRuntimePlatform: 'com.instana.forge.infrastructure.runtime.netcore.NetCoreRuntimePlatform',
  nomadScheduler: 'com.instana.forge.infrastructure.scheduler.nomad.NomadScheduler',
  nginx: 'com.instana.forge.infrastructure.webserver.nginx.Nginx',
  nodeJsRuntimePlatform: 'com.instana.forge.infrastructure.runtime.nodejs.NodeJsRuntimePlatform',
  nova: 'com.instana.forge.hardware.virtual.openstack.Nova',
  opc: 'com.instana.forge.hardware.virtual.opc.Opc',
  oracleDB: 'com.instana.forge.infrastructure.database.oracledb.OracleDB',
  openLDAP: 'com.instana.forge.infrastructure.directory.openldap.OpenLDAP',
  openshiftDeploymentConfig:
    'com.instana.forge.infrastructure.paas.kubernetes.derivedentity.openshift.deploymentconfig.OpenshiftDeploymentConfig',
  packet: 'com.instana.forge.hardware.virtual.Packet',
  phpFpmRuntimePlatform: 'com.instana.forge.infrastructure.runtime.phpfpm.PhpFpmRuntimePlatform',
  phpRuntimePlatform: 'com.instana.forge.infrastructure.runtime.php.PhpRuntimePlatform',
  ping: 'com.instana.forge.infrastructure.synthetic.ping.Ping',
  pingDirectory: 'com.instana.forge.infrastructure.directory.pingdirectory.PingDirectory',
  postgreSqlDatabase: 'com.instana.forge.infrastructure.database.postgresql.PostgreSqlDatabase',
  process: 'com.instana.forge.infrastructure.os.process.Process',
  prometheus: 'com.instana.forge.infrastructure.custom.prometheus.Prometheus',
  pythonRuntimePlatform: 'com.instana.forge.infrastructure.runtime.python.PythonRuntimePlatform',
  rabbitMq: 'com.instana.forge.infrastructure.messaging.rabbitmq.RabbitMq',
  redis: 'com.instana.forge.infrastructure.cache.redis.Redis',
  rubyRuntimePlatform: 'com.instana.forge.infrastructure.runtime.ruby.RubyRuntimePlatform',
  sapHana: 'com.instana.forge.infrastructure.database.saphana.SapHana',
  service: 'com.instana.forge.application.Service',
  solr: 'com.instana.forge.infrastructure.database.solr.Solr',
  springbootApplicationContainer:
    'com.instana.forge.infrastructure.application.springboot.SpringbootApplicationContainer',
  sparkApplication: 'com.instana.forge.infrastructure.dataanalytics.sparkapplication.SparkApplication',
  sparkStandalone: 'com.instana.forge.infrastructure.dataanalytics.sparkstandalone.SparkStandalone',
  statsd: 'com.instana.forge.common.Statsd',
  tomcatApplicationContainer: 'com.instana.forge.infrastructure.application.tomcat.TomcatApplicationContainer',
  unmonitoredHost: 'com.instana.forge.infrastructure.UnmonitoredHost',
  varnish: 'com.instana.forge.infrastructure.cache.varnish.Varnish',
  webLogicApplicationContainer: 'com.instana.forge.infrastructure.application.weblogic.WebLogicApplicationContainer',
  webSphereApplicationContainer: 'com.instana.forge.infrastructure.application.websphere.WebSphereApplicationContainer',
  webSphereLibertyApplicationContainer:
    'com.instana.forge.infrastructure.application.websphere.WebSphereLibertyApplicationContainer',
  zooKeeper: 'com.instana.forge.infrastructure.database.zookeeper.ZooKeeper'
};
