port: 4000
root: false
ssi: true
proxy:
  #the local address from gulp dev
  '/': http://127.0.0.1:7272

  #service API
  #'/api/': http://127.0.0.1:8080/ #local backend
  '/api/': http://192.168.0.114:8080/ #local backend
websocketProxy:
  #'/api/data': http://localhost:8080/data #dummy backend
  '/api/data': http://192.168.0.114:8080/data
