checksumBehavior: update

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmPublishRegistry: "https://delivery.instana.io/artifactory/api/npm/int-npm-local/"

npmRegistryServer: "https://delivery.instana.io/artifactory/api/npm/int-npm-virtual/"

yarnPath: .yarn/releases/yarn-3.7.0.cjs
