version: 0.2

env:
  variables:
    CODEBUILD_PROJECT_NAME: "ui-client-storybook"
    RUN_UI_TEST_ON_DELIVERY: "false"
  parameter-store:
    EFS_DATA_DIR: "efs.data.dir"
    EFS_DNS: "efs.data.dns"
    GITHUB_READ_USER: "github.read.user"
    GITHUB_READ_PASSWORD: "github.read.password"
    CONTAINERS_INSTANA_IO_USER: "containers.instana.io.user"
    CONTAINERS_INSTANA_IO_PASSWORD: "containers.instana.io.password"
    ARTIFACT_INSTANA_IO_USER: "artifact.instana.io.user"
    ARTIFACT_INSTANA_IO_PASSWORD: "artifact.instana.io.password"
    AWS_ACCESS_KEY_ID: "s3.devinfra.access.key.id"
    AWS_SECRET_ACCESS_KEY: "s3.devinfra.secret.access.key"
    CHROMATIC_PROJECT_TOKEN: "ui_client.chromatic.project.token"
    ARTIFACT_RND_INSTANA_IO_USER: 'artifact-rnd.instana.io.user'
    ARTIFACT_RND_INSTANA_IO_PASSWORD: 'artifact-rnd.instana.io.password'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Remove SBT repository: https://github.com/aws/aws-codebuild-docker-images/issues/449
      - rm -f /etc/apt/sources.list.d/sbt.list
      # git configuration to check out git submodules
      - echo "https://$GITHUB_READ_USER:$GITHUB_READ_PASSWORD@github.com" > $HOME/.git-credentials
      - git config --global credential.helper store
      # download git submodules so that our shared CI tools are available
      - git submodule update --init --recursive
      # Set up the shared tooling
      - 'USE_N=true ./build/ci-shared-tools/scripts/setup.bash'
      - ./build/ci-shared-tools/scripts/codebuild/setup.bash
      - export GIT_BRANCH="$(./build/ci-shared-tools/scripts/git/getBranch.js)"
      # Set up the correct Node.js version
      - n `cat .nvmrc`
  pre_build:
    commands:
      - |
        REGISTRY="https://artifact-rnd.instana.io" \
          REPOSITORY_KEY="npm-virtual-internal" \
          USERNAME="$ARTIFACT_RND_INSTANA_IO_USER" \
          PASSWORD="$ARTIFACT_RND_INSTANA_IO_PASSWORD" \
          NON_INTERACTIVE=true \
          WRITE_TO_CWD=true \
          NPM_CONFIG_REGISTRY="https://registry.npmjs.org/" \
          npx create-artifactory-access-config
      # Install project dependencies
      - npm install -g yarn
      - yarn
  build:
    commands:
      - yarn run storybookBuild
      - npx s3-deploy@1.4.0 './storybookTarget/**' --cwd './storybookTarget/' --bucket instana-devinfra-ui-client-playground --deleteRemoved --invalidate
      - 'test -n "$RUN_UI_TEST_ON_DELIVERY" -a "$RUN_UI_TEST_ON_DELIVERY" = "true" && yarn run storybookTest || true # ignore failing build'
