version: 0.2

env:
  parameter-store:
    INSTANA_ARTIFACTORY_USERNAME: 'delivery.instana.io.internal.rw.username'
    INSTANA_ARTIFACTORY_PASSWORD: 'delivery.instana.io.internal.rw.password'
    AWS_ACCESS_KEY_ID: "s3.devinfra.access.key.id"
    AWS_SECRET_ACCESS_KEY: "s3.devinfra.secret.access.key"
    GITHUB_API_TOKEN: "ibm.github.e.api.token"
    GITHUB_READ_PASSWORD: "github.read.password"
    GITHUB_READ_USER: "github.read.user"
    TWISTLOCK_INSTANA_IO_PASSWORD: "twistlock.instana.io.password"
    TWISTLOCK_INSTANA_IO_USER: "twistlock.instana.io.user"
    IMAGE_SCAN_RESULTS_WRITER_SERVICE_ACCOUNT_JSON: "image.scan.results.writer.service.account.json"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Set up the shared tooling
      - ./build/download-ci-shared-tools.bash
      - 'USE_N=true ./build/ci-shared-tools/scripts/setup.bash'
      - ./build/ci-shared-tools/scripts/codebuild/setup.bash
      - docker run --rm --privileged delivery.instana.io/int-docker-private-virtual/tonistiigi/binfmt --install ppc64le
      - docker run --rm --privileged delivery.instana.io/int-docker-private-virtual/tonistiigi/binfmt --install s390x
      - docker run --rm --privileged delivery.instana.io/int-docker-private-virtual/tonistiigi/binfmt --install arm64
      # Install docker buildx
      - wget https://github.com/docker/buildx/releases/download/v0.12.1/buildx-v0.12.1.linux-amd64
      - chmod +x buildx-v0.12.1.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.12.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --name multi-arch --platform=linux/ppc64le,linux/s390x,linux/arm64 --use
      - docker buildx inspect --bootstrap
  build:
    commands:
      - cd containers && ./scripts/build-and-publish.sh ${CONTAINER_IMAGE_NAME}
