sonar.projectKey=ui-client
sonar.javascript.lcov.reportPaths=./coverage/lcov.info,./packages/in-server/coverage/lcov.info
sonar.eslint.reportPaths=./eslint-report.json
sonar.javascript.node.maxspace=8192
sonar.log.level=INFO
sonar.sources=packages/
sonar.sourceEncoding=UTF-8
# This is causing problems
# 2023-09: this was still ignoring all sources, when set to false
#          hence this setting is still needed, or further improvement of .gitignore files?
# https://community.sonarsource.com/t/all-files-excluded-by-the-scm-ignore-settings/12031
sonar.scm.exclusions.disabled=true

sonar.exclusions=packages/in-server/node_modules/**/*,packages/in-server/coverage/**/*,build/**/*,**/*.stories.js,**.stories.tsx,**/__mocks__/*,**/stories/**
sonar.coverage.exclusions=packages/in-forge/**/*,packages/in-internal/**/*,**/*_test.*,**/*.test.*

# Ignore a false positive: reporting these 11k lines of geodata
sonar.cpd.exclusions=packages/in-components/RequestQuoteDialog/geodata.js

# Ignore sonar reported issue "react props read-only"
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6759
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx
