sonar.projectKey=ui-client
sonar.javascript.lcov.reportPaths=./coverage/lcov.info,./packages/in-server/coverage/lcov.info
sonar.eslint.reportPaths=./eslint-report.json
sonar.javascript.node.maxspace=8192
sonar.log.level=DEBUG
sonar.sources=packages/
sonar.sourceEncoding=UTF-8
# This is causing problems
# https://community.sonarsource.com/t/all-files-excluded-by-the-scm-ignore-settings/12031
sonar.scm.exclusions.disabled=true
sonar.exclusions=packages/in-server/node_modules/**/*,packages/in-server/coverage/**/*,build/**/*,packages/**/**/*.story\.(js|ts|tsx|mdx)
