import debounce from './debounce';
import delayedStop from './delayedStop';
import distinct from './distinct';
import errors from './errors';
import filter from './filter';
import flatMap from './flatMap';
import freeze from './freeze';
import map from './map';
import merge from './merge';
import nextFrame from './nextFrame';
import once from './once';
import scan from './scan';
import skipFirst from './skipFirst';
import startWith from './startWith';
import startWithFn from './startWithFn';
import subscribe from './subscribe';
import tap from './tap';
import throttle from './throttle';
import transform from './transform';

export function applyOperators(prototype) {
  prototype.debounce = debounce;
  prototype.delayedStop = delayedStop;
  prototype.distinct = distinct;
  prototype.errors = errors;
  prototype.filter = filter;
  prototype.flatMap = flatMap;
  prototype.freeze = freeze;
  prototype.map = map;
  prototype.merge = merge;
  prototype.nextFrame = nextFrame;
  prototype.once = once;
  prototype.scan = scan;
  prototype.skipFirst = skipFirst;
  prototype.startWith = startWith;
  prototype.startWithFn = startWithFn;
  prototype.subscribe = subscribe;
  prototype.tap = tap;
  prototype.throttle = throttle;
  prototype.transform = transform;
}
