#!groovy

// define global vars for use in later stages
def branchName          = env.BRANCH_NAME
def isDeliveryBranch    = null
def gitCommitId         = null
def gitCommitAuthor     = null
def gitMessage          = null

void setBuildStatus(String message, String state) {
  def commitSha = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()

  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.ibm.com/instana/ui-client"],
      commitShaSource: [$class: "ManuallyEnteredShaSource", sha: commitSha],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}

pipeline {
  agent any
  options {
    ansiColor('xterm')
  }
  stages {
    stage ('Setup') {
      steps {
        milestone(label: "Setup", ordinal: null)
        setBuildStatus('Build started', 'PENDING')

        script {
          if (branchName.contains('/') || branchName.contains(',')) {
            setBuildStatus('Build failure', 'FAILURE')
            error "Build aborted: Branch names containing slashes or commas aren't allowed. Please rename your branch."
          }

          // Set up the shared tooling
          withCredentials([string(credentialsId: 'GH_IBM_API_TOKEN', variable: 'GITHUB_API_TOKEN')]) {
            sh "./build/download-ci-shared-tools.bash"
            sh "./build/ci-shared-tools/scripts/setup.bash"
          }

          isDeliveryBranch = sh(returnStdout: true, script: "./build/ci-shared-tools/scripts/isDeliveryBranch.js") == 'true'
          gitCommitId         = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
          gitCommitAuthor     = sh(returnStdout: true, script: "git --no-pager show -s --format='%ae' $gitCommitId").trim()
          gitMessage          = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an (<https://github.ibm.com/instana/ui-client/commit/%h|%h>): %s'").trim()

          currentBuild.displayName = "#${env.BUILD_NUMBER}: ${branchName}"
          stash includes: "**/*", name: "ui-client-checkout-${gitCommitId}", useDefaultExcludes: false
        }
      }
    }

    stage('Run Storybook Test') {
      steps {
        timeout(time: 30, unit: 'MINUTES') {
          timestamps {
            script {
              def RUN_UI_STORYBOOK_TEST = env.RUN_UI_STORYBOOK_TEST

              if (RUN_UI_STORYBOOK_TEST == 'true') {
                  try {
                    awsCodeBuild credentialsType: 'jenkins',
                      credentialsId: 'codebuild',
                      projectName: 'ui-client-storybook',
                      region: 'us-west-2',
                      imageOverride: 'aws/codebuild/standard:5.0',
                      sourceControlType: 'project',
                      envVariables: '[ {RUN_UI_STORYBOOK_TEST, ${RUN_UI_STORYBOOK_TEST}}, {GIT_BRANCH, ${branchName}} ]',
                      sourceVersion: gitCommitId,
                      privilegedModeOverride: 'True'

                    if ( currentBuild.currentResult == 'SUCCESS' ) {
                      notifySuccess('dev-notification', "<${env.BUILD_URL}|${env.JOB_NAME} : Storybook test success: ${gitCommitId}, branch: ${branchName}")
                    }
                  } catch (e) {
                    notifyFailure('dev-notification', "<${env.BUILD_URL}|${env.JOB_NAME} :  Storybook test failed: ${gitCommitId}, branch: ${branchName}")
                    throw e
                  }
              }
            }
          }
        }
      }
    }
  }
}

def notifySuccess(channel, message) {
  slackSend channel: channel, color: 'good', message: message
}

def notifyFailure(channel, message) {
  slackSend channel: channel, color: 'danger', message: message
}
