// flow-typed signature: 7ffee93889714c8b74c7eed756596232
// flow-typed version: <<STUB>>/cz-conventional-changelog_v1.1.4/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-conventional-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cz-conventional-changelog/index' {
  declare module.exports: $Exports<'cz-conventional-changelog'>;
}
declare module 'cz-conventional-changelog/index.js' {
  declare module.exports: $Exports<'cz-conventional-changelog'>;
}
