// flow-typed signature: 06db2892b84a1788bafd57e428ef5a45
// flow-typed version: <<STUB>>/dompurify_v^0.8.3/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dompurify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dompurify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dompurify/dist/purify.min' {
  declare module.exports: any;
}

declare module 'dompurify/src/purify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dompurify/dist/purify.min.js' {
  declare module.exports: $Exports<'dompurify/dist/purify.min'>;
}
declare module 'dompurify/src/purify.js' {
  declare module.exports: $Exports<'dompurify/src/purify'>;
}
