// flow-typed signature: b00b05af30d81e220112aa8ac39a3912
// flow-typed version: <<STUB>>/eslint-config-instana_v^3.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-instana'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-instana' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-instana/index' {
  declare module.exports: $Exports<'eslint-config-instana'>;
}
declare module 'eslint-config-instana/index.js' {
  declare module.exports: $Exports<'eslint-config-instana'>;
}
