// flow-typed signature: aaf982826e631c0e0923a505d942b122
// flow-typed version: <<STUB>>/eslint-plugin-mocha_v^1.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-mocha/lib/rules/handle-done-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-exclusive-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-global-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-synchronous-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-mocha/index' {
  declare module.exports: $Exports<'eslint-plugin-mocha'>;
}
declare module 'eslint-plugin-mocha/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha'>;
}
declare module 'eslint-plugin-mocha/lib/rules/handle-done-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/handle-done-callback'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-exclusive-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-exclusive-tests'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-global-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-global-tests'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-synchronous-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-synchronous-tests'>;
}
