// flow-typed signature: dbea6d30b7611f5c55424930401eccd1
// flow-typed version: <<STUB>>/eslint-plugin-instana-import-order_v^1.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-instana-import-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-instana-import-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-instana-import-order/lib/rules/import-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/internal-fixed-in-external' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/multiple-of-each-kind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/not-sorted-no-whitespace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/not-sorted' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/only-local' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/only-third-party' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/sorted-but-no-whitespace' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/files/sorted' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/lib/rules/import-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-instana-import-order/tests/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-instana-import-order/index' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order'>;
}
declare module 'eslint-plugin-instana-import-order/index.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order'>;
}
declare module 'eslint-plugin-instana-import-order/lib/rules/import-order.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/lib/rules/import-order'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/internal-fixed-in-external.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/internal-fixed-in-external'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/multiple-of-each-kind.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/multiple-of-each-kind'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/not-sorted-no-whitespace.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/not-sorted-no-whitespace'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/not-sorted.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/not-sorted'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/only-local.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/only-local'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/only-third-party.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/only-third-party'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/sorted-but-no-whitespace.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/sorted-but-no-whitespace'>;
}
declare module 'eslint-plugin-instana-import-order/tests/files/sorted.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/files/sorted'>;
}
declare module 'eslint-plugin-instana-import-order/tests/lib/rules/import-order.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/lib/rules/import-order'>;
}
declare module 'eslint-plugin-instana-import-order/tests/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-instana-import-order/tests/utils'>;
}
