// flow-typed signature: 2bf2fcd603cc09e098645ee214bf080a
// flow-typed version: <<STUB>>/instana-nodejs-sensor_vnext/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'instana-nodejs-sensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'instana-nodejs-sensor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'instana-nodejs-sensor/src/actions/profiling/cpu' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/actions/source' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/agent/bunyanToAgentStream' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/agent/log' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/agent/opts' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/agent/requestHandler' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/agentConnection' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/applicationUnderMonitoring' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/clone' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/cmdline_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/cmdline' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/compression_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/compression' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/http' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/index' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/logger_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/logger' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/activeHandles_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/activeHandles' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/activeRequests' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/args' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/dependencies_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/dependencies' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/description' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/execArgs' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/gc' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/heapSpaces_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/heapSpaces' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/http' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/keywords' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/libuv' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/memory_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/memory' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/name_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/name' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/optDependencies' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/pid' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/sensorVersion' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/startTime_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/startTime' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/version' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/metrics/versions' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/pidStore_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/pidStore' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/slidingWindow_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/slidingWindow' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/states/agentHostLookup' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/states/agentready' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/states/announced' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/states/unannounced' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/constants' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/hook_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/hook' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/index_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/index' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/instrumentation/elasticsearch' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/instrumentation/httpClient' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/instrumentation/httpServer' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/instrumentation/mongodb' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/tracing/transmission' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/uniq_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/uniq' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/util/atMostOnce_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/util/atMostOnce' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/util/requireHook' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/src/util/stackTrace' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/actions/profiling/cpu_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/actions/source_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/agentCommunication_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/agentStub_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/agentStub' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/agentStubControls' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/express' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressControls' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressElasticsearch' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressElasticsearchControls' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressMongodb' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressMongodbControls' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressProxy' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/apps/expressProxyControls' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/config' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/disabledTracing_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/tracing_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/tracing/elasticsearch_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/tracing/mongodb_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/tracing/stackTraces_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/util/requireHook_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/util/stackTrace_test' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/util/testModuleA' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/util/testModuleB' {
  declare module.exports: any;
}

declare module 'instana-nodejs-sensor/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'instana-nodejs-sensor/src/actions/profiling/cpu.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/actions/profiling/cpu'>;
}
declare module 'instana-nodejs-sensor/src/actions/source.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/actions/source'>;
}
declare module 'instana-nodejs-sensor/src/agent/bunyanToAgentStream.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/agent/bunyanToAgentStream'>;
}
declare module 'instana-nodejs-sensor/src/agent/log.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/agent/log'>;
}
declare module 'instana-nodejs-sensor/src/agent/opts.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/agent/opts'>;
}
declare module 'instana-nodejs-sensor/src/agent/requestHandler.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/agent/requestHandler'>;
}
declare module 'instana-nodejs-sensor/src/agentConnection.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/agentConnection'>;
}
declare module 'instana-nodejs-sensor/src/applicationUnderMonitoring.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/applicationUnderMonitoring'>;
}
declare module 'instana-nodejs-sensor/src/clone.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/clone'>;
}
declare module 'instana-nodejs-sensor/src/cmdline_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/cmdline_test'>;
}
declare module 'instana-nodejs-sensor/src/cmdline.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/cmdline'>;
}
declare module 'instana-nodejs-sensor/src/compression_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/compression_test'>;
}
declare module 'instana-nodejs-sensor/src/compression.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/compression'>;
}
declare module 'instana-nodejs-sensor/src/http.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/http'>;
}
declare module 'instana-nodejs-sensor/src/index.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/index'>;
}
declare module 'instana-nodejs-sensor/src/logger_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/logger_test'>;
}
declare module 'instana-nodejs-sensor/src/logger.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/logger'>;
}
declare module 'instana-nodejs-sensor/src/metrics/activeHandles_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/activeHandles_test'>;
}
declare module 'instana-nodejs-sensor/src/metrics/activeHandles.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/activeHandles'>;
}
declare module 'instana-nodejs-sensor/src/metrics/activeRequests.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/activeRequests'>;
}
declare module 'instana-nodejs-sensor/src/metrics/args.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/args'>;
}
declare module 'instana-nodejs-sensor/src/metrics/dependencies_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/dependencies_test'>;
}
declare module 'instana-nodejs-sensor/src/metrics/dependencies.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/dependencies'>;
}
declare module 'instana-nodejs-sensor/src/metrics/description.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/description'>;
}
declare module 'instana-nodejs-sensor/src/metrics/execArgs.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/execArgs'>;
}
declare module 'instana-nodejs-sensor/src/metrics/gc.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/gc'>;
}
declare module 'instana-nodejs-sensor/src/metrics/heapSpaces_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/heapSpaces_test'>;
}
declare module 'instana-nodejs-sensor/src/metrics/heapSpaces.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/heapSpaces'>;
}
declare module 'instana-nodejs-sensor/src/metrics/http.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/http'>;
}
declare module 'instana-nodejs-sensor/src/metrics/keywords.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/keywords'>;
}
declare module 'instana-nodejs-sensor/src/metrics/libuv.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/libuv'>;
}
declare module 'instana-nodejs-sensor/src/metrics/memory_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/memory_test'>;
}
declare module 'instana-nodejs-sensor/src/metrics/memory.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/memory'>;
}
declare module 'instana-nodejs-sensor/src/metrics/name_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/name_test'>;
}
declare module 'instana-nodejs-sensor/src/metrics/name.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/name'>;
}
declare module 'instana-nodejs-sensor/src/metrics/optDependencies.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/optDependencies'>;
}
declare module 'instana-nodejs-sensor/src/metrics/pid.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/pid'>;
}
declare module 'instana-nodejs-sensor/src/metrics/sensorVersion.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/sensorVersion'>;
}
declare module 'instana-nodejs-sensor/src/metrics/startTime_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/startTime_test'>;
}
declare module 'instana-nodejs-sensor/src/metrics/startTime.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/startTime'>;
}
declare module 'instana-nodejs-sensor/src/metrics/version.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/version'>;
}
declare module 'instana-nodejs-sensor/src/metrics/versions.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/metrics/versions'>;
}
declare module 'instana-nodejs-sensor/src/pidStore_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/pidStore_test'>;
}
declare module 'instana-nodejs-sensor/src/pidStore.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/pidStore'>;
}
declare module 'instana-nodejs-sensor/src/slidingWindow_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/slidingWindow_test'>;
}
declare module 'instana-nodejs-sensor/src/slidingWindow.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/slidingWindow'>;
}
declare module 'instana-nodejs-sensor/src/states/agentHostLookup.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/states/agentHostLookup'>;
}
declare module 'instana-nodejs-sensor/src/states/agentready.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/states/agentready'>;
}
declare module 'instana-nodejs-sensor/src/states/announced.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/states/announced'>;
}
declare module 'instana-nodejs-sensor/src/states/unannounced.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/states/unannounced'>;
}
declare module 'instana-nodejs-sensor/src/tracing/constants.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/constants'>;
}
declare module 'instana-nodejs-sensor/src/tracing/hook_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/hook_test'>;
}
declare module 'instana-nodejs-sensor/src/tracing/hook.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/hook'>;
}
declare module 'instana-nodejs-sensor/src/tracing/index_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/index_test'>;
}
declare module 'instana-nodejs-sensor/src/tracing/index.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/index'>;
}
declare module 'instana-nodejs-sensor/src/tracing/instrumentation/elasticsearch.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/instrumentation/elasticsearch'>;
}
declare module 'instana-nodejs-sensor/src/tracing/instrumentation/httpClient.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/instrumentation/httpClient'>;
}
declare module 'instana-nodejs-sensor/src/tracing/instrumentation/httpServer.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/instrumentation/httpServer'>;
}
declare module 'instana-nodejs-sensor/src/tracing/instrumentation/mongodb.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/instrumentation/mongodb'>;
}
declare module 'instana-nodejs-sensor/src/tracing/transmission.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/tracing/transmission'>;
}
declare module 'instana-nodejs-sensor/src/uniq_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/uniq_test'>;
}
declare module 'instana-nodejs-sensor/src/uniq.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/uniq'>;
}
declare module 'instana-nodejs-sensor/src/util/atMostOnce_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/util/atMostOnce_test'>;
}
declare module 'instana-nodejs-sensor/src/util/atMostOnce.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/util/atMostOnce'>;
}
declare module 'instana-nodejs-sensor/src/util/requireHook.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/util/requireHook'>;
}
declare module 'instana-nodejs-sensor/src/util/stackTrace.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/src/util/stackTrace'>;
}
declare module 'instana-nodejs-sensor/test/actions/profiling/cpu_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/actions/profiling/cpu_test'>;
}
declare module 'instana-nodejs-sensor/test/actions/source_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/actions/source_test'>;
}
declare module 'instana-nodejs-sensor/test/agentCommunication_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/agentCommunication_test'>;
}
declare module 'instana-nodejs-sensor/test/apps/agentStub_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/agentStub_test'>;
}
declare module 'instana-nodejs-sensor/test/apps/agentStub.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/agentStub'>;
}
declare module 'instana-nodejs-sensor/test/apps/agentStubControls.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/agentStubControls'>;
}
declare module 'instana-nodejs-sensor/test/apps/express.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/express'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressControls.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressControls'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressElasticsearch.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressElasticsearch'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressElasticsearchControls.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressElasticsearchControls'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressMongodb.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressMongodb'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressMongodbControls.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressMongodbControls'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressProxy.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressProxy'>;
}
declare module 'instana-nodejs-sensor/test/apps/expressProxyControls.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/apps/expressProxyControls'>;
}
declare module 'instana-nodejs-sensor/test/config.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/config'>;
}
declare module 'instana-nodejs-sensor/test/disabledTracing_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/disabledTracing_test'>;
}
declare module 'instana-nodejs-sensor/test/tracing_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/tracing_test'>;
}
declare module 'instana-nodejs-sensor/test/tracing/elasticsearch_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/tracing/elasticsearch_test'>;
}
declare module 'instana-nodejs-sensor/test/tracing/mongodb_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/tracing/mongodb_test'>;
}
declare module 'instana-nodejs-sensor/test/tracing/stackTraces_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/tracing/stackTraces_test'>;
}
declare module 'instana-nodejs-sensor/test/util/requireHook_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/util/requireHook_test'>;
}
declare module 'instana-nodejs-sensor/test/util/stackTrace_test.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/util/stackTrace_test'>;
}
declare module 'instana-nodejs-sensor/test/util/testModuleA.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/util/testModuleA'>;
}
declare module 'instana-nodejs-sensor/test/util/testModuleB.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/util/testModuleB'>;
}
declare module 'instana-nodejs-sensor/test/utils.js' {
  declare module.exports: $Exports<'instana-nodejs-sensor/test/utils'>;
}
