// flow-typed signature: c4c1e0feabf59f2d8c12a108b476c4c1
// flow-typed version: <<STUB>>/instalog_v^1.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'instalog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'instalog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'instalog/lib/ConsoleAppender' {
  declare module.exports: any;
}

declare module 'instalog/lib/index' {
  declare module.exports: any;
}

declare module 'instalog/lib/Logger' {
  declare module.exports: any;
}

declare module 'instalog/test/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'instalog/lib/ConsoleAppender.js' {
  declare module.exports: $Exports<'instalog/lib/ConsoleAppender'>;
}
declare module 'instalog/lib/index.js' {
  declare module.exports: $Exports<'instalog/lib/index'>;
}
declare module 'instalog/lib/Logger.js' {
  declare module.exports: $Exports<'instalog/lib/Logger'>;
}
declare module 'instalog/test/index_test.js' {
  declare module.exports: $Exports<'instalog/test/index_test'>;
}
