// flow-typed signature: 0d0baa5eec59bf73796b1cd4c3877fb5
// flow-typed version: <<STUB>>/instana-ui-theme_v^1.8.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'instana-ui-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'instana-ui-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'instana-ui-theme/build/translateTheme' {
  declare module.exports: any;
}

declare module 'instana-ui-theme/dist/styleGuide/index' {
  declare module.exports: any;
}

declare module 'instana-ui-theme/styleGuide.webpack.config' {
  declare module.exports: any;
}

declare module 'instana-ui-theme/styleGuide/assets/prism' {
  declare module.exports: any;
}

declare module 'instana-ui-theme/themeConfig/_base' {
  declare module.exports: any;
}

declare module 'instana-ui-theme/themeConfig/day' {
  declare module.exports: any;
}

declare module 'instana-ui-theme/themeConfig/night' {
  declare module.exports: any;
}

// Filename aliases
declare module 'instana-ui-theme/build/translateTheme.js' {
  declare module.exports: $Exports<'instana-ui-theme/build/translateTheme'>;
}
declare module 'instana-ui-theme/dist/styleGuide/index.js' {
  declare module.exports: $Exports<'instana-ui-theme/dist/styleGuide/index'>;
}
declare module 'instana-ui-theme/index' {
  declare module.exports: $Exports<'instana-ui-theme'>;
}
declare module 'instana-ui-theme/index.js' {
  declare module.exports: $Exports<'instana-ui-theme'>;
}
declare module 'instana-ui-theme/styleGuide.webpack.config.js' {
  declare module.exports: $Exports<'instana-ui-theme/styleGuide.webpack.config'>;
}
declare module 'instana-ui-theme/styleGuide/assets/prism.js' {
  declare module.exports: $Exports<'instana-ui-theme/styleGuide/assets/prism'>;
}
declare module 'instana-ui-theme/themeConfig/_base.js' {
  declare module.exports: $Exports<'instana-ui-theme/themeConfig/_base'>;
}
declare module 'instana-ui-theme/themeConfig/day.js' {
  declare module.exports: $Exports<'instana-ui-theme/themeConfig/day'>;
}
declare module 'instana-ui-theme/themeConfig/night.js' {
  declare module.exports: $Exports<'instana-ui-theme/themeConfig/night'>;
}
