// flow-typed signature: af6b40e9b1e6ceb3aabb382e9e2fb40e
// flow-typed version: <<STUB>>/jsdom_v^2.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdom/lib/jsdom' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/documentAdapter' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/documentfeatures' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/domtohtml' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/history' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/htmltodom' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/index' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/location' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/utils' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/Window' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/contextify-shim' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level1/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/events' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/html' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/languages/javascript' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/style' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/ls' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/xpath' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/dom-implementation' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/index' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-filter' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/selectors' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdom/lib/jsdom.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom'>;
}
declare module 'jsdom/lib/jsdom/browser/documentAdapter.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/documentAdapter'>;
}
declare module 'jsdom/lib/jsdom/browser/documentfeatures.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/documentfeatures'>;
}
declare module 'jsdom/lib/jsdom/browser/domtohtml.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/domtohtml'>;
}
declare module 'jsdom/lib/jsdom/browser/history.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/history'>;
}
declare module 'jsdom/lib/jsdom/browser/htmltodom.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/htmltodom'>;
}
declare module 'jsdom/lib/jsdom/browser/index.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/index'>;
}
declare module 'jsdom/lib/jsdom/browser/location.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/location'>;
}
declare module 'jsdom/lib/jsdom/browser/utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/utils'>;
}
declare module 'jsdom/lib/jsdom/browser/Window.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/Window'>;
}
declare module 'jsdom/lib/jsdom/contextify-shim.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/contextify-shim'>;
}
declare module 'jsdom/lib/jsdom/level1/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level1/core'>;
}
declare module 'jsdom/lib/jsdom/level2/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/core'>;
}
declare module 'jsdom/lib/jsdom/level2/events.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/events'>;
}
declare module 'jsdom/lib/jsdom/level2/html.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/html'>;
}
declare module 'jsdom/lib/jsdom/level2/languages/javascript.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/languages/javascript'>;
}
declare module 'jsdom/lib/jsdom/level2/style.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/style'>;
}
declare module 'jsdom/lib/jsdom/level3/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/core'>;
}
declare module 'jsdom/lib/jsdom/level3/ls.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/ls'>;
}
declare module 'jsdom/lib/jsdom/level3/xpath.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/xpath'>;
}
declare module 'jsdom/lib/jsdom/living/dom-implementation.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/dom-implementation'>;
}
declare module 'jsdom/lib/jsdom/living/index.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/index'>;
}
declare module 'jsdom/lib/jsdom/living/node-filter.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-filter'>;
}
declare module 'jsdom/lib/jsdom/living/node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node'>;
}
declare module 'jsdom/lib/jsdom/living/selectors.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/selectors'>;
}
declare module 'jsdom/lib/jsdom/utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/utils'>;
}
