// flow-typed signature: 2711df1b4a2255dbec0fc8ed81749dbd
// flow-typed version: <<STUB>>/koijs_v^0.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koijs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koijs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koijs/build/koi' {
  declare module.exports: any;
}

declare module 'koijs/target/assets/bundle/index' {
  declare module.exports: any;
}

declare module 'koijs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koijs/build/koi.js' {
  declare module.exports: $Exports<'koijs/build/koi'>;
}
declare module 'koijs/target/assets/bundle/index.js' {
  declare module.exports: $Exports<'koijs/target/assets/bundle/index'>;
}
declare module 'koijs/webpack.config.js' {
  declare module.exports: $Exports<'koijs/webpack.config'>;
}
