// flow-typed signature: ced36720c9ed06592cb8ebebc63ed47c
// flow-typed version: <<STUB>>/markdown-it-link-target_v^1.0.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-link-target'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-link-target' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'markdown-it-link-target/index' {
  declare module.exports: $Exports<'markdown-it-link-target'>;
}
declare module 'markdown-it-link-target/index.js' {
  declare module.exports: $Exports<'markdown-it-link-target'>;
}
