// flow-typed signature: 558759ccd0ea004f1bddf8ad708dbb93
// flow-typed version: <<STUB>>/meta-marked-loader_v1.1.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meta-marked-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'meta-marked-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'meta-marked-loader/index' {
  declare module.exports: $Exports<'meta-marked-loader'>;
}
declare module 'meta-marked-loader/index.js' {
  declare module.exports: $Exports<'meta-marked-loader'>;
}
