// flow-typed signature: e7ea997a2a65d44b5e51c049b15fb188
// flow-typed version: <<STUB>>/npm-check-updates_v2.5.6/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-check-updates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-check-updates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-check-updates/lib/npm-check-updates' {
  declare module.exports: any;
}

declare module 'npm-check-updates/lib/package-managers/bower' {
  declare module.exports: any;
}

declare module 'npm-check-updates/lib/package-managers/npm' {
  declare module.exports: any;
}

declare module 'npm-check-updates/lib/raw-promisify' {
  declare module.exports: any;
}

declare module 'npm-check-updates/lib/version-util' {
  declare module.exports: any;
}

declare module 'npm-check-updates/lib/versionmanager' {
  declare module.exports: any;
}

declare module 'npm-check-updates/test/individual/test-package-managers' {
  declare module.exports: any;
}

declare module 'npm-check-updates/test/test-ncu' {
  declare module.exports: any;
}

declare module 'npm-check-updates/test/test-version-util' {
  declare module.exports: any;
}

declare module 'npm-check-updates/test/test-versionmanager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-check-updates/lib/npm-check-updates.js' {
  declare module.exports: $Exports<'npm-check-updates/lib/npm-check-updates'>;
}
declare module 'npm-check-updates/lib/package-managers/bower.js' {
  declare module.exports: $Exports<'npm-check-updates/lib/package-managers/bower'>;
}
declare module 'npm-check-updates/lib/package-managers/npm.js' {
  declare module.exports: $Exports<'npm-check-updates/lib/package-managers/npm'>;
}
declare module 'npm-check-updates/lib/raw-promisify.js' {
  declare module.exports: $Exports<'npm-check-updates/lib/raw-promisify'>;
}
declare module 'npm-check-updates/lib/version-util.js' {
  declare module.exports: $Exports<'npm-check-updates/lib/version-util'>;
}
declare module 'npm-check-updates/lib/versionmanager.js' {
  declare module.exports: $Exports<'npm-check-updates/lib/versionmanager'>;
}
declare module 'npm-check-updates/test/individual/test-package-managers.js' {
  declare module.exports: $Exports<'npm-check-updates/test/individual/test-package-managers'>;
}
declare module 'npm-check-updates/test/test-ncu.js' {
  declare module.exports: $Exports<'npm-check-updates/test/test-ncu'>;
}
declare module 'npm-check-updates/test/test-version-util.js' {
  declare module.exports: $Exports<'npm-check-updates/test/test-version-util'>;
}
declare module 'npm-check-updates/test/test-versionmanager.js' {
  declare module.exports: $Exports<'npm-check-updates/test/test-versionmanager'>;
}
