// flow-typed signature: 34a79310f5fe0e28df6a6c14523f1c0b
// flow-typed version: <<STUB>>/proxrox_v^1.12.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proxrox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'proxrox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proxrox/bin/proxrox' {
  declare module.exports: any;
}

declare module 'proxrox/examples/inquirerDevModeWithWebpack/build/dev' {
  declare module.exports: any;
}

declare module 'proxrox/examples/inquirerDevModeWithWebpack/build/questions' {
  declare module.exports: any;
}

declare module 'proxrox/examples/inquirerDevModeWithWebpack/build/webpackConfigGenerator' {
  declare module.exports: any;
}

declare module 'proxrox/examples/inquirerDevModeWithWebpack/client/index' {
  declare module.exports: any;
}

declare module 'proxrox/examples/inquirerDevModeWithWebpack/server/index' {
  declare module.exports: any;
}

declare module 'proxrox/lib/config_generator' {
  declare module.exports: any;
}

declare module 'proxrox/lib/config_loader' {
  declare module.exports: any;
}

declare module 'proxrox/lib/control' {
  declare module.exports: any;
}

declare module 'proxrox/lib/index' {
  declare module.exports: any;
}

declare module 'proxrox/lib/install' {
  declare module.exports: any;
}

declare module 'proxrox/lib/util' {
  declare module.exports: any;
}

declare module 'proxrox/test/config_generator_test' {
  declare module.exports: any;
}

declare module 'proxrox/test/config_loader_test' {
  declare module.exports: any;
}

declare module 'proxrox/test/install_test' {
  declare module.exports: any;
}

declare module 'proxrox/test/support' {
  declare module.exports: any;
}

declare module 'proxrox/test/util_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proxrox/bin/proxrox.js' {
  declare module.exports: $Exports<'proxrox/bin/proxrox'>;
}
declare module 'proxrox/examples/inquirerDevModeWithWebpack/build/dev.js' {
  declare module.exports: $Exports<'proxrox/examples/inquirerDevModeWithWebpack/build/dev'>;
}
declare module 'proxrox/examples/inquirerDevModeWithWebpack/build/questions.js' {
  declare module.exports: $Exports<'proxrox/examples/inquirerDevModeWithWebpack/build/questions'>;
}
declare module 'proxrox/examples/inquirerDevModeWithWebpack/build/webpackConfigGenerator.js' {
  declare module.exports: $Exports<'proxrox/examples/inquirerDevModeWithWebpack/build/webpackConfigGenerator'>;
}
declare module 'proxrox/examples/inquirerDevModeWithWebpack/client/index.js' {
  declare module.exports: $Exports<'proxrox/examples/inquirerDevModeWithWebpack/client/index'>;
}
declare module 'proxrox/examples/inquirerDevModeWithWebpack/server/index.js' {
  declare module.exports: $Exports<'proxrox/examples/inquirerDevModeWithWebpack/server/index'>;
}
declare module 'proxrox/lib/config_generator.js' {
  declare module.exports: $Exports<'proxrox/lib/config_generator'>;
}
declare module 'proxrox/lib/config_loader.js' {
  declare module.exports: $Exports<'proxrox/lib/config_loader'>;
}
declare module 'proxrox/lib/control.js' {
  declare module.exports: $Exports<'proxrox/lib/control'>;
}
declare module 'proxrox/lib/index.js' {
  declare module.exports: $Exports<'proxrox/lib/index'>;
}
declare module 'proxrox/lib/install.js' {
  declare module.exports: $Exports<'proxrox/lib/install'>;
}
declare module 'proxrox/lib/util.js' {
  declare module.exports: $Exports<'proxrox/lib/util'>;
}
declare module 'proxrox/test/config_generator_test.js' {
  declare module.exports: $Exports<'proxrox/test/config_generator_test'>;
}
declare module 'proxrox/test/config_loader_test.js' {
  declare module.exports: $Exports<'proxrox/test/config_loader_test'>;
}
declare module 'proxrox/test/install_test.js' {
  declare module.exports: $Exports<'proxrox/test/install_test'>;
}
declare module 'proxrox/test/support.js' {
  declare module.exports: $Exports<'proxrox/test/support'>;
}
declare module 'proxrox/test/util_test.js' {
  declare module.exports: $Exports<'proxrox/test/util_test'>;
}
