// flow-typed signature: 849780027e7543e6d21d20f248fb2f23
// flow-typed version: <<STUB>>/reactive-observables_v^1.32.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactive-observables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactive-observables' {
  declare module.exports: any;
}
