// flow-typed signature: 711243cc94ef4947ba70d7af64faa8ba
// flow-typed version: <<STUB>>/react-toggle_v2.1.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toggle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toggle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toggle/check' {
  declare module.exports: any;
}

declare module 'react-toggle/x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toggle/check.js' {
  declare module.exports: $Exports<'react-toggle/check'>;
}
declare module 'react-toggle/index' {
  declare module.exports: $Exports<'react-toggle'>;
}
declare module 'react-toggle/index.js' {
  declare module.exports: $Exports<'react-toggle'>;
}
declare module 'react-toggle/x.js' {
  declare module.exports: $Exports<'react-toggle/x'>;
}
