// flow-typed signature: 8904084a93fd3ea24daeb8a8281f3cb4
// flow-typed version: <<STUB>>/react-immutable-proptypes_v^2.1.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-immutable-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-immutable-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-immutable-proptypes/dist/ImmutablePropTypes' {
  declare module.exports: any;
}

declare module 'react-immutable-proptypes/src/ImmutablePropTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-immutable-proptypes/dist/ImmutablePropTypes.js' {
  declare module.exports: $Exports<'react-immutable-proptypes/dist/ImmutablePropTypes'>;
}
declare module 'react-immutable-proptypes/src/ImmutablePropTypes.js' {
  declare module.exports: $Exports<'react-immutable-proptypes/src/ImmutablePropTypes'>;
}
