// flow-typed signature: 5d0f8ec33df47ec7cb9b0758cee04b85
// flow-typed version: <<STUB>>/roemitter_v^2.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roemitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'roemitter' {
  declare module.exports: any;
}
