// flow-typed signature: ea07e3fe7a13996d356789bb283511c5
// flow-typed version: <<STUB>>/tween.js_v^15.0.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tween.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tween.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tween.js/build/tween.min' {
  declare module.exports: any;
}

declare module 'tween.js/examples/js/createGraph' {
  declare module.exports: any;
}

declare module 'tween.js/examples/js/RequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'tween.js/examples/js/stats.min' {
  declare module.exports: any;
}

declare module 'tween.js/gulpfile' {
  declare module.exports: any;
}

declare module 'tween.js/src/Tween' {
  declare module.exports: any;
}

declare module 'tween.js/test/unit/nodeunitheadless' {
  declare module.exports: any;
}

declare module 'tween.js/test/unit/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tween.js/build/tween.min.js' {
  declare module.exports: $Exports<'tween.js/build/tween.min'>;
}
declare module 'tween.js/examples/js/createGraph.js' {
  declare module.exports: $Exports<'tween.js/examples/js/createGraph'>;
}
declare module 'tween.js/examples/js/RequestAnimationFrame.js' {
  declare module.exports: $Exports<'tween.js/examples/js/RequestAnimationFrame'>;
}
declare module 'tween.js/examples/js/stats.min.js' {
  declare module.exports: $Exports<'tween.js/examples/js/stats.min'>;
}
declare module 'tween.js/gulpfile.js' {
  declare module.exports: $Exports<'tween.js/gulpfile'>;
}
declare module 'tween.js/src/Tween.js' {
  declare module.exports: $Exports<'tween.js/src/Tween'>;
}
declare module 'tween.js/test/unit/nodeunitheadless.js' {
  declare module.exports: $Exports<'tween.js/test/unit/nodeunitheadless'>;
}
declare module 'tween.js/test/unit/tests.js' {
  declare module.exports: $Exports<'tween.js/test/unit/tests'>;
}
