/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2024
 */

import deserializeErrorMessage from 'in-synthetics/utils/deserializeErrorMessage';

// Generated by WCA for GP

// Test 1: Check if the function returns an string type error message.
test('deserializeErrorMessage returns an error message', () => {
  const dummyResponse: string = `Unable to process JSON: {"errors":["Test Id my%20id%20123 does not exist"]}`;
  expect(deserializeErrorMessage(dummyResponse)).toEqual(`Test Id my%20id%20123 does not exist`);
});
