/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

import hasEmptyStrings from 'in-synthetics/utils/hasEmptyStrings';

// Generated by WCA for GP

describe('hasEmptyStrings', () => {
  it('should return true if the object has an empty string', () => {
    const obj = {
      name: 'John',
      age: '',
      location: 'New York'
    };
    expect(hasEmptyStrings(obj)).toBe(true);
  });

  it('should return true if the object has an empty key', () => {
    const obj = {
      '': 'John',
      age: '30',
      location: 'New York'
    };
    expect(hasEmptyStrings(obj)).toBe(true);
  });

  it('should return true if the object has an empty string and an empty key', () => {
    const obj = {
      '': 'John',
      age: '',
      location: 'New York'
    };
    expect(hasEmptyStrings(obj)).toBe(true);
  });

  it('should return true if the single property has an empty string and an empty key ', () => {
    const obj = {
      '': ''
    };
    expect(hasEmptyStrings(obj)).toBe(true);
  });

  it('should return false if the object does not have any empty strings', () => {
    const obj = {
      name: 'John',
      age: '30',
      location: 'New York'
    };
    expect(hasEmptyStrings(obj)).toBe(false);
  });
});
