/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2024
 */

import isBrowserTestType from 'in-synthetics/utils/isBrowserTestType';

// Generated by WCA for GP
// This function checks if the given test type is a browser test type.
// Browser test types are defined in the `browserTests` array.

// Test that the `isBrowserTestType` function returns true for browser test types.
test('returns true for browser test types', () => {
  expect(isBrowserTestType('WebpageScript')).toBe(true);
  expect(isBrowserTestType('WebpageAction')).toBe(true);
  expect(isBrowserTestType('BrowserScript')).toBe(true);
});

// Test that the `isBrowserTestType` function returns false for non-browser test types.
test('returns false for non-browser test types', () => {
  expect(isBrowserTestType('HttpScript')).toBe(false);
  expect(isBrowserTestType('HttpAction')).toBe(false);
});
