/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

// Generated by WCA for GP
import { massageLocationDisplayLabel } from 'in-synthetics/utils/massageLocationDisplayLabel';

describe('massageLocationDisplayLabel', () => {
  it('returns the display label if it is not empty', () => {
    const displayLabel = 'Test Location';
    const id = 'test-location';
    const result = massageLocationDisplayLabel(displayLabel, id);
    expect(result).toBe(displayLabel);
  });

  it('returns the id with the word "deleted" appended if the display label is empty', () => {
    const displayLabel = '';
    const id = 'test-location';
    const result = massageLocationDisplayLabel(displayLabel, id);
    expect(result).toBe(`${id}-deleted`);
  });
});
