/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

// Generated by WCA for GP
import { validate } from 'in-synthetics/utils/scriptUploader';

describe('scriptUploader', () => {
  it('should return an empty array if there are no errors', () => {
    const code = 'const x = 1;';
    const errors = validate(code);
    expect(errors).toEqual([]);
  });

  it('should return an array of errors if there are syntax errors', () => {
    const code = 'const x = 1; const y = 2; const z = ';
    const errors = validate(code);
    expect(errors).toEqual([
      {
        code: 'VALIDATION',
        message: 'Unexpected end of input(line number: 1, column number: 37)'
      }
    ]);
  });

  it('should return an array of errors if there are ilegal tokens', () => {
    const code = 'const x = 1; \\';
    const errors = validate(code);
    expect(errors).toEqual([
      {
        code: 'VALIDATION',
        message: 'Unexpected token ILLEGAL(line number: 1, column number: 15)'
      }
    ]);
  });

  it('should return an array of errors if the script is empty', () => {
    const code = '';
    const errors = validate(code);
    expect(errors).toEqual([
      {
        code: 'VALIDATION',
        message: 'Empty code. Nothing to validate.'
      }
    ]);
  });
});
