/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

// Generated by WCA for GP
import { getSyntheticType, getDisplayType } from 'in-synthetics/utils/syntheticTypeMap';

describe('getSyntheticType()', () => {
  it('should convert display type to synthetic type', () => {
    expect(getSyntheticType('API Simple')).toBe('HTTPAction');
    expect(getSyntheticType('API Script')).toBe('HTTPScript');
    expect(getSyntheticType('Webpage Simple')).toBe('WebpageAction');
    expect(getSyntheticType('Webpage Script')).toBe('WebpageScript');
    expect(getSyntheticType('Browser Script')).toBe('BrowserScript');
    expect(getSyntheticType('DNS')).toBe('DNS');
    expect(getSyntheticType('Other')).toBe('Other');
  });
});

describe('getDisplayType()', () => {
  it('should convert synthetic type to display type', () => {
    expect(getDisplayType('HTTPAction')).toBe('API Simple');
    expect(getDisplayType('HTTPScript')).toBe('API Script');
    expect(getDisplayType('WebpageAction')).toBe('Webpage Simple');
    expect(getDisplayType('WebpageScript')).toBe('Webpage Script');
    expect(getDisplayType('BrowserScript')).toBe('Browser Script');
    expect(getDisplayType('DNS')).toBe('DNS');
    expect(getDisplayType('Other')).toBe('Other');
  });
});
