/*
 * (c) Copyright IBM Corp. 2022
 * (c) Copyright Instana Inc. 2022
 */

// the keys (not the values) need to be kept in sync with
// in-services/featureFlags
module.exports = {
  agentMonitoringIssuesEnabled: true,
  applicationSmartAlertsEnabled: true,
  containerInfoEnabled: true,
  entityCountWidgetEnabled: true,
  infraMetricsWidgetEnabled: true,
  infraExplorePresentationEnabled: true,
  infraExploreDataEnabled: true,
  beeInstanaInfraMetricsEnabled: true,
  highResolutionInfrastructureMetricsEnabled: true,
  internalMonitoringUnit: true,
  enableTroubleshootingMode: true,
  isSelfService: false,
  isUsageInfoPopupEnabled: false,
  latencyDistributionBase10Enabled: true,
  maintenanceNotesEnabled: false,
  newApCreationEnabled: true,
  onPremLicenseInformationEnabled: false,
  pcfEnabled: true,
  phmcEnabled: true,
  releaseNotesEnabled: true,
  routeIdOverPathTplEnabled: false,
  skipOnboardingDialog: false,
  tenantSwitcherEnabled: true,
  useInstanaSaasEumTrackingUrlEnabled: true,
  vsphereEnabled: true,
  openstackEnabled: true,
  zhmcEnabled: true,
  websiteUserBreakdownEnabled: true,
  ampCompanyInfoEnabled: true,
  ampEnabled: true,
  persistentVolumeSupportEnabled: true,
  loggingEnabled: true,
  pseudoLanguageEnabled: true,
  syntheticCallsEnabled: true,
  applicationHealthOverviewEnabled: true,
  openFacetedSearchByDefault: true,
  agentInstallViewRestrictedToIBMSaas: false,
  traceDetailViewV2Enabled: false,
  deprecateAppDataLegacyEventsEnabled: true,
  disallowAppDataLegacyEventsEnabled: false,
  hideAppDataLegacyEventsEnabled: false,
  potentialProblemsEnabled: true,
  builtInGlobalApplicationSmartAlertsEnabled: true,
  websiteSloEnabled: true,
  perEndpointAdaptiveBaselineEnabled: false,
  websiteSmartAlertsAdaptiveBaselineEnabled: true,
  smartAlertsLogsBlueprintEnabled: true,
  syntheticsTestEnabled: true,
  kubernetesExploreEnabled: true,
  kubernetesTeamEnabled: true,
  configMigrationFeatureEnabled: true,
  sliCHClusterAccessEnabled: true,
  perSecondAggregationEnabled: false,
  apdexWidgetEnabled: true,
  applicationApdexEnabled: true,
  actionAutomationEnabled: true,
  websiteUploadConfigEnabled: true,
  pluginMetricStatisticsEnabled: true,
  mobileAppCrashBeaconEnabled: true,
  k8sTimeShiftEnabled: true,
  syntheticBrowserScriptEnabled: true,
  websiteBeaconQueryOptimizationEnabled: true
};
