// the keys (not the values) need to be kept in sync with
// packages/in-server/services/resolvers/consul.js
module.exports = {
  isSelfService: false,
  releaseNotesEnabled: true,
  maintenanceNotesEnabled: false,
  useInstanaSaasEumTrackingUrlEnabled: true,
  tenantSwitcherEnabled: true,
  isUsageInfoPopupEnabled: false,
  onPremLicenseInformationEnabled: false,
  customEventsInWebsiteMonitoringEnabled: true,
  ruleDeprecationValidationChecksEnabled: true,
  containerInfoEnabled: true,
  trackUrlPathChanges: true,
  internalMonitoringUnit: true,
  isRbacEnabled: true,
  samplingIndicatorEnabled: true,
  isAdhocMetricAggregationEnabled: true,
  customDashboardsEnabled: true,
  pcfEnabled: true,
  logDnaEnabled: true,
  websiteUserBreakdownEnabled: true,
  fullTermsConfigEnabled: true,
  isOnboardingGuideEnabled: true,
  contextGuideEnabled: false,
  eumAlertingEnabled: true,
  googleAnalyticsDisabled: false,
  vsphereEnabled: true,
  profilingEnabled: true,
  mobileAppMonitoringEnabled: true
};
