/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

import { number, millis, percentagePlainZeroDecimalPlaces } from 'in-services/formatters/number';
import { t } from 'in-i18n';

export default [
  {
    metrics: [
      'metrics.Availability.ABAP_Central_Service_Availability.ABAP_SCS_MESSAGE_SERVER_STATUS.value',
      'metrics.Availability.ABAP_Instance_Availability.ABAP_INSTANCE_LOCAL_HTTP_AVAIL_Instance_Local_Http_Availability.value',
      'metrics.Availability.Connectivity_from_Java_to_ABAP.VMC_JAVA_TO_ABAP.value',
      'metrics.Availability.Connectivtity_from_ABAP_to_Java.VMC_ABAP_TO_JAVA.value',
      'metrics.Availability.High_number_of_ABAP_System_Log_Messages.RECEIVING_STATUS_FROM_HOST.value',
      'metrics.Availability.Instance_Availability.ABAP_INSTANCE_AVAILABILITY.value',
      'metrics.Availability.Instance_Availability.ABAP_INSTANCE_STATUS.value',
      'metrics.Availability.Instance_Availability.ABAP_LOCAL_RFC_AVAILABILITY.value',
      'metrics.Availability.Instance_Local_Logon_Test.ABAP_LOCAL_LOGON_TEST.value',
      'metrics.Availability.Instance_Status.ABAP_INSTANCE_STATUS_REMOTE.value',
      'metrics.Exceptions.ABAP_Short_Dumps.ABAP_INST_SHORTDUMPS_ABAP_Short_Dumps.value',
      'metrics.Exceptions.ABAP_Short_Dumps.ABAP_SHORTDUMP_FREQ.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS_ABAP_Client_eq_000.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS_ABAP_Client_eq_001.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS_ABAP_Client_eq_066.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS_ABAP_Client_eq_400.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS_ABAP_Client_eq_500.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_CLIENT_USERS_Number_of_Dialog_Users_in_Client.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_DIALOG_USERS.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_HTTP_USERS.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_RFC_USERS.value',
      'metrics.Performance.ABAP_User_Load.ABAP_INST_TOTAL_USERS.value',
      'metrics.Performance.ABAP_User_Load.HIGH_USER_LOAD.value',
      'metrics.Performance.Batch_Resources.ABAP_INST_BTC_QUEUE_LENGTH.value',
      'metrics.Performance.Batch_Resources.ABAP_INST_BTC_WP_FREE.value',
      'metrics.Performance.Batch_Resources.ABAP_INST_BTC_WP_STOPPED.value',
      'metrics.Performance.Dialog_Resources.ABAP_INST_DIALOG_LONGRUNNING.value',
      'metrics.Performance.Dialog_Resources.DIALOG_RESOURCES.value',
      'metrics.Performance.Dialog_Response_Time.NUMBER_OF_DIALOG_STEPS_PER_MIN.value',
      'metrics.Performance.Gateway_Resources.GATEWAY_RESOURCES.value',
      'metrics.Performance.High_number_of_ABAP_System_Log_Messages.RECEIVING_STATUS_FROM_HOST.value',
      'metrics.Performance.ICM_Resources.ICM_RESOURCES.value',
      'metrics.Performance.ICM_Resources.NUMBER_OF_ICM_CONNECTIONS.value',
      'metrics.Performance.ICM_Resources.NUMBER_OF_ICM_REQUESTS_IN_QUEU.value',
      'metrics.Performance.ICM_Resources.NUMBER_OF_ICM_THREADS.value',
      'metrics.Performance.Memory.MEMORY.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Buffer_name_eq_CUA_db_Key_Figure_eq_Swaps.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Buffer_name_eq_Nametab_Field_definition_db_Key_Figure_eq_Swaps.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Buffer_name_eq_Nametab_Short_db_Key_Figure_eq_Swaps.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Buffer_name_eq_Program_db_Key_Figure_eq_Swaps.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Buffer_name_eq_Table_Generic_key_db_Key_Figure_eq_Swaps.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Buffer_name_eq_Table_Single_record_db_Key_Figure_eq_Swaps.value',
      'metrics.Performance.Memory.NUMBER_OF_BUFFER_SWAPS_Number_of_buffer_swaps.value',
      'metrics.Performance.Spool_Resources.SPOOL_RESOURCES.value',
      'metrics.Performance.Spool_Resources.SPOOL_WORK_PROCESSES_STOPPED.value',
      'metrics.Performance.Update_Resources.UPDATE1_WORK_PROCESSES_STOPPED.value',
      'metrics.Performance.Update_Resources.UPDATE2_WORK_PROCESSES_STOPPED.value',
      'metrics.Performance.Update_Resources.UPDATE_RESSOURCES.value'
    ],
    labels: [
      t('in-forge:plugins.abapInstance.centralService'),
      t('in-forge:plugins.abapInstance.instanceAvail'),
      t('in-forge:plugins.abapInstance.javaToAbap'),
      t('in-forge:plugins.abapInstance.abapToJava'),
      t('in-forge:plugins.abapInstance.receiveStatus'),
      t('in-forge:plugins.abapInstance.instanceAvailability'),
      t('in-forge:plugins.abapInstance.instanceStatus'),
      t('in-forge:plugins.abapInstance.localRFC'),
      t('in-forge:plugins.abapInstance.localLogonTest'),
      t('in-forge:plugins.abapInstance.instanceStatusRemote'),
      t('in-forge:plugins.abapInstance.abapShortDumps'),
      t('in-forge:plugins.abapInstance.abapShortDumpsFreq'),
      t('in-forge:plugins.abapInstance.dialogClientUsers'),
      t('in-forge:plugins.abapInstance.abapClienteq000'),
      t('in-forge:plugins.abapInstance.abapClienteq001'),
      t('in-forge:plugins.abapInstance.abapClienteq066'),
      t('in-forge:plugins.abapInstance.abapClienteq400'),
      t('in-forge:plugins.abapInstance.abapClienteq500'),
      t('in-forge:plugins.abapInstance.noDialogUsersClient'),
      t('in-forge:plugins.abapInstance.instDialogUsers'),
      t('in-forge:plugins.abapInstance.intHttpUsers'),
      t('in-forge:plugins.abapInstance.intRFCUsers'),
      t('in-forge:plugins.abapInstance.intTotalUsers'),
      t('in-forge:plugins.abapInstance.highUserLoad'),
      t('in-forge:plugins.abapInstance.instBTCQueueLength'),
      t('in-forge:plugins.abapInstance.instBTCWPFree'),
      t('in-forge:plugins.abapInstance.instBTCWPStopped'),
      t('in-forge:plugins.abapInstance.instDialogLongRunning'),
      t('in-forge:plugins.abapInstance.dialogResources'),
      t('in-forge:plugins.abapInstance.noOfdialogStepsPerMin'),
      t('in-forge:plugins.abapInstance.gatewayResources'),
      t('in-forge:plugins.abapInstance.statusFromHost'),
      t('in-forge:plugins.abapInstance.iCMResources'),
      t('in-forge:plugins.abapInstance.noICMConnections'),
      t('in-forge:plugins.abapInstance.noICMReq'),
      t('in-forge:plugins.abapInstance.noICMThreads'),
      t('in-forge:plugins.abapInstance.memory'),
      t('in-forge:plugins.abapInstance.memoryCUADb'),
      t('in-forge:plugins.abapInstance.memoryNametab'),
      t('in-forge:plugins.abapInstance.memoryNametabShort'),
      t('in-forge:plugins.abapInstance.memoryProgramDb'),
      t('in-forge:plugins.abapInstance.memoryTableGeneric'),
      t('in-forge:plugins.abapInstance.memoryTableSingle'),
      t('in-forge:plugins.abapInstance.memoryNoOfBufferSwaps'),
      t('in-forge:plugins.abapInstance.spoolResources'),
      t('in-forge:plugins.abapInstance.wPStopped'),
      t('in-forge:plugins.abapInstance.update1WPStopped'),
      t('in-forge:plugins.abapInstance.update2WPStopped'),
      t('in-forge:plugins.abapInstance.updateResources')
    ],
    min: 0,
    formatter: number.compact
  },
  {
    metrics: [
      'metrics.Performance.Dialog_Response_Time.DIALOG_DB_REQUEST_TIME.value',
      'metrics.Performance.Dialog_Response_Time.DIALOG_FRONTEND_NETWORK_TIME.value',
      'metrics.Performance.Dialog_Response_Time.DIALOG_FRONTEND_RESPONSE_TIME.value',
      'metrics.Performance.Dialog_Response_Time.DIALOG_LOAD_+_GENERATION_TIME.value',
      'metrics.Performance.Dialog_Response_Time.DIALOG_STANDARDIZED_RESPONSE_T.value'
    ],
    labels: [
      t('in-forge:plugins.abapInstance.dialogDBReqTime'),
      t('in-forge:plugins.abapInstance.dialogNetworkTime'),
      t('in-forge:plugins.abapInstance.dialogRespTime'),
      t('in-forge:plugins.abapInstance.dialogLoadGenTime'),
      t('in-forge:plugins.abapInstance.dialogStandardRespTime')
    ],
    min: 0,
    formatter: millis
  },
  {
    metrics: [
      'metrics.Performance.Gateway_Resources.GATEWAY_CLIENT_USAGE__ob_%_cb_.value',
      'metrics.Performance.Gateway_Resources.GATEWAY_CONNECTION_USAGE__ob_%_cb_.value',
      'metrics.Performance.Gateway_Resources.REMOTE_GATWAYS_USAGE__ob_%_cb_.value',
      'metrics.Performance.ICM_Resources.ABAP_INST_ICM_CONN_USAGE.value',
      'metrics.Performance.ICM_Resources.ABAP_INST_ICM_REQUEST_USAGE.value',
      'metrics.Performance.ICM_Resources.ABAP_INST_ICM_THREAD_USAGE.value',
      'metrics.Performance.Memory.ABAP_INST_MEMORY_EM_USED.value',
      'metrics.Performance.Memory.ABAP_INST_MEMORY_HEAP_USED.value',
      'metrics.Performance.Memory.ABAP_INST_MEMORY_PAGING_AREA_USED.value',
      'metrics.Performance.Memory.ABAP_INST_MEMORY_ROLL_AREA_USED.value',
      'metrics.Performance.Spool_Resources.ABAP_INST_SPOOL_WP_UTILIZATION.value',
      'metrics.Performance.Update_Resources.UPDATE1_QUEUE_UTILIZATION.value',
      'metrics.Performance.Update_Resources.UPDATE2_QUEUE_UTILIZATION.value'
    ],
    labels: [
      t('in-forge:plugins.abapInstance.gatewayClientUsage'),
      t('in-forge:plugins.abapInstance.gatewayConnectionUsage'),
      t('in-forge:plugins.abapInstance.remoteGatewayUsage'),
      t('in-forge:plugins.abapInstance.iCMConnectionUsage'),
      t('in-forge:plugins.abapInstance.iCMReqUsage'),
      t('in-forge:plugins.abapInstance.iCMThreadUsage'),
      t('in-forge:plugins.abapInstance.memoryUsed'),
      t('in-forge:plugins.abapInstance.memoryHeapUsed'),
      t('in-forge:plugins.abapInstance.memoryPagingUsed'),
      t('in-forge:plugins.abapInstance.memoryRollUsed'),
      t('in-forge:plugins.abapInstance.spoolUtil'),
      t('in-forge:plugins.abapInstance.update1QueueUtil'),
      t('in-forge:plugins.abapInstance.update2QueueUtil')
    ],
    min: 0,
    formatter: percentagePlainZeroDecimalPlaces
  }
];
