const MARGIN = 0.025;
const NORMALIZED_POS_WITH_MARGIN = 0.5 + MARGIN;

const VERTICES = [
  // front
  -NORMALIZED_POS_WITH_MARGIN, 0, -NORMALIZED_POS_WITH_MARGIN,
  -NORMALIZED_POS_WITH_MARGIN, 0, NORMALIZED_POS_WITH_MARGIN,

  -NORMALIZED_POS_WITH_MARGIN, 0, NORMALIZED_POS_WITH_MARGIN,
  NORMALIZED_POS_WITH_MARGIN, 0, NORMALIZED_POS_WITH_MARGIN,

  // sides
  NORMALIZED_POS_WITH_MARGIN, 0, NORMALIZED_POS_WITH_MARGIN,
  NORMALIZED_POS_WITH_MARGIN, 1, NORMALIZED_POS_WITH_MARGIN,

  -NORMALIZED_POS_WITH_MARGIN, 0, -NORMALIZED_POS_WITH_MARGIN,
  -NORMALIZED_POS_WITH_MARGIN, 1, -NORMALIZED_POS_WITH_MARGIN,

  // top
  -NORMALIZED_POS_WITH_MARGIN, 1, -NORMALIZED_POS_WITH_MARGIN,
  NORMALIZED_POS_WITH_MARGIN, 1, -NORMALIZED_POS_WITH_MARGIN,

  NORMALIZED_POS_WITH_MARGIN, 1, -NORMALIZED_POS_WITH_MARGIN,
  NORMALIZED_POS_WITH_MARGIN, 1, NORMALIZED_POS_WITH_MARGIN
];

const COLORS = [
  1, 1, 1,
  1, 1, 1,

  1, 1, 1,
  1, 1, 1,

  1, 1, 1,
  1, 1, 1,

  1, 1, 1,
  1, 1, 1,

  1, 1, 1,
  1, 1, 1,

  1, 1, 1,
  1, 1, 1
];

const contentProvider = {
  getVertices: () => {
    return VERTICES;
  },

  getColors: () => {
    return COLORS;
  }
};

export default contentProvider;
