/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */
import internetExplorer from '@browser-logos/internet-explorer-tile_10-11/internet-explorer-tile_10-11.svg';
import samsungInternet from '@browser-logos/samsung-internet/samsung-internet.svg';
import chromium from '@browser-logos/chromium/chromium_128x128.png';
import safariIos from '@browser-logos/safari-ios/safari-ios.svg';
import safari from '@browser-logos/safari/safari_128x128.png';
import yandex from '@browser-logos/yandex/yandex_128x128.png';
import electron from '@browser-logos/electron/electron.svg';
import firefox from '@browser-logos/firefox/firefox.svg';
import chrome from '@browser-logos/chrome/chrome.svg';
import opera from '@browser-logos/opera/opera.svg';
import uc from '@browser-logos/uc/uc_128x128.png';
import edge from '@browser-logos/edge/edge.svg';

// These are the mappings for the names that we are getting our of the user agent parser
// within eum-acceptor.
//
// The list was generated by retrieving the top N browsers across all our customers in both
// EU and US
export const userAgentParserBrowserNameToIcon = {
  chrome: chrome,
  'chrome mobile': chrome,
  'chrome mobile webview': chrome,
  'chrome mobile ios': chrome,
  chromium: chromium,

  firefox: firefox,
  'firefox mobile': firefox,
  'firefox ios': firefox,

  safari: safari,
  'mobile safari ui/wkwebview': safariIos,
  'mobile safari': safariIos,

  opera: opera,
  'opera mini': opera,
  'opera mobile': opera,

  'samsung internet': samsungInternet,
  edge: edge,
  ie: internetExplorer,
  'yandex browser': yandex,
  'uc browser': uc,
  electron: electron
};
