FROM registry.internal.instana.io/instana/nginx-nodejs:latest

MAINTAINER Ben Ripkens "ben@instana.com"

LABEL com.instana.commit.id="{{GIT_COMMIT}}"

COPY deployment/nginx.conf.j2 /etc/nginx/nginx.conf.j2
COPY deployment/mime.types /etc/nginx/mime.types
COPY deployment/.htpasswd /etc/nginx/.htpasswd
COPY target /opt/www
COPY deployment/config.json.j2 /opt/www/config.json.j2
COPY deployment/serverConfig.json.j2 /opt/www/serverConfig.json.j2
COPY deployment/star_instana_io.crt /etc/ssl/certs/star_instana_io.crt
COPY deployment/star_instana_io.key /opt/www/star_instana_io.key.j2
COPY deployment/dhgroup.pem /etc/ssl/dhgroup.pem

CMD ["/sbin/my_init"]

# prepare folders for deamons
RUN mkdir /etc/service/nginx
RUN mkdir /etc/service/in-server

# copy scripts to that folders and call them 'run'
# see https://github.com/phusion/baseimage-docker#adding_additional_daemons for additional information
ADD deployment/services/nginx.sh /etc/service/nginx/run
ADD deployment/services/in-server.sh /etc/service/in-server/run

EXPOSE 80 443
