FROM registry-internal.instana.io/instana/nodejs:latest

MAINTAINER Ben Ripkens "ben@instana.com"

LABEL com.instana.commit.id="{{INSTANA_UICLIENT_COMMIT}}" \
      com.instana.branch="{{INSTANA_UICLIENT_BRANCH}}" \
      com.instana.image.tag="{{INSTANA_CONTAINER_TAG}}"

# Using this in combination with a .dockerignore file to reduce
# the number of copy operations (and thus layers).
COPY . /opt/all

RUN mkdir -p /etc/service/in-server && \

    mv /opt/all/target                             /opt/www && \
    mv /opt/all/deployment/config.json.j2          /opt/www/config.json.j2 && \
    mv /opt/all/deployment/serverConfig.json.j2    /opt/www/serverConfig.json.j2 && \
    mv /opt/all/deployment/services/in-server.sh   /etc/service/in-server/run && \
    mv /opt/all/deployment/discovery               /opt/discovery && \
    mv /opt/all/deployment/ext-discovery/*         /opt/discovery/ && \

    # Install dependencies inside the container. We need to do this to compile
    # native extensions against the image's operating system. This makes the
    # build a bit slower, but is the only technically correct way.
    cd /opt/www && \
    npm install --production && \

    # Now that we moved all files, we can remove the all directory and
    # all the other files that were only interesting for the image
    # setup
    apt-get clean && \
    apt-get purge && \
    rm -rf /opt/all /var/lib/apt/lists/* /tmp/* /var/tmp/**

CMD ["/sbin/my_init"]
