/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */

import {
  track,
  ANALYZE_LOGGING_QUERY_BUILDER_FILTER_ADDED,
  ANALYZE_LOGGING_QUERY_BUILDER_QUERY_CHANGED,
  ANALYZE_LOGGING_QUERY_BUILDER_GROUP_ADDED,
  ANALYZE_LOGGING_QUERY_BUILDER_CHART_CHANGED,
  ANALYZE_LOGGING_LOAD_MORE_CLICKED,
  ANALYZE_LOGGING_SELECTED_TAGS_CHANGED,
  ANALYZE_LOGGING_TIMEFRAME_USED,
  ANALYZE_LOGGING_LOG_MESSAGE_PARAMETER_CLICKED,
  ANALYZE_LOGGING_FACETTEDSEARCH_ITEM_CLICKED,
  ANALYZE_LOGGING_FACETTEDSEARCH_GROUP_CLICKED,
  ANALYZE_LOGGING_JUMP_TO_LOGS,
  ANALYZE_LOGGING_TIME_SPENT
} from 'in-services/tracking/tracking';

export const filterAdded = e => track(ANALYZE_LOGGING_QUERY_BUILDER_FILTER_ADDED, e);
export const queryChanged = e => track(ANALYZE_LOGGING_QUERY_BUILDER_QUERY_CHANGED, e);
export const groupAdded = e => track(ANALYZE_LOGGING_QUERY_BUILDER_GROUP_ADDED, e);
export const chartChanged = e => track(ANALYZE_LOGGING_QUERY_BUILDER_CHART_CHANGED, e);
export const selectedChanged = e => track(ANALYZE_LOGGING_SELECTED_TAGS_CHANGED, e);
export const loadMoreClicked = e => track(ANALYZE_LOGGING_LOAD_MORE_CLICKED, e);
export const timeframeUsed = e => track(ANALYZE_LOGGING_TIMEFRAME_USED, e);
export const logMessageParameterClicked = e => track(ANALYZE_LOGGING_LOG_MESSAGE_PARAMETER_CLICKED, e);
export const facettedSearchGroupClicked = e => track(ANALYZE_LOGGING_FACETTEDSEARCH_GROUP_CLICKED, e);
export const facettedSearchItemClicked = e => track(ANALYZE_LOGGING_FACETTEDSEARCH_ITEM_CLICKED, e);
export const jumpToLogs = e => track(ANALYZE_LOGGING_JUMP_TO_LOGS, e);
export const timeSpent = e => track(ANALYZE_LOGGING_TIME_SPENT, e);
