export const plugins = {
  availabilityZone: 'availabilityZone',
  cassandra: 'cassandraNode',
  cassandraCluster: 'cassandraCluster',
  dropwizard: 'dropwizardApplicationContainer',
  docker: 'docker',
  ec2: 'ec2',
  elasticsearch: 'elasticsearchNode',
  elasticsearchCluster: 'elasticsearchCluster',
  httpd: 'httpd',
  jbossas: 'jBossAsApplicationContainer',
  javaWebApp: 'genericJavaWebapp',
  jira: 'jiraApplication',
  jvm: 'jvmRuntimePlatform',
  kafka: 'kafka',
  mongodb: 'mongoDb',
  mssql: 'msSqlDatabase',
  mysql: 'mySqlDatabase',
  postgresql: 'postgreSqlDatabase',
  mariaDbDatabase: 'mariaDbDatabase',
  nginx: 'nginx',
  nodejs: 'nodeJsRuntimePlatform',
  nodejsApp: 'genericNodejsApp',
  nodejsCluster: 'nodeJsCluster',
  os: 'host',
  phpfpm: 'phpFpmRuntimePlatform',
  process: 'process',
  redis: 'redis',
  rabbitmq: 'rabbitMq',
  springboot: 'springbootApplicationContainer',
  tomcat: 'tomcatApplicationContainer',
  msiis: 'msiis',
  genericHardware: 'genericHardware',
  genericZone: 'genericZone',
  unmonitoredHost: 'unmonitoredHost',
  haproxy: 'hAProxy',
  oracledb: 'oracleDB',

  // TODO TEMPORARY HACK FOR PROCESS VIEW
  dummyJavaApp: 'dummyJavaApp',
  dummyMysqlSchema: 'dummyMysqlSchema',
  dummyMysqlDb: 'dummyMysqlDb',
  dummyTomcat: 'dummyTomcat',
  dummyConnection: 'dummyConnection'
};
