/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */
import React from 'react';

import InfrastructureEntityLinkPresenter from 'in-analyze/TraceDetail/components/CallDetails/components/InfrastructureEntityLink/InfrastructureEntityLinkPresenter';

export default {
  title: 'Templates|analyze/CallDetail/InfraEntityLink',
  component: InfrastructureEntityLinkPresenter
};

export function Default() {
  return <InfrastructureEntityLinkPresenter entity={entity} snapshot={snapshot} plugin="nodeJsRuntimePlatform" />;
}
export function CorrelationMissing() {
  return <InfrastructureEntityLinkPresenter />;
}
export function Loading() {
  return <InfrastructureEntityLinkPresenter snapshot={{ progress: { loading: true } }} />;
}

const entity = {
  id: 'SnPyGceVfHY1nwTjo-o_7SbMqLk',
  time: 1570594567000,
  label: 'shop-frontend v1.0.0',
  plugin: 'nodeJsRuntimePlatform'
};

const snapshot = new Map(
  Object.entries({
    dependencies: [
      {
        direction: 'outgoing',
        type: 'is',
        key: 'com.instana.forge.infrastructure.os.process.graph.ProcessDependency=EC2-i-b5885e26.6642'
      }
    ],
    from: 1570594567000,
    data: {
      'gc.statsSupported': true,
      healthchecks: [],
      http: {
        '::3016': {
          type: 'http',
          address: {
            address: '::',
            family: 'IPv6',
            port: 3016
          }
        }
      },
      dependencies: {
        statuses: '1.4.0',
        'on-finished': '2.3.0',
        'balanced-match': '1.0.0',
        'set-blocking': '2.0.0',
        'tunnel-agent': '0.6.0',
        'mime-types': '2.1.24',
        moment: '2.24.0',
        'safe-buffer': '5.1.2',
        'npm-bundled': '1.0.6',
        '@instana/core': '1.70.0',
        mkdirp: '0.5.1',
        shimmer: '1.2.0',
        once: '1.4.0',
        rimraf: '2.4.5',
        'assert-plus': '1.0.0',
        minizlib: '1.2.1',
        abbrev: '1.1.1',
        yallist: '3.0.3',
        qs: '6.5.2',
        'content-disposition': '0.5.2',
        'signal-exit': '3.0.2',
        sshpk: '1.16.1',
        'concat-map': '0.0.1',
        'ee-first': '1.1.1',
        'ignore-walk': '3.0.1',
        'fast-deep-equal': '2.0.1',
        forwarded: '0.1.2',
        dashdash: '1.14.1',
        cookie: '0.3.1',
        'fs.realpath': '1.0.0',
        'strip-json-comments': '2.0.1',
        ini: '1.3.5',
        'os-homedir': '1.0.2',
        'brace-expansion': '1.1.11',
        'file-uri-to-path': '1.0.0',
        'aws-sign2': '0.7.0',
        nopt: '4.0.1',
        tar: '4.4.10',
        'util-deprecate': '1.0.2',
        'safe-json-stringify': '1.2.0',
        ms: '2.1.2',
        'json-schema': '0.2.3',
        'request-promise-native': '1.0.7',
        'raw-body': '2.3.3',
        getpass: '0.1.7',
        'core-util-is': '1.0.2',
        unpipe: '1.0.0',
        'safer-buffer': '2.1.2',
        minipass: '2.3.5',
        semver: '5.5.1',
        'fs-minipass': '1.2.6',
        'combined-stream': '1.0.8',
        'detect-libc': '1.0.3',
        send: '0.16.2',
        osenv: '0.1.5',
        caseless: '0.12.0',
        'event-loop-stats': '1.1.0',
        'is-fullwidth-code-point': '1.0.0',
        mv: '2.1.1',
        'node-pre-gyp': '0.13.0',
        psl: '1.2.0',
        'string-width': '1.0.2',
        isstream: '0.1.2',
        'process-nextick-args': '2.0.1',
        'uri-js': '4.2.2',
        'body-parser': '1.18.3',
        'has-unicode': '2.0.1',
        negotiator: '0.6.2',
        sax: '1.2.4',
        extsprintf: '1.3.0',
        bytes: '3.0.0',
        accepts: '1.3.7',
        bunyan: '1.8.12',
        'delayed-stream': '1.0.0',
        'wide-align': '1.1.3',
        aproba: '1.2.0',
        '@instana/collector': '1.70.0',
        'serve-static': '1.13.2',
        'fast-json-stable-stringify': '2.0.0',
        ajv: '6.10.1',
        tweetnacl: '0.14.5',
        'content-type': '1.0.4',
        fresh: '0.5.2',
        bindings: '1.5.0',
        'stealthy-require': '1.1.1',
        delegates: '1.0.0',
        minimatch: '3.0.4',
        needle: '2.4.0',
        'cookie-signature': '1.0.6',
        'merge-descriptors': '1.0.1',
        'media-typer': '0.3.0',
        request: '2.88.0',
        'range-parser': '1.2.1',
        isarray: '1.0.0',
        jsprim: '1.4.1',
        'request-promise-core': '1.1.2',
        'http-errors': '1.6.3',
        'code-point-at': '1.1.0',
        'array-flatten': '1.1.1',
        express: '4.16.4',
        'proxy-addr': '2.0.5',
        rc: '1.2.8',
        chownr: '1.1.2',
        'is-typedarray': '1.0.0',
        'path-is-absolute': '1.0.1',
        vary: '1.1.2',
        verror: '1.10.0',
        methods: '1.1.2',
        'emitter-listener': '1.1.2',
        'path-to-regexp': '0.1.7',
        'http-signature': '1.2.0',
        debug: '3.2.6',
        'form-data': '2.3.3',
        'oauth-sign': '0.9.0',
        wrappy: '1.0.2',
        mime: '1.4.1',
        finalhandler: '1.1.1',
        'gcstats.js': '1.0.0',
        minimist: '0.0.8',
        'json-stringify-safe': '5.0.1',
        etag: '1.8.1',
        asn1: '0.2.4',
        inflight: '1.0.6',
        depd: '1.1.2',
        'har-schema': '2.0.0',
        jsbn: '0.1.1',
        lodash: '4.17.14',
        'tough-cookie': '2.4.3',
        'is-bluebird': '1.0.2',
        'cls-bluebird': '2.1.0',
        string_decoder: '1.1.1',
        'mime-db': '1.40.0',
        setprototypeof: '1.1.0',
        aws4: '1.8.0',
        'escape-html': '1.0.3',
        'strip-ansi': '3.0.1',
        glob: '6.0.4',
        inherits: '2.0.4',
        opentracing: '0.14.3',
        npmlog: '4.1.2',
        gauge: '2.7.4',
        'json-schema-traverse': '0.4.1',
        'are-we-there-yet': '1.1.5',
        'npm-packlist': '1.4.4',
        encodeurl: '1.0.2',
        'performance-now': '2.1.0',
        'bcrypt-pbkdf': '1.0.2',
        'redis-commands': '1.5.0',
        asynckit: '0.4.0',
        extend: '3.0.2',
        destroy: '1.0.4',
        'serialize-error': '2.1.0',
        nan: '2.14.0',
        ncp: '2.0.0',
        'deep-extend': '0.6.0',
        uuid: '3.3.2',
        'async-hook-jl': '1.7.6',
        'utils-merge': '1.0.1',
        'event-loop-lag': '1.4.0',
        'number-is-nan': '1.0.1',
        'console-control-strings': '1.1.0',
        netlinkwrapper: '1.1.2',
        parseurl: '1.3.3',
        'stack-chain': '1.3.7',
        punycode: '2.1.1',
        'type-is': '1.6.18',
        'ecc-jsbn': '0.1.2',
        'ansi-regex': '2.1.1',
        'v8-profiler-node8': '6.1.1',
        'dtrace-provider': '0.8.7',
        'object-assign': '4.1.1',
        'readable-stream': '2.3.6',
        'har-validator': '5.1.3',
        'iconv-lite': '0.4.24',
        'os-tmpdir': '1.0.2',
        'ipaddr.js': '1.9.0',
        'forever-agent': '0.6.1'
      },
      keywords: ['shop', 'user interface'],
      pid: 6642,
      name: 'shop-frontend',
      execArgs: [],
      startTime: 1570594189871,
      directDependencies: {
        peerDependencies: {},
        dependencies: {
          request: '^2.88.0',
          express: '4.16.4',
          'request-promise-native': '^1.0.5',
          '@instana/collector': 'latest'
        },
        optionalDependencies: {},
        'shop-frontend': '1.0.0'
      },
      'libuv.statsSupported': true,
      version: '1.0.0',
      heapSpaces: ['code_space', 'large_object_space', 'map_space', 'new_space', 'old_space', 'read_only_space'],
      versions: {
        uv: '1.23.2',
        node: '10.12.0',
        v8: '6.8.275.32-node.35',
        openssl: '1.1.0i',
        tz: '2018e',
        modules: '64',
        zlib: '1.2.11',
        napi: '3',
        nghttp2: '1.34.0',
        http_parser: '2.8.0',
        cldr: '33.1',
        icu: '62.1',
        unicode: '11.0',
        ares: '1.14.0'
      },
      description: 'Provides access to the shop.',
      args: ['/usr/local/bin/node', '/opt/shop-frontend/src/index'],
      sensorVersion: '1.70.0'
    },
    processorTags: ['shop', 'user interface'],
    plugin: 'nodeJsRuntimePlatform',
    label: 'shop-frontend v1.0.0',
    timestamp: 1570594567000,
    volatileId: {
      host_id: 'EC2-i-b5885e26',
      sensor_name: 'com.instana.plugin.nodejs',
      entity_id: '6642'
    },
    id: 'SnPyGceVfHY1nwTjo-o_7SbMqLk',
    to: null,
    entityId: {
      host: 'EC2-i-b5885e26',
      pluginId: 'com.instana.forge.infrastructure.runtime.nodejs.NodeJsRuntimePlatform',
      steadyId: '6642'
    }
  })
);
