import React from 'react';

import DashboardSection from 'in-sdk/components/dashboard/DashboardSection';
import { number, seconds } from 'in-services/formatters/number';
import Chart from 'in-components/Chart';

export default function AwsElbAppDashboard({ snapshot, timeframe }) {
  const snapshotId = snapshot.get('id');

  return (
    <div>
      <DashboardSection title="Connections">
        <Chart
          snapshotId={snapshotId}
          timeframe={timeframe}
          y1={{
            min: 0,
            metrics: ['active_connection_count', 'new_connection_count', 'rejected_connection_count'],
            labels: ['Active', 'New', 'Rejected'],
            type: 'line',
            formatter: number.compact
          }}
        />
      </DashboardSection>

      <DashboardSection title="Request count (generated by a targets)">
        <Chart
          snapshotId={snapshotId}
          timeframe={timeframe}
          y1={{
            min: 0,
            metrics: ['request_count', 'target_2XX_count', 'target_3XX_count', 'target_4XX_count', 'target_5XX_count'],
            labels: [
              'All Requests',
              'Requests with Status Code 2xx',
              'Requests with Status Code 3xx',
              'Requests with Status Code 4xx',
              'Requests with Status Code 5xx'
            ],
            type: 'line',
            formatter: number.compact
          }}
        />
      </DashboardSection>

      <DashboardSection title="The number of HTTP error codes that originate from the load balancer">
        <Chart
          snapshotId={snapshotId}
          timeframe={timeframe}
          y1={{
            min: 0,
            metrics: ['elb_4XX_count', 'elb_5XX_count'],
            labels: ['Status Code 4xx', 'Status Code 5xx'],
            type: 'line',
            formatter: number.compact
          }}
        />
      </DashboardSection>

      <DashboardSection title="The time elapsed after the request leaves the load balancer until a response from the target is received">
        <Chart
          snapshotId={snapshotId}
          timeframe={timeframe}
          y1={{
            min: 0,
            metrics: ['target_response_time'],
            labels: ['Response Time'],
            type: 'line',
            formatter: seconds.detailed
          }}
          y2={{
            min: 0,
            metrics: ['target_connection_error_count'],
            labels: ['Connection Error Count'],
            type: 'line',
            formatter: number.compact
          }}
        />
      </DashboardSection>

      <DashboardSection title="TLS Error Count">
        <Chart
          snapshotId={snapshotId}
          timeframe={timeframe}
          y1={{
            min: 0,
            metrics: ['client_tls_negotiation_error_count', 'target_tls_negotiation_error_count'],
            labels: ['Client', 'Target'],
            type: 'line',
            formatter: number.compact
          }}
        />
      </DashboardSection>
    </div>
  );
}
