#Sample Otel Collector Config

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  otlp:
    endpoint: otelcol:4317

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [Totlp]
      processors: []
      exporters: [Totlp]
    metrics:
      receivers: [Motlp]
      processors: [Mbatch]
      exporters: [Motlp]
    logs:
      receivers: [Lotlp]
      processors: [Lbatch]
      exporters: [Lotlp]

