/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

// no need for translation, it is only used within tracking
export const pageNames = Object.freeze({
  home: 'Home',
  applications: 'Applications',
  application_summary: 'Application > Summary',
  service_summary: 'Service > Summary',
  services: 'Services',
  smart_alerts: 'Smart Alerts',
  websites: 'Websites',
  website_summary: 'Website > Summary',
  mobile_apps: 'Mobile Apps',
  processes: 'Processes',
  activities: 'Activities',
  locations: 'Locations',
  tests: 'Tests',
  incidents: 'Incidents',
  issues: 'Issues',
  analytics: 'Analytics',
  endpoint: 'Endpoint',
  custom_end_point_config: 'Endpoint > Configure Endpoint',
  endpoint_summary: 'Endpoint > Summary',
  bizops: 'BizOps',
  cloud_foundary_applications: 'Cloud Foundry Applications',
  cloud_foundary_application_summary: 'Cloud Foundry Application > Summary',
  custom_dashboard: 'Custom Dashboard',
  agents: 'Agents',
  comparison_table: 'Comparison Table',
  zhmcs: 'zHMCs',
  systems: 'Systems',
  system_summary: 'System > summary',
  infrastructure: 'Infrastructure',
  infrastructure_dashboard: 'Infrastructure -> Dashboard',
  infra_smart_alert_deatils: 'Infra Smart Alerts Details Page',
  infra_smart_alerts: 'Infra Smart Alerts',
  infra_comparison_table: 'Infrastructure > Comparison table',
  clusters: 'Clusters',
  cluster_summary: 'Cluster > summary',
  vsphere: 'vSphereDatacenters',
  user_settings: 'User Settings',
  team_settings: 'Team Settings',
  cron_job_summary: 'Cron Jobs > Summary',
  namespace_summary: 'Namespaces > Summary',
  node_summary: 'Nodes > Summary',
  pod_summary: 'Pods >Summary',
  k8s_service_summary: 'K8s Services > Summary',
  map: 'Map',
  migration: 'Migration',
  compute_instances: 'Compute Instances',
  hypervisors: 'Hypervisors',
  event_description: 'event > description',
  event: 'Event',
  infra_explore: 'Infra Explore',
  regions: 'Regions',
  logical_partition: 'Logical Partition',
  logical_partition_summary: 'Logical Partition > Summary',
  phmc: 'pHMC',
  phmc_systems: 'phmc Systems',
  vios: 'Virtual I/O Server',
  vios_summary: 'Virtual I/O Server > Summary',
  vsphere_vm: 'vSphere VM',
  vsphere_esxi_host: 'vSphere ESXi Host',
  vsphere_data_center: 'vSphere Datacenter',
  synthetic_monitoring: 'Synthetic Monitoring',
  synthetic_monitoring_tests: 'Tests',
  shared_processor_pool: 'Shared Processor Pools',
  sap_databases: 'Databases',
  ibmp_phmcs: 'IBM Power HMC',
  ibmp_phmcs_systems: 'IBM Power HMC Systems',
  sap_db_instance: 'DB Instance',
  abap_system: 'Abap System',
  abap_instance: 'ABAP Instance',
  sap_dbms: 'SAP DB2',
  sap_hana: 'SAP Hana',
  sap_db_tenant: 'DB Tenant',
  sap_java_instance: 'SAP Java Instance',
  sap_java_system: 'SAP Java System',
  events_all: 'All',
  local_alerts: 'Local Alert Details',
  global_alerts: 'Global Alert Details',
  instances: 'Instances',
  deployment_summary: 'Deployment > Summary'
} as const);
type PageNameKeys = keyof typeof pageNames;
export type PageName = (typeof pageNames)[PageNameKeys];
