/*
 * IBM Confidential
 * PID 5737-N85, 5900-AG5
 * Copyright IBM Corp. 2023
 */

// no need for translation, it is only used within tracking
export const pageNames = Object.freeze({
  home: 'Home',
  agent_catalog: 'Agent Catalog',
  applications: 'Applications',
  application_summary: 'Application > Summary',
  service_summary: 'Service > Summary',
  services: 'Services',
  subtraces: 'Subtraces',
  smart_alerts: 'Smart Alerts',
  smart_alerts_tearsheet: 'Smart Alerts (New)',
  websites: 'Websites',
  website: 'Website',
  website_summary: 'Website > Summary',
  mobile_apps: 'Mobile Apps',
  mobile_app_summary: 'Mobile App > Summary',
  mobile_app_view_summary: 'Mobile App View > Summary',
  mobile_app_session_start: 'Analytics > Mobile App Session Start',
  processes: 'Processes',
  profiles: 'Profiles',
  activities: 'Activities',
  locations: 'Locations',
  tests: 'Tests',
  incidents: 'Incidents',
  issues: 'Issues',
  analytics: 'Analytics',
  endpoint: 'Endpoint',
  custom_end_point_config: 'Endpoint > Configure Endpoint',
  endpoint_summary: 'Endpoint > Summary',
  bizops: 'Business Monitoring',
  bizops_processes: 'Business Processes',
  bizops_process: 'Business Process',
  bizops_activity: 'Business Activity',
  bizops_perspectives: 'Business Perspectives',
  bizops_perspective: 'Business Perspective',
  cloud_foundary_applications: 'Cloud Foundry Applications',
  cloud_foundary_application_summary: 'Cloud Foundry Application > Summary',
  custom_dashboard: 'Custom Dashboard',
  agents: 'Agents',
  comparison_table: 'Comparison Table',
  zhmcs: 'zHMCs',
  ibm_zhmcs: 'IBM Z HMCs',
  systems: 'Systems',
  system_summary: 'System > summary',
  infrastructure: 'Infrastructure',
  infra_map: 'Infrastructure > Map',
  infrastructure_dashboard: 'Infrastructure -> Dashboard',
  infra_smart_alert_deatils: 'Infra Smart Alerts Details Page',
  infra_smart_alerts: 'Infra Smart Alerts',
  infra_comparison_table: 'Infrastructure > Comparison table',
  infra_graph_explorer: 'Infrastructure > Graph explorer',
  clusters: 'Clusters',
  kubernetes_clusters: 'Kubernetes > Clusters',
  kubernetes_namespaces: 'Kubernetes > Namespaces',
  cluster_summary: 'Cluster > summary',
  cluster_cost: 'Cluster > Cost',
  vsphere: 'vSphereDatacenters',
  user_settings: 'User Settings',
  securityAndAccess: 'Security & Access',
  global_settings: 'Global Settings',
  account_and_billing: 'Account & Billing',
  license: 'Account & Billing > Licenses',
  cron_job_summary: 'Cron Jobs > Summary',
  namespace_summary: 'Namespaces > Summary',
  node_summary: 'Nodes > Summary',
  persistent_volume_summary: 'PersistentVolumes > Summary',
  pod_summary: 'Pods >Summary',
  k8s_service_summary: 'K8s Services > Summary',
  map: 'Map',
  migration: 'Migration',
  compute_instances: 'Compute Instances',
  hypervisors: 'Hypervisors',
  event: 'Event',
  event_generate_with_watsonx: 'Event > Generate With watsonx',
  events: 'Events',
  infra_explore: 'Infra Explore',
  regions: 'Regions',
  logical_partition: 'Logical Partition',
  logical_partition_summary: 'Logical Partition > Summary',
  phmc: 'pHMC',
  phmc_systems: 'phmc Systems',
  vios: 'Virtual I/O Server',
  vios_summary: 'Virtual I/O Server > Summary',
  vsphere_vm: 'vSphere VM',
  vsphere_esxi_host: 'vSphere ESXi Host',
  vsphere_data_center: 'vSphere Datacenter',
  vulnerability_overview: 'Vulnerability Overview',
  synthetic_monitoring: 'Synthetic Monitoring',
  synthetic_test_result: 'Synthetic Test Result >  Details',
  synthetic_test: 'Synthetic Test',
  synthetic_monitoring_alert: 'Synthetic Monitoring > Smart Alerts',
  synthetic_monitoring_tests: 'Synthetic Monitoring > Tests',
  synthetic_credentials: 'Credentials',
  shared_processor_pool: 'Shared Processor Pools',
  sap_databases: 'Databases',
  ibmp_phmcs: 'IBM Power HMC',
  ibmp_phmcs_systems: 'IBM Power HMC Systems',
  sap_db_instance: 'DB Instance',
  abap_system: 'Abap System',
  abap_instance: 'ABAP Instance',
  abap_instance_summary: 'ABAP Instance > Summary',
  abap_instance_system_overview: 'ABAP Instance > System Overview',
  abap_instance_transactional_statistics: 'ABAP Instance > Transactional Statistics',
  abap_instance_networks: 'ABAP Instance > Networks',
  abap_instance_fiori: 'ABAP Instance > Fiori',
  abap_instance_idoc: 'ABAP Instance > IDoc',
  abap_instance_related_resources: 'ABAP Instance > Related Resources',
  sap_dbms: 'SAP DB2',
  sap_hana: 'SAP Hana',
  sap_db_tenant: 'DB Tenant',
  sap_java_instance: 'SAP Java Instance',
  sap_java_system: 'SAP Java System',
  open_stack_region_hypervisors: 'OpenStack Region > Hypervisors',
  open_stack_region_hypervisor_summary: 'OpenStack Region Hypervisor > Summary',
  open_stack_region_compute_instance_summary: 'OpenStack Region Compute Instance > Summary',
  open_stack_region_compute_instances: 'Compute Instances > Hypervisors',
  open_stack_regions: 'OpenStack Regions',
  sap_hana_system: 'SAP Hana System',
  sap_web_dispatcher: 'Sap Web Dispatcher',
  sap_abap_sensor: 'SAP ABAP Sensor > Summary',
  events_all: 'All',
  local_alerts: 'Local Alert Details',
  logs: 'Logs',
  log_smart_alerts: 'Log Smart Alerts',
  global_alerts: 'Global Alert Details',
  instances: 'Instances',
  deployment_summary: 'Deployment > Summary',
  powervc_hypervisors: 'RegionOne > Hypervisors',
  powervc_regions: 'regions',
  powervc_compute_Instances: 'Compute Instances',
  powervc: 'PowerVC',
  service_levels: 'Service Levels',
  service_level_objective: 'Service Level Objective',
  slo_summary: 'Service Level Objective > Summary',
  slo_config: 'Service Level Objective > Configuration',
  slo_correction_windows: 'Service Level Objective > Correction windows',
  correction_windows: 'Correction windows',
  automation_action_catalog: 'Automation > Action Catalog',
  automation_action_view: 'Automation > Action Catalog > Action details',
  automation_action_create: 'Automation > Action Catalog > New or Edit Action',
  automation_action_history: 'Automation > Action History',
  automation_policies: 'Automation > Policies',
  automation_policy_view: 'Automation > Policies > Policy details',
  automation_policy_create: 'Automation > Policies > New or Edit Policy',
  automation_generate_script_with_watsonx: 'Automation > Generate script With watsonx',
  custom_payload: 'Custom Payload',
  nutanix_vm: 'Nutanix VM',
  nutanix_host: 'Nutanix Host',
  nutanix_clusters: 'Nutanix Clusters',
  nutanix: 'Nutanix',
  xenserver: 'XenServer',
  xenserver_host: 'XenServer Host',
  windowshypervisor: 'Windows Hypervisor',
  linuxkvmhypervisor: 'Linux KVM Hypervisor',
  linuxkvmhypervisor_host: 'Linux KVM Hypervisor Host'
} as const);
type PageNameKeys = keyof typeof pageNames;
export type PageName = (typeof pageNames)[PageNameKeys];
