import { number } from 'in-services/formatters/number';

export default [
  {
    metrics: [
      'Merge',
      'ReplicatedFetch',
      'ReplicatedSend',
      'ReplicatedChecks',
      'BackgroundPoolTask',
      'DiskSpaceReservedForMerge',
      'DistributedSend',
      'QueryPreempted',
      'TCPConnection',
      'HTTPConnection',
      'InterserverConnection',
      'OpenFileForRead',
      'OpenFileForWrite',
      'Read',
      'Write',
      'SendExternalTables',
      'QueryThread',
      'ReadonlyReplica',
      'LeaderReplica',
      'MemoryTracking',
      'MemoryTrackingInBackgroundProcessingPool',
      'MemoryTrackingForMerges',
      'LeaderElection',
      'EphemeralNode',
      'ZooKeeperWatch',
      'DelayedInserts',
      'ContextLockWait',
      'StorageBufferRows',
      'StorageBufferBytes',
      'DictCacheRequests',
      'Revision',
      'RWLockWaitingReaders',
      'RWLockWaitingWriters',
      'RWLockActiveReaders',
      'RWLockActiveWriters'
    ],
    labels: [
      'Merge',
      'Replicated Fetch',
      'Replicated Send',
      'Replicated Checks',
      'Background Pool Task',
      'Disk Space Reserved For Merge',
      'Distributed Send',
      'Query Preempted',
      'TCP Connection',
      'HTTP Connection',
      'Interserver Connection',
      'Open File For Read',
      'Open File For Write',
      'Read',
      'Write',
      'Send External Tables',
      'Query Thread',
      'Readonly Replica',
      'Leader Replica',
      'Memory Tracking',
      'Memory Tracking In Background Processing Pool',
      'Memory Tracking For Merges',
      'Leader Election',
      'Ephemeral Node',
      'Zoo Keeper Watch',
      'Delayed Inserts',
      'Context Lock Wait',
      'Storage Buffer Rows',
      'Storage Buffer Bytes',
      'Dict Cache Requests',
      'Revision',
      'RW Lock Waiting Readers',
      'RW Lock Waiting Writers',
      'RW Lock Active Readers',
      'RW Lock Active Writers'
    ],
    min: 0,
    category: ['ClickHouse'],
    formatter: number
  }
];
