apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-pr
spec:
  steps:
    - name: echo
      image: docker-na-public.artifactory.swg-devops.com/hyc-katamari-cicd-team-docker-local/base-images/ubi-builder:latest
      script: |
        #!/bin/sh
        echo "Hello pr"  