/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */

import {
  EQUALS,
  CONTAINS,
  LESS_THAN,
  GREATER_THAN,
  NOT_EMPTY,
  IS_EMPTY,
  NOT_EQUAL,
  NOT_CONTAIN,
  NOT_BLANK,
  IS_BLANK,
  STARTS_WITH,
  ENDS_WITH,
  NOT_STARTS_WITH,
  NOT_ENDS_WITH,
  GREATER_OR_EQUAL_THAN,
  LESS_OR_EQUAL_THAN
} from 'in-components/QueryBuilder/tagFilter/operators';

export const BOOLEAN = [EQUALS];

export const STRING = [
  EQUALS,
  NOT_EQUAL,
  CONTAINS,
  NOT_CONTAIN,
  NOT_EMPTY,
  IS_EMPTY,
  STARTS_WITH,
  ENDS_WITH,
  NOT_STARTS_WITH,
  NOT_ENDS_WITH
];
export const STRING_SET = STRING;
export const STRING_LIST = STRING_SET;

export const NUMBER = [
  EQUALS,
  NOT_EQUAL,
  LESS_THAN,
  GREATER_THAN,
  NOT_EMPTY,
  IS_EMPTY,
  LESS_OR_EQUAL_THAN,
  GREATER_OR_EQUAL_THAN
];

export const KEY_VALUE_PAIR = [
  EQUALS,
  NOT_EQUAL,
  CONTAINS,
  NOT_CONTAIN,
  NOT_EMPTY,
  IS_EMPTY,
  STARTS_WITH,
  ENDS_WITH,
  NOT_BLANK,
  IS_BLANK
];
