export default {
  canConfigureServiceMapping: 'Service & Endpoint Mapping',
  canConfigureEumApplications: 'Website Monitoring Configuration',
  canConfigureMobileAppMonitoring: 'Mobile App Monitoring Configuration',
  canConfigureUsers: 'User management',
  canConfigureRoles: 'Access role configuration',
  canConfigureTeams: 'Access team configuration',
  canInstallNewAgents: 'Agent download and agent key visibility',
  canSeeUsageInformation: 'Access to license usage',
  canSeeOnPremLicenseInformation: 'Access to on prem license usage',
  canConfigureIntegrations: 'Configuration of integrations',
  canConfigureCustomAlerts: 'Configuration of custom alerts',
  canConfigureApiTokens: 'Configuration of API tokens',
  canConfigureAgentRunMode: 'Configuration of agent mode',
  canViewAuditLog: 'Access to audit log',
  canConfigureAgents: 'Configuration of agents',
  canConfigureApplications: 'Configuration of applications',
  canConfigureAuthenticationMethods: 'Configuration of authentication methods',
  canConfigureLogManagement: 'Configuration of log management',
  canConfigureReleases: 'Configuration of releases'
};
