---
title: Not Monitoring
...

Instana is not receiving any data from agents.
Please install the Instana agent on the systems you want to monitor. Installation instructions have been provided to you with the welcome e-mail.

If you have installed agents, please check for errors during agent startup, network connectivity to Instana and if you have a valid license.

If you need our help please contact us for further support.
