---
title: Not Monitoring
...

Instana is currently not receiving any data from agents.
Please install the Instana agent on the systems you want to monitor. Installation instructions are available in our [online documentation][Docs].

If you have already installed agents, please check the agent log for errors during startup, network connectivity to Instana and if you have a valid license.

Should you need additional assistance, please contact us via our [support portal][Support].


[Docs]:https://instana.atlassian.net/wiki/display/DOCS/The+Agent
[Support]:https://support.instana.com
