---
title: Shortcuts
...

Some important functions of Instana can be activated using keyboard shortcuts.

 - `c` : centering the map
 - `f` : open and focusing the searchbar
 - `esc` : close the sidebar / dashboard that is currently visible
 - `shift + ?` : open the help dialog for shortcuts
