---
title: Using the Search Bar
...

The Instana search functionality can be used to filter the 3D maps, comparison tables, trace- and incident views.
Leveraging the [lucene query syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html), the search bar has
extensive abilities to search using fuzzy and wildcard searches as well as boolean operators. For example, the following
query restricts views to production hosts with less than four CPUs:

`entity.host.cpuCount:<4 AND entity.zone:production`.

## Search Bar Interaction
The search bar supports autocompletion for search fields and will syntax highlight the lucene query while you type.
Once typing, the search bar will propose search fields that match the current input. You can accept proposed fields
by hitting `RETURN`. Hit `CTRL+SPACE` to open the auto completion popup.

## Lucene Query Syntax Cheat Sheet

 - **Fielded search:** `entity.host.cpuCount:>4`
 - **Boolean operators:** `entity.host.cpuCount:<4 AND entity.zone:production`
 - **Grouping:** `(entity.host.cpuCount:<4 AND entity.zone:production) OR entity.host.cpuCount:>4`
 - **Wildcard searches:** `entity.type:*container*`

Please refer to the [documentation](https://instana.atlassian.net/wiki/display/DOCS/Search) for more information.
