---
title: WebGL cannot be initialized
...

You browser supports WebGL, but it can't be initialized. This can happen for some browser and hardware reasons. Some
possible reasons are:

  - too many open tabs
  - lack of a dedicated GPU or a busy GPU
  - browser / hardware incompatibility

For further troubleshooting information please refer to the [WebGL official doku](https://www.khronos.org/webgl/wiki/FAQ).
