/*
 * (c) Copyright IBM Corp. 2021
 * (c) Copyright Instana Inc.
 */
import { number } from 'in-services/formatters/number';

export default [
  {
    metrics: [
      'nomad.client.allocated.cpu',
      'nomad.client.allocated.disk',
      'nomad.client.allocated.iops',
      'nomad.client.allocated.memory',
      'nomad.client.allocations.blocked',
      'nomad.client.allocations.migrating',
      'nomad.client.allocations.pending',
      'nomad.client.allocations.running',
      'nomad.client.allocations.terminal',
      'nomad.client.unallocated.cpu',
      'nomad.client.unallocated.disk',
      'nomad.client.unallocated.iops',
      'nomad.client.unallocated.memory',
      'nomad.nomad.blocked_evals.total_blocked',
      'nomad.nomad.blocked_evals.total_escaped',
      'nomad.nomad.blocked_evals.total_quota_limit',
      'nomad.nomad.broker._core.ready',
      'nomad.nomad.broker._core.unacked',
      'nomad.nomad.broker.total_blocked',
      'nomad.nomad.broker.total_ready',
      'nomad.nomad.broker.total_unacked',
      'nomad.nomad.broker.total_waiting',
      'nomad.nomad.heartbeat.active',
      'nomad.nomad.plan.queue_depth',
      'nomad.nomad.vault.distributed_tokens_revoking',
      'nomad.runtime.alloc_bytes',
      'nomad.runtime.free_count',
      'nomad.runtime.heap_objects',
      'nomad.runtime.malloc_count',
      'nomad.runtime.num_goroutines',
      'nomad.runtime.sys_bytes',
      'nomad.runtime.total_gc_pause_ns',
      'nomad.runtime.total_gc_runs',
      'nomad.uptime'
    ],
    labels: [
      'Total amount of CPU shares the scheduler has allocated to tasks',
      'Total amount of disk space the scheduler has allocated to tasks',
      'Total amount of IOPS the scheduler has allocated to tasks',
      'Total amount of memory the scheduler has allocated to tasks',
      'Blocked allocations',
      'Migrating allocations',
      'Pending allocations',
      'Running allocations',
      'Terminated allocations',
      'Total amount of CPU shares free for the scheduler to allocate to tasks',
      'Total amount of disk space free for the scheduler to allocate to tasks',
      'Total amount of IOPS free for the scheduler to allocate to tasks',
      'Total amount of memory free for the scheduler to allocate to tasks',
      'Total amount of blocked evaluations',
      'Total amount of escaped evaluations',
      'Total quota limit for blocked evaluations',
      'Broker core ready',
      'Broker core unacknowledged',
      'Broker total blocked',
      'Broker total ready',
      'Broker total unacknowledged',
      'Broker total waiting',
      'Heartbeat active',
      'Nomad plan queue depth',
      'Nomad vault distributed tokens revoking',
      'Runtime allocated bytes',
      'Runtime free count',
      'Runtime heap objects',
      'Runtime malloc count',
      'Runtime number of go routines',
      'Runtime system bytes',
      'Runtime total amount of gc pause in ns',
      'Runtime total amount of gc runs',
      'Uptime'
    ],
    min: 0,
    category: ['Nomad'],
    formatter: number
  }
];
